### ISSUE TITLE
Dedicated Server windows size

### ISSUE THREAD

**Issue by alexgdi** [OpenXRay/xray-16#106]
on dev branch. Dedicated Server was open the window size is the same as the client. 
![default](https://cloud.githubusercontent.com/assets/10780496/12079638/7e730140-b251-11e5-90f8-9bfe266f797b.PNG)

**Comment by nitrocaster** [comment]
I plan to make it a pure console app, so that's not really an issue.

**Comment by alexgdi** [comment]
I think it's good decision! Dedicated Server will be located in xrEngine module , or it would be better to implement a separate application ?

**Comment by Xottab-DUTY** [comment]
IMHO i think separate application would be better :)
