### ISSUE TITLE
What with OQ in opengl renderer?

### ISSUE THREAD

**Issue by galek** [OpenXRay/xray-16#107]
I seen source code of the updates renderer, and not found OQ code. 
In original renders this functionality is exist.-So maybe add this in OGL renderer?

BUT:
1) Classic HOQ is very slow - need arrearage on 3 frames - for getting result from GPU
2) Conditional rendering is supported only for opengl3.0 and later(glBeginConditionalRender). 
And: You can use: GL_QUERY_NO_WAIT, but it's works regularly only on NV, in AMD exist bug(in drivers[officially approved]) what GL_QUERY_NO_WAIT=GL_QUERY_WAIT. On Intel - i think what similiar situation ,because all is very slow(worse than without OQ)
3) Is very fast solution - software occlusion culling (on CPU) using SSE(see https://software.intel.com/en-us/blogs/2013/09/06/software-occlusion-culling-update-2)
4) Non-classic HOQ(shader based) - HiZ and Raster HOQ
(see https://github.com/nvpro-samples/gl_occlusion_culling). In my own engine i planned use Raster

**Comment by CrossVR** [comment]
The 1.6 OpenGL renderer is still in a very early stage, if you want to see a more complete implementation you should look at the 1.5 repo.

**Comment by galek** [comment]
I seen your repo, but OQ code is not found

**Comment by CrossVR** [comment]
@galek Then I'm not sure what you mean with OQ code?

**Comment by galek** [comment]
See examples in:

https://www.opengl.org/registry/specs/ARB/occlusion_query.txt
https://www.opengl.org/registry/specs/ARB/occlusion_query2.txt
and https://www.opengl.org/registry/specs/NV/conditional_render.txt -just delete NV post-fix(in opengl4 core)

**Comment by CrossVR** [comment]
You can find the occlusion queries here: https://github.com/OpenXRay/xray-16/blob/dev/src/Layers/xrRender/QueryHelper.h#L46

Just look for files that include QueryHelper.h

**Comment by galek** [comment]
ok, but it is "classic" OQ
