### ISSUE TITLE
Add FXAA to renders (R4 and RGL at least)

### ISSUE THREAD

**Issue by Xottab-DUTY** [OpenXRay/xray-16#109]
Check out **rendering** branch of avoitishin's fork – [avbaula added FXAA for R4 there](8d46862e979eecfcda80bbf9ce10a5909059b598).

**Comment by Swartz27** [comment]
https://github.com/avoitishin/xray-16/commit/8d46862e979eecfcda80bbf9ce10a5909059b598

**Comment by Xottab-DUTY** [comment]
Added for:
- [x] R2 (https://github.com/OpenXRay/xray-16/commit/b337b1a6dfedfe8961b2e59b663aa56126bacc2c)
- [x] R3 (https://github.com/OpenXRay/xray-16/commit/1bd9349807798e2d5f026818d34a7d24a6f53473)
- [x] R4 (https://github.com/OpenXRay/xray-16/commit/380b85b206b376bdd87eceb58346927da6c07664)
- [X] RGL (https://github.com/OpenXRay/xray-16/commit/359ddb87941da33b132f7a0647815e454e28af80, https://github.com/OpenXRay/xray-16/commit/c23e6ac38ee65cc6168b17bfa96ea54f3c001343, https://github.com/OpenXRay/xray-16/commit/65da5a72aba14dc2133ff10a0349246fbaa34dd6)
