### ISSUE TITLE
Implement FMOD sound system

### ISSUE THREAD

**Issue by ghost** [OpenXRay/xray-16#110]
http://www.fmod.org/download/

Before, I've recommended OpenAL Soft, as have others, however, FMOD is far more powerful, and it is also multi-platform. 

It only requires including one header and library file, the dll included with the low level API takes care of the rest. Stuff such as EAX that is included in xrSound could be replaced by FMOD DSP effect equivalents.

**Comment by Lyokanthrope** [comment]
https://www.audiokinetic.com/products/wwise/

Another option is WWise, but I'm not sure about licensing issues and implementation.

**Comment by tamlin-mike** [comment]
While FMOD is "nice", and WWISE is pretty much mandated in UE-engine games, they are both proprietary.
Is proprietary 3rd party audio code really needed? If so, to do what?

If we're only looking at FFT for resampling and frequency shifting, there are free libs for that. For the positional rendering, OpenAL handles it.

What else would one of the proprietary solutions provide that's required?

**Comment by ghost** [comment]
I suppose it's not required, I just need it for my own personal mod. But, I settled on implementing Open AL Soft (very easy, and yes I know you can just use the wrapper, but I wanted it integrated). To further enhance things I downloaded a trial of Phonon 3D and was going to buy it for 3d sound, but, unfortunately, it doesn't support the type of audio format we need.
