### ISSUE TITLE
Effector camera flashing and glitching.

### ISSUE THREAD

**Issue by SpencerBelleau** [OpenXRay/xray-16#117]
https://www.youtube.com/watch?v=f767Sf4Ebcc
An easier way to replicate this is to get hammered ingame then walk diagonally. It seems to happen only during times when the camera is tilting.

**Comment by nitrocaster** [comment]
Does it happen with this specific weapon or with any weapon?

**Comment by SpencerBelleau** [comment]
Any weapon, even no weapon. If you slow it down it seems to be caused my the camera pitch/yaw/roll resetting or shifting rapidly to a set position then back.

**Comment by nitrocaster** [comment]
Yeah, I see.

**Comment by tamlin-mike** [comment]
Are we talking about the (possible) single-frame white frame at ~11-12 seconds, or is it something else? (I don't think one can single-step youtube vdeos in a browser).

I'm sure it'll be dead easy to fix, but it may be pure hell to find. :-)

**Comment by nitrocaster** [comment]
@tamlin-mike We're talking about single frame which doesn't follow the animation. You can download the video to watch it frame-by-frame.

**Comment by tamlin-mike** [comment]
"You can download the video"
Awesome, I didn't know the tube allowed that.

**Comment by culhatsker** [comment]
@tamlin-mike YouTube doesn't restrict video downloading, copyright owners do.

**Comment by Xottab-DUTY** [comment]
@ShokerStlk, don't you know something about this bug? Probably, it was already fixed?

**Comment by SkyLoaderr** [comment]
@Xottab-DUTY Fixed in [3ba633f](https://github.com/OpenXRay/xray-16/commit/3ba633fcff67162e154c4f32f62792635b9e7c74).

**Comment by Xottab-DUTY** [comment]
@SkyLoaderr thank you!
