### ISSUE TITLE
Error LNK1104 missing glbinding.lib

### ISSUE THREAD

**Issue by alexgdi** [OpenXRay/xray-16#126]
On a dev branch Error:LNK1104 missing glbinding.lib. Mistake or under work?

Ошибка    LNK1104 не удается открыть файл "glbinding.lib" xrRender_GL E:\git\xray-16\src\Layers\xrRenderPC_GL\LINK    1   

Ошибка или в процессе работы?

**Comment by Xottab-DUTY** [comment]
Work in progress: glbinding was replaced by glew, but it seems that Armada forgot something :)

(In Russian)
В процессе: вместо glbinding был поставлен обратно glew, но, похоже, Armada, что-то забыл :)

**Comment by alexgdi** [comment]
thx!
P.S. та не переводи0, я понимаю) просто иногда прямо выразить мысли на английском тяжело) проще на русском написать.)

**Comment by Xottab-DUTY** [comment]
Will be waiting when someone fix that :)

P.S.: У меня иногда тоже такая проблема возникает :)
