### ISSUE TITLE
Add BugTrap as submodule

### ISSUE THREAD

**Issue by alexgdi** [OpenXRay/xray-16#127]
Need add BugTrap as submodule or not?

**Comment by tamlin-mike** [comment]
Unless my eyesight is totally broken today, this is already done and issue should be closed.

**Comment by alexgdi** [comment]
@tamlin-mike when this pr been closed issue will be done. https://github.com/OpenXRay/xray-16/pull/136

**Comment by andrew-boyarshin** [comment]
#160 is to resolve this issue when merged.

**Comment by alexgdi** [comment]
#160 was merged so #127 must closed.
