### ISSUE TITLE
Discussion of "proposed engine changes"

### ISSUE THREAD

**Issue by ghost** [OpenXRay/xray-16#13]
I think we should have a place other than IRC to discuss engine changes a bit.

The things in "proposed engine changes" that have a \* after them are things that I've already done, and most of which I've ported to COP already for a friend. Most of those are weapons related, since I'm focusing on working on a weapon related mod.

Soon I will assign tasks to myself, but it sounds like others are interested in weapons as well. Perhaps we should have a seperate branch for these changes as not everyone will want them?
Things I can't do myself but want to see: Abakan firing 2 shots at 1800rpm, fixed abrupt transition between walking, running animations and then idle anim with grenade launcher attached.

To add to the list of other things I've done, I made it so you can't reload while sprinting.

In terms of a comment Kevin/Loner left in the file, in terms of Gore there is skeleton wallmark code (bullet holes on bodies) partly implemented but commented out in places. Unfortunately my attempts with it so far have not been successful, and it would need to be rewritten entirely for DX10&11 it looks like.

**Comment by nitrocaster** [comment]
First of all, I suggest we remove this file and add appropriate tasks into doc/design/tasks.txt (https://github.com/OpenXRay/xray-16/issues/6)

> I made it so you can't reload while sprinting.

Isn't that defined in configs?

**Comment by ghost** [comment]
No, it's not defined in configs, it's new code that had to be added.

As for that file, we can remove it, but I thought it might be a good reference for ideas people may have. I'll leave it up to you.

**Comment by CrossVR** [comment]
I really think any such gameplay changes should be done in a fork though. We could use this repository to preserve and improve vanilla without any changes to the gameplay or visual style. Then that could serve as a good base for people to fork the code and start making their own changes to the gameplay and visual style.
