### ISSUE TITLE
xrAICore compilation fails on VS2015 Update 2

### ISSUE THREAD

**Issue by alexgdi** [OpenXRay/xray-16#133]
Error:  C2338   /RTCc rejects conformant code, so it isn't supported by the C++ Standard Library. Either remove this compiler option, or define _ALLOW_RTCc_IN_STL to acknowledge that you have received this warning.  xrAICore    D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\yvals.h  71

**Comment by nitrocaster** [comment]
Fixed with #135.
