### ISSUE TITLE
Complete build instructions?

### ISSUE THREAD

**Issue by ghost** [OpenXRay/xray-16#139]
Hi, I'm still using the older version of Open Xray that both Avotishin and Revolucas have been working on. However I would like to move to the current Open Xray, regardless of it being WIP.

Unfortunately I have difficulty building the project because not all of the needed dependencies are available in the build.txt link. I know about luabind and luajit, neither of those are a problem.

I can get more specific if needed, I can download the code again and tell you what I'm having trouble with. Unfortunately not all the links are readily available for this stuff, for example I remember gamespy being a bit of an issue.

**Comment by nitrocaster** [comment]
GameSpy is included as a submodule.
Once you cloned the repository, you do `git submodule update --init --recursive`, downloading all submodules.

**Comment by ghost** [comment]
Oh :P Sorry about the dumb post then, I'll go ahead and do that.
