### ISSUE TITLE
Good resource on some Xray issues

### ISSUE THREAD

**Issue by ghost** [OpenXRay/xray-16#141]
http://www.viva64.com/en/b/0405/

**Comment by Kaffeine** [comment]
Duplicate: #140

**Comment by alexgdi** [comment]
:)

**Comment by Swartz27** [comment]
Fuck you Yan. Terribly sorry I didn't notice this was brought up before.
You guys are seriously the largest group of faggots I've ever encountered.
I'm withdrawing all of my support from Open Xray (and technically I was the
original author). However, if there is code I feel like using I'm still
going to use it and not give you cocksuckers any credit at all for your
work.

**Comment by alexgdi** [comment]
@Swartz27 uuuu...
Google Transtale: what's happening Swartz27? I do not understand why you behave podbroney please explain what I'm doing wrong?
