### ISSUE TITLE
Decouple and update TinyXML

### ISSUE THREAD

**Issue by Xottab-DUTY** [OpenXRay/xray-16#143]
We need to decouple TinyXML and update it to TinyXML-2.
It's API almost similar to TinyXML-1, but it's implementation completely re-written to make it more appropriate for use in games. It uses less memory (about 40% of TinyXML-1), uses far fewer memory allocations (1/10th to 1/100th), and faster.
- [ ] Decouple TinyXML
- [ ] Update TinyXML
- [ ] Update to TinyXML2 (Current we can't do this because of https://github.com/leethomason/tinyxml2/issues/729)

**Comment by ghost** [comment]
I'll assign this task to myself, I need to start helping with this repo.

**Comment by andrew-boyarshin** [comment]
@Swartz27 whooops... Accidentally unassigned you (you know, GitHub issue buttons, group selection, this kind of stuff). Feel free to reassign yourself if you are still on this issue.

**Comment by Xottab-DUTY** [comment]
New TinyXML2 and pugixml we were used in incompatible with original game XML files.
