### ISSUE TITLE
Overhauled weapon attachment system

### ISSUE THREAD

**Issue by Comanche93** [OpenXRay/xray-16#144]
Hey folks!
I was wondering if its possible to implement different weapon attachment system here on x-ray, e.g. like in ArmA III, where you can install various attachments on your gun, even from another mod or made by other person...
At this moment, to have, for example, scope on your rifle, you have to include it in weapon 3d-model so possibilities to tune a gun are limited . But with new WAS you just make some attach nodes on 3d-model where it will be placed, and download separate scope, GL and other accesories...

**Comment by Xottab-DUTY** [comment]
This would be really cool, except it changes gameplay which we trying not to change. Mainly, this proposal is not for OpenXRay, but some other projects such as weapon mods, at least for now (maybe, in future, we will start implement many new gameplay features, but with ability to disable it and play with vanilla gameplay. Maybe)

Mind you, my opinion may not coincide with other people's in project.

**Comment by Charius** [comment]
I'm not a contributor of this project. But I want to set my imho. Idea is nice and very interesting and I think it should be implemented as extension, and I agree with @Xottab-DUTY

**Comment by Comanche93** [comment]
Agree with you)
But i was just talking about code support for WAS with keeping an old system.
I believe everything alse modders will do. Especially guys from Gunslinger or Shoker mods...

Added later:
Nevermind, actually SWM already has this feature...

**Comment by PavelBlend** [comment]
Если я правильно понял гугл переводчик, то этот запрос связан с новой системой аддонов.

Хотелось бы, чтобы эта функция была добавлена. Думаю, что пригодилось бы для мододелов, так как open-xray - это платформа для моддинга, а не отдельный мод.

Лично я хотел бы увидеть следующее:

- модели прицелов, глушителей, подствольных гранатомётов хранятся в отдельных файлах от оружия. А у самого оружия должны быть три кости: `wpn_gl`, `wpn_scope` и `wpn_silincer` (чтобы названия этих костей можно было указывать в конфигах). И у каждого оружия в конфигах присутствуют параметры смещения и вращения для каждого аддона. И чтобы гранатомёт убирался не за счёт анимации (путём перемещения кости гранатомёта вниз), а за счёт скрытия кости движком. В итоге оружие сможет иметь более одного вида глушителя, прицела и гранатомёта. И можно помимо этих аддонов добавить рукоятки, магазины и фонарики. Может ещё что-нибудь. Вообще можно сделать секцию `wpn_ak74_addons`, в которой будут параметры `addon_1`, `addon_2`, `addon_3` ... , которые будут представлять из себя ссылки на отдельные секции, например, `addon_1 = wpn_ak74_addon_1`. И секция `wpn_ak74_addon_1` будет хранить параметры смещения, вращения, используемые анимации и т. д.

- сделать возможность использовать Bone Parts для левой и правой руки. То есть, чтобы можно было для левой руки указать одну анимацию, а для правой руки - другую. Например, когда ГГ держит в руках АК с рукояткой, то для левой руки включается версия анимации в позиции рукоятки, а правая рука остаётся со стандартной анимацией. Или когда подсоединяется гранатомёт, то левая рука начинает использовать анимацию ak74_reload_gl, а правая остаётся на анимации ak74_reload. Можно даже сделать так:
для анимации перезарядки делать две анимации: ak74_reload_left и ak74_reload_right (для левой и правой руки). И для анимации ak74_reload_left будут анимационные ключи для левой руки, а у правой руки будут стоять нули, а в анимации ak74_reload_right сделать наоборот. Или можно вообще разделить модель рук на две модели: модель левой руки (+её анимации) и модель правой руки (+её другие анимации). Не знаю, насколько это адекватно делать. Просто сейчас приходится делать кучу анимаций (ak74_reload, ak74_reload_gl + анимации для каждого вида рукоятки, гранатомёта), а если руки разделить на две модели, то анимации будут меняться только для левой руки, а правая будет иметь меньше анимаций. В общем не знаю, может кто лучшее решение предложит.

- сделать возможность указать анимации для прикручивания глушителя (и, возможно, других аддонов), снятие оружия с предохранителя, анимации без магазина.

И все эти возможности должны быть опциональными. Например, создать класс `WEAPON`, который будет иметь эти возможности, а старые классы `WP_AK74` и т. д. будут работать по старой схеме (чтобы не утратить совместимость с оригиналом).

**Comment by mortany** [comment]
Подствольный гранатомёт итак скрывается костями, анимация ему не нужна. А вот остальное почти всё есть в шокере, только пользоваться этим пока никто не умеет.
