### ISSUE TITLE
Лицензия

### ISSUE THREAD

**Issue by ghost** [OpenXRay/xray-16#145]
Я так понимаю исходный код XRay используется со слитого архива?

Насколько вообще легитимно использовать проект?

**Comment by nitrocaster** [comment]
[README.md](https://github.com/OpenXRay/xray-16/blob/dev/README.md):

> Be advised that this project is not sanctioned by GSC Game World in any way – and they remain the copyright holders of all the original source code.

[License.txt](https://github.com/OpenXRay/xray-16/blob/dev/License.txt)

**Comment by ghost** [comment]
Так зачем на гитхабе этот проект?

**Comment by GoldRenard** [comment]
Вроде как Сергей Григорович дал неофициальное разрешение на использование исходников в некоммерческих целях.
