### ISSUE TITLE
Per-vertex to per-pixel lighting

### ISSUE THREAD

**Issue by ghost** [OpenXRay/xray-16#15]
Per-vertex lighting I believe causes a good deal of problems in XRay. A good example is light bleed through walls and ceilings. Another is easy to see on weapon models, where both sides get lit up at once, or how at certain angles it only lights small parts of the model and not others.

Concerns: performance cost

Thoughts?

P.S. Yes I will commit the actor shadows nitro, I just have been quite busy and I'm still trying to figure out how to use Git Shell.

**Comment by nitrocaster** [comment]
What makes you think X-Ray uses per-vertex lighting?

**Comment by ghost** [comment]
From XrEngine folder, "Effects Description.txt":
- Colored dynamic, per vertex lighting
  - Intelligent light sources selection & clipping
    - Makes possible more than 100 dynamic lights per frame at reasonable FPS-es

Plus it's obvious if you notice the light bleed in certain places, or on the Svadosk the way lighting looks funky on some doors, etc.

**Comment by nitrocaster** [comment]
X-Ray used vertex lighting in early 2000. I'm pretty sure there's no per-vertex lighting in vanilla releases.
Light bleeding doesn't have to be caused only by per-vertex lighting, there're may be another factors.
Maybe you could post a screenshot to show what you exactly mean?

**Comment by ghost** [comment]
Whoops, could have sworn it used per-vertex due to some light anomalies I've seen. I'll post some screens of what I mean later.
