### ISSUE TITLE
dev branch broken

### ISSUE THREAD

**Issue by alexgdi** [OpenXRay/xray-16#158]
Hello all! Compile on VS 2017 RC i have an error:
 
Russian:
Серьезность	Код	Описание	Проект	Файл	Строка	Suppression State
Ошибка	C2244	luabind::functor<void,int...>::operator (): не удается сопоставить определение функции существующему объявлению	xrScriptEngine	E:\git\xray-16\src\xrScriptEngine\Functor.hpp	27	

Google Translate:

Severity Code Description Project File Line Suppression State
Error C2244 luabind :: functor <void, int ...> :: operator (): unable to match function definition to the existing ad xrScriptEngine E: \ git \ xray-16 \ src \ xrScriptEngine \ Functor.hpp 27

something with luabind was broken. 🌵

**Comment by CrossVR** [comment]
This sound like something I fixed in commit 570f74e8390c313970c4a23bedcfaec6d87b442f

Or perhaps I broke it in that commit. Which git commit are you on?

**Comment by alexgdi** [comment]
Armada651, oh sorry. my repo was not update. thx for reply and waste time.
