### ISSUE TITLE
Linker errors with Luabind

### ISSUE THREAD

**Issue by tomi-kr** [OpenXRay/xray-16#159]
As the title says, linker output has been attached. Any help would be appreciated.

[linker_errors.txt](https://github.com/OpenXRay/xray-16/files/727954/linker_errors.txt)

**Comment by alexgdi** [comment]
tom9099, Did you build luajit?

**Comment by CrossVR** [comment]
Project dependencies are not well defined yet, try building the luabind project individually first.

**Comment by andrew-boyarshin** [comment]
#160 is to resolve this issue when merged.
