### ISSUE TITLE
Missed source files

### ISSUE THREAD

**Issue by muradovm** [OpenXRay/xray-16#163]
Hi everyone!

I followed by steps described in "how to build" but encountered a problem with source files. Looks like "fastmath.h" and "utime.h" are missed. My VS cannot find them. Where can I get them?

Thank you

**Comment by Xottab-DUTY** [comment]
I think you are trying to build editors. There are broken and cannot be compiled.
For now, the solution cannot just be builded with click on "Build solution". You need to manually build every project, except editors. Armada is working on that downside in #160

**Comment by revolucas** [comment]
I think you can just click build on xrGame project and it will build pretty much everything you need. Build only these:

> crypto
> CxImage
> DXT
> luabind
> luajit-2
> NVTT
> ode
> OpenAL
> xrAPI
> xrCDB
> xrCore
> xrCPU_Pipe
> xrD3D9-Null
> xrEngine
> xrGame
> xrNetServer
> xrParticles
> xrPhysics
> xrRender_R1
> xrRender_R2
> xrRender_R3
> xrRender_R4
> xrSound
> xrXMLParser

**Comment by muradovm** [comment]
Oh, thank you.
