### ISSUE TITLE
Current OpenXRay/dev is seriously broken

### ISSUE THREAD

**Issue by ShokerStlk** [OpenXRay/xray-16#164]
Once again - sry for my bad english. 
First - I'm not very good with Git yet.
Second - I'm not very good in VS workflow\settings, programming is more like hobby for me.
So sry again.
- - - - - - - - - - - - - - - - - - - - - - - -
I'm relatively "new" for OpenXRay (migrated to it from vanila VS2008 sources), and i found a lot of serious problems in this project, that doesn't allow me to work with it normaly.

Here is a short list of what i remember: (For /dev branch)
1)  Incomplete build instruction (**Armada651** currently work around this), "compiled binaries" from xray-16-libraries.zip (lib-files) for Ogg\Theora compiled with VS2013 and doesn't work in VS2015 (it easy to recompile them, but anyway ...) 
2) master branch is outdated for 2 years. There also no hint about what fixes exist in dev, and doesn't exist in master. (i can use commit history but again it's not user-friendly). 
3) Mixed (aka Debug) build configuration not setup properly. Generated .lib-files scattered around different folders and can't be linked without manual work. xrGame in Mixed mode require CXImage.lib which doesn't exist. (but i get it worked with **renamed** CXImage_static.lib)
It also look's like in-game xrWeatherEditor now can't be compiled (?) unlike in older OpenXRay or vanila.
4) I'm also still don't understand difference beetween Mixed\Debug configurations, but this "problem" goes from vanila engine, since Debug in vanila can't be compiled without tons of errors, unlike Mixed.
5) ac222fe "When running the game in windowed mode, game window appears at the center of screen by default" - for god sake this change should be reverted back to vanila. A lot of mod-developers work in windowed mode cuz they whant to have some **free space** on screen. (and also for fast alt+tab)
For players we should implement proper borderless-mode in future.
6) 28261db, 0e56552 "Desktop cursor is confined by game window client space when game cursor is hidden" - this feature is also broken. Seems like nobody test it enough before pushing. ._.
--> 6.1) Right-Down window limits are not-exist (cursor can go below window) - there is a typo-or-smth in code. 
--> 6.2) Since cursor is locked by OS now, it can be **stick** in "hiden window" limits sometimes, even is xrEngine.exe **already** terminated, or when game is hang\loading while alt+tab.
--> I already partially-fixed some for myself, but it's still work not very good while game process are hanging, so i think this change should be reveted \ reworked.
7) https://github.com/avoitishin/xray-16/wiki/List-of-Changes - as far as i know: Call of Chernobyl engine is forked from it. This fork have some **crucial** features, like ECO Render or Spawn Antifreeze, which (surprising for me) not exist in this repo.
It also have proper Wiki - why this changes not in main OpenXRay? (probably cuz **avoitishin** didn't push them into main for some reason)
8) **MAIN PROBLEM** - Lua is broken. Maybe it's my fault, and i build-it in a wrong way? _(As far as i know there should be two version of LuaJit, **but i don't know how to change them**)_
It cause crashes in code, **which work in vanila engine**. It also dosen't generate proper log. 
Here is simple example of crash. (there many of them)

<details><summary>[Spoiler]</summary><p>

Example of vanila log:

```
Expression    : fatal error
Function      : CScriptEngine::lua_error
File          : E:\stalker\patch_1_0004\xr_3da\xrGame\script_engine.cpp
Line          : 73
Description   : <no expression>
Arguments     : LUA error: ...hadow of chernobyl\gamedata\scripts\xr_danger.script:116: attempt to index field 'ignore_types' (a nil value)
```

s_name - string
i - number
self:AddItemToList(s_name, i) <-- line 311

1) What i see in current Release build while crash:
```
FATAL ERROR
 
[error] Expression    : !m_error_code
[error] Function      : raii_guard::~raii_guard
[error] File          : script_engine.cpp
[error] Line          : 531
[error] Description   : see call_stack for details!

```
2) What i see after changing [break_on_assert](https://github.com/OpenXRay/xray-16/issues/147#issuecomment-250605820) to false

```
! SCRIPT ERROR: see call_stack for details!
 
FATAL ERROR
 
[error] Expression    : <no expression>
[error] Function      : CScriptEngine::lua_error
[error] File          : script_engine.cpp
[error] Line          : 749
[error] Description   : fatal error
[error] Arguments     : LUA error: No matching overload found, candidates:
CUITextWnd* AddTextField(CUIListBoxItem&,char const*,custom [float])
```
It even doesn't show file name \ line number in Release build! How am I supposed to fix lua-errors with it?

3) What i see in Mixed (aka Debug) build:
```
* Loading script: god_tbl.script
! [LUA] SCRIPT RUNTIME ERROR
! [LUA]  0 : [C] [C](-1) : 
! [LUA]  1 : [C  ] AddTextField
! [LUA]  2 : [Lua] ... - call of pripyat\gamedata\scripts\ui_god_dialog.script(818) : AddItemToList
! [LUA]  3 : [Lua] ... - call of pripyat\gamedata\scripts\ui_god_dialog.script(311) : 
! [LUA] No matching overload found, candidates:
CUITextWnd* AddTextField(CUIListBoxItem&,char const*,custom [float])
! SCRIPT ERROR: see call_stack for details!
! [LUA] SCRIPT RUNTIME ERROR
! SCRIPT ERROR: see call_stack for details!
```
4) It also more case-sensitive compared to vanilla Lua: **F**alse instead of false will crash the game. (I know it's bad code, but this example from vanila game)

</p></details>

Once again - why such big changes doesn't tested enough before pushing. =\

I know that everybody work for free, fully on enthusiasm. But if we want a new people to work with, then we should to fix what already we have. Currently there is no way to use it in any project

I will try to fix what i can, but i'm not very good in complicated code such Luabind\LuaJit.

PS: GitHub 2017... why i should to google  about how to hide long text in spoiler.

**Comment by alexgdi** [comment]
luajit compile separetly with msvcbuild_all.bat

**Comment by andrew-boyarshin** [comment]
Spawn antifreeze was introduced several times in @revolucas fork (which is in turn, as far as I can remember originally fork of @avoitishin fork). It caused issues (you can check it from his commit history) and turned out to be non-profitable, as it did not solve the main problem (freezes on large NPCs quantities spawn), yet introduced crashes and bugs.

**Comment by CrossVR** [comment]
I agree with most points, feel free to submit PRs. We've been having problems getting this project on the road because of a lack of developers. So a lot of changes were made without proper review or discussion.

**Comment by revolucas** [comment]
I thought Armada added luajit2 project, it seems to work for me. 

Although Call of Chernobyl has been unforked from Open Xray for quite some time now I can confirm that LuaJIT2 works perfectly fine and have been using it in CoC for over 2 years. The problem is more likely you had errors in your lua code to begin with, that the original luaJIT 1 was unable to detect. I use AddTextField several places in my own code just fine. There is a lot of bad and poorly written lua code in Call of Pripyat. If you turn on lua logging and play vanilla game you will see nothing but red text in console [LUA] errors.

**Comment by ShokerStlk** [comment]
As i understand, CoC use official LuaJIT - http://luajit.org/git/luajit-2.0.git
While OpenXRay use forked repo - https://github.com/OpenXRay/LuaJIT.git 
with no (?) updates. Or  git submodule update suppose to refresh it? (i rly don't know how it work)

Btw i think problem in new LuaBind, which is heavily-modded for XRay https://github.com/OpenXRay/luabind-deboostified.git
CoC use original one.

**Comment by revolucas** [comment]
Ah, luabind could be why.

**Comment by jakebriggs** [comment]
I really want to play around and see if I can't work out why xray crashes when invoking the steam overlay but getting it compiles was a major challenge and I can't get in game to debug it.

I can however get to the title screen so I guess I could still do some debugging, but it doesn't feel worth it if the payoff is not being able to play anyway.

**Comment by jakebriggs** [comment]
Turns out steam overlay is broken when running from native Linux steam and wine stalker. I am running an optimus laptop, I'll try it without running it on the nvidia GPU, but it seems like this is my problem :)

**Comment by ghost** [comment]
I have to agree here. Nitro is nowhere to be seen, and I haven't done anything because all I did was fork the code as soon as it came out, then Nitro forked it and made me an admin. I can't really help as I'm not much of a programmer, which is why I'm going to remove myself from Open Xray, which I should anyway, as I have no interest in contributing to the useless and broken code here even if I could help.

**Comment by CrossVR** [comment]
@Swartz27 The project is indeed a bit of a mess right now, I'm going to try and fix that. But that does mean we'll be dealing with boring stuff like fixing broken code for a while.

I removed you from the organization as you wanted, feel free to return when things are stable again.

**Comment by jakebriggs** [comment]
Apart from the bugs in the issues section, what other stuff is broken? I am keen to help but I don't 100% know where to start.

I have it compiling and getting in game, and even made a couple of tweaks on my codebase for funsies - I removed the intro movies and splash screen, because splash screens are so last week and it seemed like a simple goal.

**Comment by Xottab-DUTY** [comment]
@jakebriggs as many times said i can say it again: the editors are broken and no one wan't to mess with them, because they are for Borland compiler, not for Visual Studio. Feel free to mess this mess if you want ;)

**Comment by jakebriggs** [comment]
That doesn't sound fun :P

**Comment by Xottab-DUTY** [comment]
You can observe other forks and correctly merge useful changes from them.

**Comment by ShokerStlk** [comment]
As I found out - the main problem of new LuaBind \ xrScriptEngine is missing ability to auto cast variable types. (**implicit type conversion**)

For example, we have a engine function, ported to Lua:
CUITextWnd* AddTextField(LPCSTR txt, float width);
Fist argument is string, second is float.

BOTH examples of this [shit-] code will work in original CoP Lua scripts:
_itm:AddTextField( "123",  1.0)   -- string, float
_itm:AddTextField(  123,    1.0)   -- number, float

Since first argument - number - would be automaticly converted to string.
Even nil would be converted to "" (empty string)

But in current Lua second example will crash:
"No matching overload found, candidates: CUITextWnd* AddTextField(CUIListBoxItem&,char const*,custom [float]) "

So it's PROBABLY not fully broken, but we lost some backward comparability with original game\mods.

I dont have enough skill to fix this by myself.
So i think to revert back to master branch (2015, with old Lua) and port to it all crucial changes from dev / CoC / avoitishin repositories.

**Comment by Xottab-DUTY** [comment]
I think reverting to old Lua isn't good idea, but it is an solution for this problem. But, a lot of work was done and a lot of time for it spended, so i think we should try to add ability to auto cast types. I think @nitrocaster can do this, but it is unlikely he will want to do this work.

**Comment by CrossVR** [comment]
@jakebriggs The two big goals we have is to port the engine to Linux and to port all previous games (ShoC and CS) to the latest version of the engine.

Which effort would you be interested in helping with?

**Comment by jakebriggs** [comment]
The Linux port I think, since that could be divided up into bits. As Xottab-DUTY pointed out above, merging other forks useful changes into this one would be valuable, and any changes that involves porting to SDL would help with the Linux port, so maybe I'll start by looking for these forks :)

**Comment by ShokerStlk** [comment]
@Armada651, do you have ability to accept pull requests in OpenXRay/luabind-deboostified too? I have some changes to it (does not pushed yet), but looks like @nitrocaster  is currently offline for long.

Btw, looks like i found a way to fix current lua problems.  I will push it all when it be ready. Currently it's not broken (unlike i said before), just not setup properly for XRay.

**Comment by CrossVR** [comment]
@ShokerStlk I can merge pull requests, but you haven't submitted anything and I do need to code review everything before I will merge it.

**Comment by ShokerStlk** [comment]
Just funny thing - it seems that old luabind from original XRay 1.6.02 just mute any errors, and not crash the game. This leads to undefined behavior in original game and hiding a lot of errors.
For example: vector():set(vector2(), vector2(), vector2()) 
This code will not crash the vanilla game, but silently will break current code execution.

**Comment by JacobBriggsAckama** [comment]
I had a really good play with https://github.com/vincent-t/xray-16/ copying over a bunch of the SDL related defines and ifdefs into @Armada651 branch (easier compiling) and managed to get it compiling and even running if SDL is turned off.... 

Anyway I am out of action for a week or so but I'd like to contribute properly, at least by identifying where SDL would need to be incorporated and hopefully get the engine running with SDL popping up the window instead of using the windows libs. Hopefully the work that @Armada651 did on cleaning the compile up will make it into this repos by then, so I can do it for reals.

**Comment by Xottab-DUTY** [comment]
@jakerabid It would be great if you coordinate your work with @vincent-t

**Comment by jakebriggs** [comment]
Oops I posted with my work account rather than my personal account lol

**Comment by jakebriggs** [comment]
@Xottab-DUTY yeah that's a great idea if @vincent-t is keen :) I think it was a good exercise in learning how the engine is put together.

**Comment by 0xBADEAFFE** [comment]
@jakebriggs How can I help you? :)

**Comment by jakebriggs** [comment]
@vincent-t probably a brief description of where you think your SDL conversion is at - should, for example, the menu of the game show up in the SDL created window?

Unfortunately I am moving house - my dev machine is going to be stored away, so I may not be able to do anything on this for the next 3 or 4 weeks. But, I am storing it at work, so I might be able to work on it after all depending on how things work out!

**Comment by Xottab-DUTY** [comment]
Issue with luabind crashing the engine on a wrong script was fixed. Now it will crash only if error callback wasn't set. Here's the commit: https://github.com/Xottab-DUTY/luabind-deboostified/commit/ee8a074be60ab849b2f4c7bba79b8c6001bf74c3.
@ShokerStlk This might be interesting for you.

**Comment by Yaksinikos** [comment]
Alt+tab does not work for linux / cinnamon at all, as well as fast-changing the workspace. :disappointed:

**Comment by Xottab-DUTY** [comment]
Outdated. Most of the issues are fixed in the current `xd_dev` branch which will be merged into `dev`. There are still some issues left though. You can find them here: https://github.com/OpenXRay/luabind-deboostified/issues
