### ISSUE TITLE
Is this still running ?

### ISSUE THREAD

**Issue by ChristopherCapito** [OpenXRay/xray-16#17]
Hi. Is this still running? Do you actually have the source code for the whole engine? For free use?

**Comment by nitrocaster** [comment]
I'm not sure what do you mean by 'still running'. Is there any work underway? Yes it is. This repository contains almost complete source (except some tools, e.g. dialog editor and lua IDE). Licence is available [here](https://github.com/OpenXRay/xray-16/blob/master/License.txt).

**Comment by ChristopherCapito** [comment]
Exactly what I was getting at. There was talks that this is dead, that s why I asked. Thank you.
