### ISSUE TITLE
Visual Studio 2017

### ISSUE THREAD

**Issue by andrew-boyarshin** [OpenXRay/xray-16#174]
Now that VS2017 is released, it might be worth migrating to the latest version.

Benefits:
- Latest C++ compiler
- Latest IDE means improved development UX (noone really likes laggy VS)
- Fixed C++ bugs and improved standard conformance (might improve #148 situation and improve portability)

Disadvantages:
- Requires migration of all submodules, probably wait for #160 to arrive?

## Russian (Русский)
Наконец-то вышла VS2017. Необходимо рассмотреть возможность перехода на новую версию.

Аргументы **за**:
- Обновление C++ компилятора
- Обновление среды VS, удобнее работать с кодом и VS стала быстрее работать
- Исправление ошибок реализации стандарта C++ (может упростить нахождение ошибок, связанных с #148)

Аргументы **против**:
- Требуется также миграция всех подмодулей и библиотек, возможно, стоит подождать #160?

**Comment by CrossVR** [comment]
Yeah we should upgrade, but we should indeed wait until #160 is merged.

**Comment by alexgdi** [comment]
+1

**Comment by CrossVR** [comment]
If anyone wants to help out though, I completed PR #160 so it's just awaiting review. If you'd like you could help us by reviewing and testing it.

**Comment by Xottab-DUTY** [comment]
Another benefit is that now we don't need to create VS project files if some submodule uses CMake, because of VS support it directly

**Comment by andrew-boyarshin** [comment]
@Xottab-DUTY as far as I am concerned, PR created by @Armada651 did not migrate to CMake. It was designed to unify build system under git submodules and VS project files instead of downloading some ZIP archives or running LuaJIT's ```msvcbuild.bat``` by hand.

**Comment by Xottab-DUTY** [comment]
@andrew-boyarshin Yes, it is. I mentioned this, because we may have some 3rd party library in future that uses CMake and we likely won't need to create vsproj and just use CMakeLists from that submodule.

P.S. By the way, Luabind and lzo have CMakeLists :)

**Comment by CrossVR** [comment]
VS2017 supports CMake? That's great!

**Comment by Xottab-DUTY** [comment]
Some links that may be useful:
https://blogs.msdn.microsoft.com/vcblog/2016/10/05/cmake-support-in-visual-studio/
https://www.visualstudio.com/en-us/docs/build/steps/build/cmake

**Comment by Xottab-DUTY** [comment]
Oops, just checked how it works. Sadly, but we can't add CMake-driven project as project in VS solution. We only can open it as solution. But anyway it's useful)

**Comment by CrossVR** [comment]
Still, it's interesting for when we switch to CMake for a cross-platform port. We could decide that we'll wait with VS2017 support until we switch to CMake.

**Comment by Xottab-DUTY** [comment]
I think we should migrate to VS 2017 because of mentioned benefits)

**Comment by CrossVR** [comment]
Sure, but the question is whether we'll migrate the VS2015 solution or just wait until we migrate to CMake and we'll just support VS2017 in that build system.

**Comment by Xottab-DUTY** [comment]
Ah, this is what you mean) Then I mean that, in my humble opinion, we should migrate VS 2015 solution.

**Comment by CrossVR** [comment]
Why? We're going to have to set up CMake anyway, why would we still want to deal with both CMakeLists and solution files in this project?

**Comment by Xottab-DUTY** [comment]
After CMakeLists come we can drop solution files, but for now I don't know when we will support CMake and wan't to use VS2017 now))

**Comment by andrew-boyarshin** [comment]
I consider migrating to VS2017 to be easier after merging #160, so it should be done first. CMake is harder to introduce, so it should be done later.

**Comment by andrew-boyarshin** [comment]
And anyway, discussion of migration to build tools like CMake should be done in #21.

**Comment by CrossVR** [comment]
After some more research I agree, the CMake support in VS2017 is not yet close to the level of support for solution files. Notably absent features are the Error List and the Graphics Debugger.

**Comment by andrew-boyarshin** [comment]
Trying out #160 with VS2017 (Win10 14393 SDK only). Keypoints so far:

- std::_Construct, std::_Destroy Microsoftism removed from standard library.
- d3dx9.h missing (DX SDK needed, looking for workaround).

**Comment by Xottab-DUTY** [comment]
@andrew-boyarshin we have test branch without DX SDK, You should look at it)

**Comment by andrew-boyarshin** [comment]
@Xottab-DUTY I didn't like the solution on that branch, plus it is WIP. Looks like I've found the solution, will post details later. I can now successfully build almost everything on Win10 with only VS2017 and 14393 SDK installed.

**Comment by andrew-boyarshin** [comment]
Crossreference: #101 (Windows SDK DirectX)

**Comment by Xottab-DUTY** [comment]
Also, we shouln't use Win10 SDK, because not everyone have Win10 installed).
So, your fix needs check if it is working without Win10 SDK on, say, Win7 SDK =)

**Comment by andrew-boyarshin** [comment]
@Xottab-DUTY I used Win10 SDK because it doesn't have deprecated modules, like D3DX, and it is has leaner architecture. There will be no dependency on Win10.

UPD: Windows 7 SDK is deprecated. For development on Windows 7 you should use Windows 8.1 SDK (latest and last supported).

**Comment by Xottab-DUTY** [comment]
@andrew-boyarshin Ok, got you)

**Comment by andrew-boyarshin** [comment]
Pure build successful. Thanks, @Armada651 for your work on build system improvements (even though I had to modify it to get rid of DX SDK and to port to VS2017).

UPD: Working stable, completed a couple of first quests. After merging #160 I can send the PR to get rid of DX SDK dependency and upgrade to VS2017.

**Comment by andrew-boyarshin** [comment]
Warning: Visual Studio 2017 15.3 contains new compiler set with bug, preventing compilation of xrAICore.
[Reported bug](https://developercommunity.visualstudio.com/content/problem/95252/c2903-with-msvc-141125503-implementing-crtp.html). Will be fixed in 15.5. Do not update your VS installation.

**Comment by Xottab-DUTY** [comment]
Installed new 15.5 Preview. This bug is fixed, but there's other problems. But they can be fixed.

**Comment by Xottab-DUTY** [comment]
Current default branch is on VS 2017 already.
