### ISSUE TITLE
Get xrWeatherEditor working in Release configuration

### ISSUE THREAD

**Issue by Xottab-DUTY** [OpenXRay/xray-16#178]
For now editor wont work in Release, but it's nice to have it working with Release configuration.

_Maybe that strikedthrough stack trace below will help.._
~~Stack trace says that it can't find a file. The question is: what file?
https://gist.github.com/Xottab-DUTY/d749a56a5cc6b66f329ecb353e0e0de5~~

~~Also, compilation is broken after sources reformat. I'll push a PR with fix. Pushed #179
But we still need to find out why it won't work.~~

**Comment by Xottab-DUTY** [comment]
~~Addition: this stack trace is for Release configuration with INGAME_EDITOR defined. It seems xrWeatherEditor don't like Release.
But it's anyway broken – it crashes in Debug too.
However, I have more appopriate crash detected by BugTrap. It's place to start finding the problem. [link was here](#) I got this crash because of I have Atmosfear 3 and Absolute Nature 4 installed.~~

**Comment by Xottab-DUTY** [comment]
I'm dunderhead :D Sorry guys! It's working in Debug configuration.

But there's still some issues (or I can't understand how it is working): I can't apply any number in the editor. ([see this image](https://yadi.sk/i/F3bxPzrx3GVaAx))

**Comment by Xottab-DUTY** [comment]
Also, it makes sense to have working xrWeatherEditor in Release configuration.

**Comment by abramcumner** [comment]
> But there's still some issues (or I can't understand how it is working): I can't apply any number in the editor. (see this image)

By default, the delimiter in the Russian locale is a comma, not a period. Try to enter number with comma.

**Comment by Xottab-DUTY** [comment]
@abramcumner thank you, that works!
