### ISSUE TITLE
Progress?

### ISSUE THREAD

**Issue by BeaconDev** [OpenXRay/xray-16#18]
Is this dead guys? It would be really sad if so. Alundaio has successfully made changes to the source including grass and actor shadow, and FoV command in console.

**Comment by nitrocaster** [comment]
Not really. I'm currently busy with my personal stuff, gonna proceed with xray later.

**Comment by awdavies** [comment]
I've mostly dropped contributing due to time constrains (I'm working on another project right now, plus I've got work on top of that).  But other than that, I think it's just hit a little bit of a slow period.

**Comment by andrew-boyarshin** [comment]
Slowly working on Luabind and LuaJIT update. Rebased on latest master branch.

**Comment by andrew-boyarshin** [comment]
If somebody is still interested in it, I've made:
1. Rewritten cpuid to be asm-independent. (not copy-pasted SoC commit, as in CoP there are some new things which cpuid.cpp has to retrieve, such as affinity mask and stuff like this).
2. Implemented detection of Wine.
3. Rewritten some Blackbox code.
4. Rewritten everything, related to stacktrace. Now there is no more awful mix of asm and c++ from 2003 which was working correctly in 20% of cases.
5. Applied some optimizations and crash fixes to engine.
However, I used @avoitishin fork, not exactly this repo, so I can't contribute directly.

**Comment by nitrocaster** [comment]
Regarding debugging subsystem and cpu detection - I've already rewritten that in [xray](https://github.com/OpenXRay/xray) (there's no blackbox stuff there anymore) but haven't apply on xray-16 yet.
Another thing is that I don't see any forks of xray-16 in your profile - where are the changes you made?

**Comment by inelisoni** [comment]
I'm interested) but I can't commit

Îòïðàâëåíî ñ iPhone

**Comment by nitrocaster** [comment]
You can commit to your fork.

**Comment by TheLonerD** [comment]
Any progress guys? And what branch is up to date, I suppose **editors_vs**?

**Comment by nitrocaster** [comment]
I'm currently busy with my own stuff, xray is on hold. editors_vs was created for porting borland-dependent editor tools to vc++/c++cli/c# so one could easily build the engine with all included tools.
If you don't want to deal with editors, use master branch.
