### ISSUE TITLE
Fix Bug. Crash in net game.

### ISSUE THREAD

**Issue by electrobas94** [OpenXRay/xray-16#184]
Game crashed when actor died.
Fix, in file
XrGame/Entity.cpp
line 256 replace if (this->ID() == Actor()->ID()) on  if (GameID() == eGameIDSingle && this->ID() == Actor()->ID()).

**Comment by CrossVR** [comment]
Could you submit this as a Pull Request? You can just use the Github webeditor if you don't have a git copy of the code repo:

https://github.com/OpenXRay/xray-16/edit/dev/src/xrGame/Entity.cpp

**Comment by MrCK1** [comment]
Not sure if this applies to single player, as the game also crashes there when an NPC is killed. However, I fixed the issue by modifying the LUA script instead.

**Comment by Xottab-DUTY** [comment]
@MrCK1 can you please provide info how you did fix this via Lua script? With this we can decide what is more optimal: cpp or lua.

**Comment by MrCK1** [comment]
Sorry for the late reply. I had to reformat my PC recently, so I'll see if I still have the file or not. I'll take a look at the proposed fix on the .CPP file to see if it functions the same as mine does.

**Comment by MrCK1** [comment]
Forgot to reply here. This only affects MP and the code works fine. Single Player doesn't crash for me after killing NPCs, whatever I did with my old build was screwing with the engine.

Side note: I can't wait until we reduce dependencies/decouple everything between all the engine modules, certainly makes it difficult to to track bugs in the callstack currently.

**Comment by Xottab-DUTY** [comment]
Fixed with 885ac4e1c61240a699f7a3384ac2ce430b0538bf

Thanks @electrobas94
