### ISSUE TITLE
This Game Engine requires a compiler or has its own compiler for scripts?

### ISSUE THREAD

**Issue by arifoxs** [OpenXRay/xray-16#186]
Hi, 
I am a bit confused code in this project, but I understand little bit also the flow of the code,
I want to ask something, if this Game Engine can run,

I want to make a game with this game Engine, I want to add a script with c ++ or something else, of course this game engine needs compiler right? Is it true? If this game engine is very dependent on the compiler like visual c + +, of course visual c ++ should be installed,

Or this gaming engine has its own script compiler, like Unity? Thank you

**Comment by Xottab-DUTY** [comment]
You can write scripts via Lua, no compiler is needed. Writing C++ scripts is actually hardcoding into the engine.

The engine itself must be compiled via Visual Studio 2015.

You really need to try to create mods for S.T.A.L.K.E.R.: Call of Pripyat before creating a game.

You should also know, that you can't make any commercial with this engine. Only noncommercial free projects.

**Comment by arifoxs** [comment]
Not commercial, okay no problem, I'm from Muria Kudus University, Indonesia, if this game engine can be used, I will share, and many students will use it to make games, of course to learn to make games, and not commercial

I read this project to learn, and add to my knowledge of C ++, because it is also developing my own Native GUI library, based on winapi32,

thank you

**Comment by MrCK1** [comment]
In its current state, X-Ray is still a mess of an engine with tons of legacy code and stuff written for compilers that no longer exist. 

Everything is done by trial and error, there's no documentation whatsoever. You'd have a much easier time developing using something that's heavily documented like Unity, Source or Unreal.

**Comment by samrocketman** [comment]
Yes, considering GSC Game World hasn't officially approved the source release of this Engine (it was leaked and GPL unofficially applied).  You're better off sticking to a game engine without any legal grey area for developing your game and instructing students.
