### ISSUE TITLE
Vulkan API or Nvidia PhysX SDK in Xray

### ISSUE THREAD

**Issue by ghost** [OpenXRay/xray-16#190]
Stalker COP uses DX9 and DX11 renders.
Have you ever wondered if the stalker would support Vulkan API and Nvidia PhysX, or DirectX 12.
https://www.lunarg.com/vulkan-sdk/
https://developer.nvidia.com/physx-sdk

**Comment by MrCK1** [comment]
The idea is to get the engine ported to Linux in the late future. I don't think using proprietary libraries is a good idea, if anything we're still trying to remove dependencies, ect.

**Comment by Chidorin** [comment]
just a hint: dxvk + moltenvk
