### ISSUE TITLE
Should Github's Projects feature be considered for usage?

### ISSUE THREAD

**Issue by SC1040-TS2** [OpenXRay/xray-16#191]
Having read about Github's implementation of their Projects system—A card system in which one can schedule tasks for completion with the aim to streamline development, similar to Trello—I was wondering if such a system could be reasonably adopted for this project.

The one flaw or caveat I'm seeing with the system in respect to this project is that, after doing some research, I had found its method of scheduling to function with a somewhat centralized structure, in the sense that the project head or whoever has access to Project assignments is the only one assigning tasks with a deadline to meet, with the rest of the developers or whoever volunteers to commit to a given project being semi-bound to it, effectively forcing a sped-up development cycle which may end up harming the project as a whole in the long run.
With this in mind, this method of working may not be work with the current state of OpenXRay, a project with a largely decentralized development team with no potential need or want to force sudden deadlines upon itself in the name of speeding up the project's time to reach milestones, and impose a commitment beyond what each developer has already committed themselves to on top of that, creating unwanted stress and tension.

With all of this being said, however, I would at least like to start a discussion on the fruitfulness of implementing the system, be it casual or fairly serious. I'll correct the wording of my earlier talk eventually, as it is very much a 'use big words to seem knowledgeable while not getting around to the point quickly enough' kind of description in my opinion, which tends not to be helpful in practice.

**Comment by ForserX** [comment]
One problem: the project is not being developed. There are a couple of independent forks. But that's all.

**Comment by SC1040-TS2** [comment]
You're right. That's the one I forgot to include or mention explicitly here: The sheer lack of development apart from forks, and other projects which have stagnated as well.

If anything, that's the ultimate reason why Github's Projects feature would not work for this, in at least some respect. However, I'd still like to hear others' point of view on this before updating the issue accordingly, or otherwise closing it if appropriate.

**Comment by ForserX** [comment]
https://github.com/ForserX/xray-oxygen/projects/1
Made for the demonstration.

Proc of this little. IMHO.

**Comment by SC1040-TS2** [comment]
Sorry, but the link returned a custom Github 404 error message. Could you send it again?

**Comment by ForserX** [comment]
@ SC1040-TS2, Sorry. I disable it. The superfluous anyway.

**Comment by SC1040-TS2** [comment]
That's understandable, @ForserX.

**Comment by Xottab-DUTY** [comment]
Github Projects is nice to use, they definitely should be used at least for clarity.
You can see the example [here](projects/2).

**Comment by Xottab-DUTY** [comment]
Github Projects will be and already used.
