### ISSUE TITLE
Consider usage of google's cpu_features library for CPU features detection

### ISSUE THREAD

**Issue by Kaffeine** [OpenXRay/xray-16#192]
https://github.com/google/cpu_features
See the project readme for API details.

Our current implementation in asm: [xrCore/cpuid.cpp](/OpenXRay/xray-16/blob/dev/src/xrCore/cpuid.cpp)

**Comment by ForserX** [comment]
Portability... C-Style...

**Comment by Kaffeine** [comment]
Do you want to use C++ just because you can? Do you also complain about other C libraries, like OpenSSL?

The C library is more portable, than ASM.

```cpp
#include "cpuinfo_x86.h"
static const X86Features features = GetX86Info().features;

void Compute(void) {
  if(features.aes && features.sse4_2) {
    // Run optimized code.
  } else {
    // Run standard code.
  }
}
```

```cpp
#include "cpuinfo_x86.h"

static const X86Info info = GetX86Info();
static const X86Microarchitecture uarch = GetX86Microarchitecture(&info);
static const bool has_fast_avx = info.features.avx && uarch != INTEL_SNB;
```

**Comment by Xottab-DUTY** [comment]
Can you comment already ported to C++ code?
[First](https://github.com/Im-dex/xray-162/blob/master/code/engine/xrCore/cpuid.cpp)
[Second](https://github.com/xrOxygen/xray-oxygen/blob/master/code/engine.vc2008/xrCore/cpuid.cpp)
[Third](https://github.com/0xBADEAFFE/xray-16/blob/linux/src/xrCore/cpuid.cpp)

And I see x86, what about x64?

**Comment by Kaffeine** [comment]
All the three implementations are almost identical and the last one (by vincent-t) seems to be already ported to Linux, but what is about Mac? Does it also make any sense to look for ARM support (the implementations are not compatible with others (not x86) platforms AFAIU)?

In this context x64 is 64 bit x86. In the cpu_features CI ([Travis CI](https://travis-ci.org/google/cpu_features) and [AppVeyor](https://ci.appveyor.com/project/gchatelet/cpu-features/branch/master)) everything is built for 64 bit, so the question is "what is about 32 bit targets"? The answer is "the library supports 32 and 64 bits targets on x86 and ARM platforms for Windows, Mac and Linux".

I'm not insist on the library usage, but on the one side, currently we have ASM implementation for win32 and on the other side, the library is small, well-tested and it supports all reasonable platforms.

**Comment by ForserX** [comment]
@Kaffeine, I just do not like C code. Sorry.

**Comment by Xottab-DUTY** [comment]
Another alternative: https://github.com/psteinb/compass
