### ISSUE TITLE
This project is dead, but where are all the contributors? 

### ISSUE THREAD

**Issue by TarasHots** [OpenXRay/xray-16#193]
Are there any active projects currently? Link, please...

**Comment by whirm** [comment]
I see activity here: https://github.com/xrOxygen/xray-oxygen

**Comment by Xottab-DUTY** [comment]
You can see activity also in my fork: https://github.com/Xottab-DUTY/xray-16

And the project isn't dead yet and wont be. =)

**Comment by ForserX** [comment]
@whirm, my project is demanding of the system.

**Comment by samrocketman** [comment]
@ForserX is xrOxygen the new home of XRay engine?  How does it relate to openxray?

**Comment by Xottab-DUTY** [comment]
@samrocketman, nope. The only home for the X-Ray engine is the GSC Game World company.

xrOxygen is not related to OpenXRay. It's a completely different repository with it's own project structure. But we have similarities in both projects.

**Comment by MrCK1** [comment]
I'm still here, the file structure is a bit of a mess so you really need a bit of time to poke around ;)

**Comment by Xottab-DUTY** [comment]
@MrCK1, what repository you are talking about?) OpenXRay, my fork of it, or xrOxygen?

**Comment by MrCK1** [comment]
@Xottab-DUTY OpenXRay.

**Comment by Xottab-DUTY** [comment]
The project came to life
