### ISSUE TITLE
Move UI subsystem into xrUICore module

### ISSUE THREAD

**Issue by Xottab-DUTY** [OpenXRay/xray-16#196]

**Comment by ForserX** [comment]
Просто сделай её lib, собери и линкани.

**Comment by Xottab-DUTY** [comment]
Нужно сделать xrUI независимый от xrGame, в отдельной папке. Если делать dll, то так будет легче проверять независимость.

**Comment by XakepSDK** [comment]
Fixed?

**Comment by Xottab-DUTY** [comment]
@XakepSDK, thank you for reminding me.

Solved with https://github.com/OpenXRay/xray-16/commit/94acc9ac7eb3bdde02345ea1c5982b198c28ee09

**Comment by XakepSDK** [comment]
Reopen because of this
https://github.com/OpenXRay/xray-16/commit/0b24d96e206ff60739079e0998193fb3c27f7e27

**Comment by Xottab-DUTY** [comment]
Was added again with https://github.com/OpenXRay/xray-16/commit/fdc6fc50b7ce292036928ecb0137451b8048e0bb
