### ISSUE TITLE
CTD при попытке кликнуть по несовместимому файлу сохранения

### ISSUE THREAD

**Issue by LVLVbNH** [OpenXRay/xray-16#226]
FATAL ERROR
 
[error] Expression    : I != levels().end()
[error] Function      : GameGraph::CHeader::level
[error] File          : d:\users\andrei\source\repos\openxray\src\xraicore\navigation\game_graph_inline.h
[error] Line          : 113
[error] Description   : there is no specified level in the game graph : 124

Шаги для повторения:
Главное меню -> Загрузка -> Попытаться выделить сохранение.

Кейс для повторения:
[save.zip](https://github.com/OpenXRay/xray-16/files/2216905/save.zip)

По идее при любых неполадках с файлом должно появляться сообщение об ошибке с предложением удалить его (или блокироваться все кнопки кроме "удалить") , но точно не CTD.

**Comment by Xottab-DUTY** [comment]
Было дело. Надо добраться и исправить..

**Comment by Xottab-DUTY** [comment]
Пока просто убрал вылет. Потом надо будет сделать получше..
