### ISSUE TITLE
Multiplayer connection crashes

### ISSUE THREAD

**Issue by M4dMurloc** [OpenXRay/xray-16#233]
- [x] 1. net_Handler()
[XRayEngine_error_report_180821-225603.zip](https://github.com/OpenXRay/xray-16/files/2307852/XRayEngine_error_report_180821-225603.zip)
Вылетает на самой первой стадии загрузки при подключении клиента к серверу(локальному или выделенному).

- [x] 2. ip_filter::is_ip_present()
[XRayEngine_error_report_180821-234032.zip](https://github.com/OpenXRay/xray-16/files/2307977/XRayEngine_error_report_180821-234032.zip)
1)Создаем сервер(локальный или выделенный) 
2)Заходим в игру как клиент: Сетевая игра->Локальная сеть->Войти
В момент когда окно со списком серверов должно обновиться вылетает ошибка, крашится сервер.

**Comment by LVLVbNH** [comment]
@M4dMurloc , Как был создан сервер? Если батником, то можешь приаттачить?

**Comment by Xottab-DUTY** [comment]
Воспроизведение вылета №2 на ip_filter::is_ip_present()
```
- Ты создаёшь сервер.
- Игрок заходит в список серверов.
- Игрок обращается к твоему серверу и просит рассказать о себе.
- Твой сервер хочет проверить, не забанен ли игрок, о котором сообщил мастер-сервер.
- Твой сервер умирает. =(((
```

**Comment by Xottab-DUTY** [comment]
Thanks to @FreeZoneMods for fixing the second crash (PR #241)
