### ISSUE TITLE
Steam for Linux is going to support Windows-based games

### ISSUE THREAD

**Issue by TarasHots** [OpenXRay/xray-16#238]
Hi, guys, I am sure you've checked this or similar article about these news: [https://gadgets.ndtv.com/games/news/steam-for-linux-now-runs-windows-pc-games-valve-1904745](url)

Stalker: Shadow of Chernobyl is already on the list. Is porting to linux is still viable effort?

Thanks, and have a great day!

**Comment by eagleivg** [comment]
Yes, porting will continue. This is work doing in learning targets.

**Comment by TarasHots** [comment]
@eagleivg thank you) Where I can find more info about porting to linux?

**Comment by XakepSDK** [comment]
https://github.com/OpenXRay/xray-16/wiki/[EN]-Linux-progress-status
