### ISSUE TITLE
Fix bug with more load on process than it should be

### ISSUE THREAD

**Issue by ViHtarb** [OpenXRay/xray-16#24]
Plz fix a bug in xrRender/ParticleEffects.cpp in line 546 and xrParticles/particle_actions_collection.cpp in line 1779:
change from if (p_cnt < nWorkers \* 20) on if (p_cnt < nWorkers \* 64)

**Comment by Xottab-DUTY** [comment]
The original code was
```
if (p_cnt < (nWorkers * 64))
    nWorkers = 1;
```
Currently, with that fix, code looks like this:
```
if (p_cnt < (nWorkers * 20))
    nWorkers = 1;
```
I found in r8384 (leaked COP svn revision ~March 2012) this code:
```
if (p_cnt < nWorkers)
   nWorkers = p_cnt;
```
Which code is better and what does it do?

**Comment by ViHtarb** [comment]
@Xottab-DUTY
Hi. I don\`t know but on my old computer with Core 2 Duo E7300 code "if (p_cnt < (nWorkers * 20))" provides 100% load and particles bugs(it`s look like rainbows instead anomalies) instead "if (p_cnt < (nWorkers * 64))"

Code "if (p_cnt < (nWorkers * 64))" i found in sources of release engine version of COP

Code "if (p_cnt < nWorkers) = p_cnt;" i did not see and don`t tried to use

**Comment by ViHtarb** [comment]
Now i noticed that this change is not in the dev and another branches of project. But why?

**Comment by Xottab-DUTY** [comment]
@nitrocaster fixed this.. Maybe this commit was occasionally dropped.
So, we need to find, what solution is better
```
if (p_cnt < (nWorkers * 64))
    nWorkers = 1;
```
or
```
if (p_cnt < nWorkers)
   nWorkers = p_cnt;
```

**Comment by revolucas** [comment]
Uneven distribution of workload on cores is not and never will be, a bad thing. It is actually a good thing.

**Comment by revolucas** [comment]
CPU usage is 90% on my 6-core with:

if (p_cnt < nWorkers)
   nWorkers = p_cnt;

-------------------------
if (p_cnt < (nWorkers * 64))
    nWorkers = 1;

Is how it is in Shadow of Chernobyl and Clear Sky source and does seem to run better then * 20. Only 20% CPU usage.

I downloaded CoP revision 8384. It seems to be much older then whatever Nitro used as the base for OpenXray.

**Comment by Xottab-DUTY** [comment]
Oh, thank you!
As far, as I know, nitrocaster used 1.6.0.2 and r8384 should be newer... Looks like I catch some bit of a nonsense here. =)
But whatever, `* 64` seems to be a better solution.

P.S. by the way, @ViHtarb says that `(nWorkers * 20)` gives graphical bugs. @revolucas what about graphics look with `if (p_cnt < nWorkers) nWorkers = p_cnt;` variant? Just interesting)

**Comment by revolucas** [comment]
I didn't notice any graphical differences, only lag when using `if (p_cnt < nWorkers) nWorkers = p_cnt;`

I don't know about r8384. It's strange as it has many slight differences, almost like it's sabotage to make it run as shitty as possible.

**Comment by Xottab-DUTY** [comment]
In theory `if (p_cnt < nWorkers) nWorkers = p_cnt;` should increase performance because it creates more workers if there's many particles.. But workers themselves needed to be optimized to take effect of multiplying them... Well.. all the code needs optimizing I'd say))
