### ISSUE TITLE
A way to debug x-ray engine

### ISSUE THREAD

**Issue by sobkas** [OpenXRay/xray-16#25]
I would like to have a prebuild version of engine, I'm trying to debug wine nine state tracker code and this would help a lot
Also is there a way to disable bugtrap.dll? It is really inconvenient to debug engnine/wine/mesa while bugtrap.dll hijacks signals

**Comment by nitrocaster** [comment]
Look for `USE_BUG_TRAP` and `USE_OWN_ERROR_MESSAGE_WINDOW` macros.
