### ISSUE TITLE
Replace D3DXMath

### ISSUE THREAD

**Issue by Xottab-DUTY** [OpenXRay/xray-16#261]
This is a part of #101.

Lets talk about replacing this part of legacy D3DX library.

Suggestions:
1. [GLM](https://github.com/g-truc/glm/) – likely candidate to use.
2. [DirectXMath](https://github.com/Microsoft/DirectXMath) – ~~it it crossplatform? If not, then we should use something different.~~ It is crossplatform.
3. Any other suggestions?

Also, if we will use GLM or DirectXMath, I suggest to replace our own engine math classes like `Fmatrix` and `Fvector` with classes from selected library.

**Comment by drug007** [comment]
I would prefer `glm`.

**Comment by ademe-del** [comment]
Looks like DirectXMath was designed for Windows, but take a look to this interesting post:
https://www.gamedev.net/forums/topic/655311-directxmath-osxlinux/?do=findComment&comment=5145291

**Comment by ForserX** [comment]
Опять идеи воруешь?

**Comment by Xottab-DUTY** [comment]
А ты уверен?)
Я это рассматривал ещё год назад, только в issue не было сформулировано.
Обсуждали это с @andrew-boyarshin и, вроде бы, с @nitrocaster.

**Comment by ForserX** [comment]
Гип об этом говорил ещё в первом заходе в фрэй

**Comment by Xottab-DUTY** [comment]
А, ну, я вашу переписку не видел, ты нашу не видел.. Об одном думаем.
Всё, в целом, дальше мусолить смысла нет.

**Comment by AKonia** [comment]
Как вариант ещё: Eigen, его многие открытые проекты используют

**Comment by drug007** [comment]
`Eigen` is heavy template library and probably its usage will increase compilation time.

**Comment by AKonia** [comment]
**But** `Eigen` is flexible and optimized for sse, it has intuitive API and I suppose "increased compilation time" is low blood.

**Comment by Cheburum** [comment]
> **But** `Eigen` is flexible and optimized for sse, it has intuitive API and I suppose "increased compilation time" is low blood.

GLM is fast too. But it is better to have benchmarks.

**Comment by Xottab-DUTY** [comment]
D3DXMath was replaced with DirectXMath.

https://github.com/OpenXRay/xray-16/commit/b4497a9ad0c5c71f71ec7b1fc31ffebbaf37aaa6, https://github.com/OpenXRay/xray-16/commit/dd86d7167a5e908aecb63018c5903fd72ea0961a, https://github.com/OpenXRay/xray-16/commit/ec397af403c772ba98f80b8547cd4111d69ae524, https://github.com/OpenXRay/xray-16/commit/b048d148d378f8633c9e132ad0ba25a81398ed9e
