### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by Xottab-DUTY** [OpenXRay/xray-16#278]
There is a question of changing the code style suggested by @FreeZoneMods:

Current casing styles:
- class/struct/enum: `PascalCase`
  - Math primitives can be in lowercase:
    `vector2f`, `angle3f`, `matrix44f`
  - Using declarations of primitive types can be in `lowercase`:
    `uint`, `int16`, `uint64`
- Functions: `PascalCase`
- Public and protected fields: `PascalCase`
  - Math primitives can use `lowercase`:
    `vector2f.x`, `angle3f.yaw`, `matrix44f.m03`
- Private fields: `camelCase`
- Local variables: `camelCase`
- Global variables: `PascalCase`
- Namespaces: `PascalCase`

The question:
Should we add a rule to use prefix for global, global static, and member and const variables?
Modified casing styles:
- Private fields: `camelCase` with prefix `m_`.
- Global variables: `PascalCase` with prefix `g_`
- Global static variables: `PascalCase` with prefix `s_`
- Global constant variables: `UPPER_CASE`

**Comment by Xottab-DUTY** [comment]
Another question is about difference in [cpp_code.txt](https://github.com/OpenXRay/xray-16/blob/xd_dev/doc/procedure/cpp_code.txt) file and [Cpp Coding Conventions](https://github.com/OpenXRay/xray-16/wiki/Cpp-Coding-Conventions#file-naming-and-mandatory-content) wiki page. They are both define the code style.
In `cpp_code.txt` there's a station about trivial expression:
```Trivial > >= < <= == != expressions should not have spaces around them.
Examples: a, array[i].var[j], sizeof(Foo), x+1
Pointers (->) are not counted as trivial expressions for > >= < <=, since it's
hard to read x->y>z, while its easy to read x->y==z.
 BAD
    if (x > 5)
 GOOD
    if (x>5)
 BAD
    if (x+1>5)
 GOOD
    if (x+1 > 5)
 BAD
    if (f(x, y) > g(y, z))
 GOOD
    if (f(x, y)>g(y, z))
 BAD
    if (x->y == 5)
 GOOD
    if (x->y==5)
 BAD
    if (x->y>=5)
 GOOD
    if (x->y >= 5)```

I think we should change it to specify that we should use spaces.

**Comment by Xottab-DUTY** [comment]
@OpenXRay/xray-contributors, summoning all the team here.

**Comment by Xottab-DUTY** [comment]
If someone doesn't like some other code style item, it should also be discussed.
Propose your suggestions here.

**Comment by drug007** [comment]
I suggest to not change code style at all. It's too subjective thing you can spend too many hours discussing it and you never satisfy everybody at all. So why bother? Professionals (and everyone tries to become professional, doesn't it?) do not suffer of code style. Just because amount of possible code styles is about infinity.
Another pitfall of code style changing is that we do not have consistent code style now and changing it we can bring more mess instead of order. The meaning of code style is code uniformity at first and  specific form is much less relevant.

**Comment by FreeZoneMods** [comment]
"Professionals (and everyone tries to become professional, doesn't it?) do not suffer of code style" - of course, yes. They don't suffer from a good and comfortable coding style. They suffer from moronic one (which doesn't correspond to real code) or from absence of coding style at all. Such 'coding styles' make the code is hard to read, to understand and to review. And of course it leads to creating some dully bugs from scratch. X-Ray is not an ideal engine, so let's won't make it just _more_ complicated. A good coding style should allow us to save time and nerves of reviewers and programmers.
We could easily see that current coding style doesn't correspond in some statements to current code. It's a very-very bad situation. Sometimes you should refactor or extend some parts of the old code, which use another coding style. And what is your choice? Do you prefer to write a code according to original engine coding style? Or do you want to follow the coding style from the project's wiki? Both ways are wrong, but there is no other variants.
I think that we should correct the current coding style to to get it to match the most part of the _real_ codebase.

**Comment by collectioner** [comment]
Let me add a few thoughts about it. Of course, IMHO. Current code-style looks good. I'm thinking from the .NET side, of course, and from my commercial dev experience. I agree with constants naming `UPPER_CASE`. And really don't understand necessary of prefixes, like "m_", "p_". I guess, in your opinion, they, they should add a better understanding, but we all use a modern IDE's. They all can show if variable global, or static or someone else. In my thoughts, prefixes just will give us less readability. 
Another theme: are you considering a design changes?

@FreeZoneMods Why we cannot perform code refactoring with respect to the current code-style? Why we `should` change our code-style in terms of current codebase?

**Comment by drug007** [comment]
> @FreeZoneMods Why we cannot perform code refactoring with respect to the current code-style? Why we should change our code-style in terms of current codebase?

this

And the whole state of the engine makes me think the code style changing isn't important enough to be done right now.

**Comment by collectioner** [comment]
@drug007 of course, it isn't a main current task. But, we should resolve this issue. We should have one final code-style and should write new code with respect to it. 

I just don't understand, why @FreeZoneMods wants to change code-style due codebase, not the other way around.

**Comment by FreeZoneMods** [comment]
@collectioner 
1) It's much simpler to change some lines in the coding style than refactor a lot of places in the code 
2) Such mass-styling commits make 'blame' tool much less usable
3) The naming style which is currently used in the most part of 'original' code is much more convenient than the one from the coding style. the current style doesn't divide variables with different visibilities and lifetime well enough. For example, let's imagine a fragment (such fragment may be a part of the diff in the review) of the some methods:
`
return &someVariable;
`
Is there a bug or not? I can't tell you without examining the lifetime of the someVariable. The current coding style doesn't make a distinguish between local variables and member variables! But if we introduce the rule 'all member fields should start with prefix m_ in the name' it will be quite obvious that the fragment contains an error and should be corrected.

@drug007, to have a two inconsistent coding styles - it's so cool! The longer this goes on, the worse the code becomes.

**Comment by collectioner** [comment]
@FreeZoneMods ok, I got it. Yes, change code-style is easier, you're right. But.. "let's take the path of less resistance, uh?" I'm not good with it. Of course, just my thoughts, without any charges. Next. We can perform refactoring in the commits. You wrote code, wanted to commit and noticed wrong style 10 lines above. Good practice: make another commit for it, yes. But I don't see an issue if we'll perform small refactoring with our logic' commits. And the last: after few years of experience, I never had an issue with member fields and local variables. Really. There is some logic in your reasoning, and most likely, your experience bigger than mine, but. But.. I just realized why I hadn't issues with the last point. Because all my member fields were with `_` prefix. My bad :D 
Well, what do you think about this possible improvement? Instead of "m_" just "_"?

**Comment by drug007** [comment]
@FreeZoneMods I do not suggest several code styles simultaneously, I suggest to not have them. If you suggest to change code style to be more consistent with current code base I'm totally agree with you. But then we shouldn't have any question about code style but just get it from source base.

**Comment by drug007** [comment]
@collectioner Code formatting shouldn't be another commit. It shall be another PR.

**Comment by collectioner** [comment]
@drug007 Yes, you're right. But again, small refactoring.. I don't think we need new commits/PR's for it, like my example.

**Comment by Zegeri** [comment]
A different issue that might be worth adding to the Coding Conventions in the file naming section: how should inline implementation files be named? The current most common way is using `*_inline.h` (e.g. `item_manager_inline.h`), but I've seen in some newer parts of the codebase `*.inl` (e.g. `PlatformWindows.inl`). Is the `*.inl` format the preferred way?

**Comment by drug007** [comment]
@collectioner When sometime later you would need to revert  PR all formatting it contains will be reverted too. It will make code less consistent. It may be even very annoying. Much more annoying than making separate PR for fomatting. Every PR should do one thing only. Frankly it's not easy to follow this rule but everytime I get a mess due to reverting I regret I didn't do it right.

@Zegeri `_inline` is more apropriate I think.

**Comment by Xottab-DUTY** [comment]
> `_inline is more apropriate I think.`

It's used by the previous programmers from GSC. But we should decide our own way: use `.inl`, `*_inline.h` or another.

**Comment by collectioner** [comment]
@drug007 Okay, you're right. TBH, I didn't think about reverting PRs, since it isn't smth like "everyday routine" of my work.

@Xottab-DUTY @Zegeri I think `.inl` is good one. Short, meaningful. One quick question: is.. is this acceptable? I mean, another file extension than `.cpp`, `.h` and so on.

**Comment by drug007** [comment]
@Xottab-DUTY  if it has been used for years why should we change it?
@collectioner  yep, it happens seldom for me but when it happens...

**Comment by Xottab-DUTY** [comment]
> `if it has been used for years why should we change it?`

There's more than one code style in the engine. The latest `lower_case` naming style was adopted when Dmitry Iassenev was lead programmer.
I suggest to use his `lower_case` to observe the continuity of generations.

But using `lower_case` style is a BIG change to our current style since it defines `camelCase` and `PascalCase` usage.

**Comment by Xottab-DUTY** [comment]
But using `lower_case` style is a BIG change to our current style since it defines `camelCase` and `PascalCase` usage.

**Comment by collectioner** [comment]
@Xottab-DUTY Yep. So let's leave `camelCase` & `PascalCase` and remove `this_stupid_case`

**Comment by AKonia** [comment]
- Возьмите clang-format и базируясь на стиле Mozilla, сделать все столь "важные" изменения.
- А по уму всё-таки менять уже написанный код - бред, лучше просто определится с конкретным стилем(для новых файлов) и опять же напросать его в .clang-format файл. В старых исходниках стоит соблюдать исходный стиль
- ИМХО префиксы - бред, т.к. особо полезной информации не несут, а имена усложняют
