### ISSUE TITLE
Holy shit

### ISSUE THREAD

**Issue by ghost** [OpenXRay/xray-16#28]
@nitrocaster I am impressed. You are on fire optimizing the engine right now in ai_cleanup! Great work!

I just wanted to say that I looked at your todo list, and there are several of the features you are looking for in the revoculas branch on here, which I have contributed to as well.

It has fixes for the DirectX compiler error (you need to add dxguid.lib to the stdafx.h, it fixes it).
I also fixed blurred R4 font on there, it's in that branch's xrRender/dxFontRender.cpp.

There is also corrected sun path, actor shadows on all renderers, and many other improvements.

On the newest avotishin branch that the revoculas branch is based on, there is also LuaJit 2.0+

You probably already know, just wanted to give you a heads up so you don't reinvent the wheel.

**Comment by nitrocaster** [comment]
I know some features are done, but I want to finish with my global changes before getting into things like luajit/luabind updating.

**Comment by ghost** [comment]
Fair enough, just thought I'd tell you. Keep up the amazing work!
