### ISSUE TITLE
Fallback shader does not work on Intel HD (OpenGL)

### ISSUE THREAD

**Issue by drewpts** [OpenXRay/xray-16#284]
Fallback shader does not work on Intel HD

Driver version - 22.20.16.4771

**Comment by Xottab-DUTY** [comment]
@drewpts can you confirm that issue is still there?

**Comment by drewpts** [comment]
let me try, will let you know :)

**Comment by Xottab-DUTY** [comment]
@drewpts, so.. ?

**Comment by Xottab-DUTY** [comment]
@drewpts, please, reopen this, if it doesn't work ;)
