### ISSUE TITLE
INSTALL cannot find luabind (linux)

### ISSUE THREAD

**Issue by aregic** [OpenXRay/xray-16#285]
Hello,

I'm trying to build the engine on linux and I have the following error when I run `make -DESTDIR=... install`

```
Install the project...
-- Install configuration: "Release"
-- Installing: /home/regic/.PlayOnLinux/wineprefix/STALKERCallOfPripyat/drive_c/cop/bin-linux-dbg/./luajit.so
CMake Error at Externals/cmake_install.cmake:52 (FILE):
  file INSTALL cannot find
  "/media/regic/2nd_SD/linux/COP/xray-16/Externals/$<TARGET_FILE:luabind>".
Call Stack (most recent call first):
  cmake_install.cmake:37 (INCLUDE)


make: *** [install] Error 1
```
luabind seems to be built correctly:

```
regic@gfdkjlherkj /media/regic/2nd_SD/linux/COP/xray-16/bin $ find . -name *.so
./Externals/luabind/src/luabind.so
./Externals/luajit.so
./Externals/ode/libODE.so
./Externals/OPCODE/OPCODE.so
./src/Layers/xrAPI/xrAPI.so
./src/Layers/xrRenderPC_GL/xrRender_GL.so
./src/utils/xrLCUtil/xrLCUtil.so
./src/xrAICore/xrAICore.so
./src/xrCDB/xrCDB.so
./src/xrCore/xrCore.so
./src/xrEngine/xrEngine.so
./src/xrGame/xrGame.so
./src/xrGameSpy/xrGameSpy.so
./src/xrNetServer/xrNetServer.so
./src/xrParticles/xrParticles.so
./src/xrPhysics/xrPhysics.so
./src/xrScriptEngine/xrScriptEngine.so
./src/xrSound/xrSound.so
./src/xrUICore/xrUICore.so
```

**Comment by a1batross** [comment]
Hm. It should replace $<TARGET_FILE:luabind> by luabind DLL. 

What version of CMake do you using?

**Comment by a1batross** [comment]
Also, it just DESTDIR, without minus sign in the beginning.

Just `make install DESTDIR=...`

**Comment by aregic** [comment]
cmake version 2.8.12.2

I did it without the sign, I've just wrote here incorrectly, sorry for that. I've replaced the TARGET_FILE expression manually to point to the luabind.so built into the bin folder and the install worked.

**Comment by aregic** [comment]
I've upgraded cmake to 3.5.1 (simple apt-get, linux mint) and TARGET_FILE is now correctly replaced. Might be useful to either add cmake3 to dependency, or - if it's just a linux problem - mention it in the linux installation guide.

**Comment by Xottab-DUTY** [comment]
@aregic, so, issue can be closed?

**Comment by a1batross** [comment]
Then cmake_minimum_required should be increased.
