### ISSUE TITLE
Linux build FATAL ERROR OpenXRay Rx64 build 7238

### ISSUE THREAD

**Issue by SwForust** [OpenXRay/xray-16#288]
the game crashes in a few seconds
os: mint 18.3
kernel: 4.18
cpu : Xeon X5460
ram: 8gb
gpu: GTX 750 1 gb
driver GPU: nvidia native 415.18

FATAL ERROR
 
[error] Expression    : <no expression>
[error] Function      : handler_base
[error] File          : /home/maks/git/xray-16/src/xrCore/xrDebug.cpp
[error] Line          : 781
[error] Description   : segmentation fault

![ss_ _ _ zaton](https://user-images.githubusercontent.com/28722726/49331429-c77ff800-f5ad-11e8-9cad-626665ffa1a1.jpeg)
[openxray_.log](https://github.com/OpenXRay/xray-16/files/2636214/openxray_.log)

**Comment by Xottab-DUTY** [comment]
Yes, it crashes when you start a new game after few seconds. We're working on it. For now you can use existing game savevthat was done after you have received these helicopters tasks

**Comment by xrombik** [comment]
No FATAL ERROR in linux build when you start a new game after few seconds. Close this issue please.

**Comment by Xottab-DUTY** [comment]
Ok, @SwForust, can you confirm the bug is fixed for you too?

**Comment by Xottab-DUTY** [comment]
Should be fixed. Tell us if it's not.
