### ISSUE TITLE
Is xrScriptEngine working correctly at the moment?

### ISSUE THREAD

**Issue by ghost** [OpenXRay/xray-16#29]
I'm talking about your ai branch of course.

I realize you're not finished what you want to do it, but all the changes got me excited to try and start engine changes from scratch with your repo as the base.

However, when I tried to compile xrScriptEngine it claims there are several undeclared identifiers, including: m_script_name, m_virtual_machine, and m_active.

Sorry to bother you and thank you for your time.

P.S. If I follow proper coding conventions would it be cool if I took care of a few things on your task list in the form of pull requests?
I could do: blurred text fix for R4; incorrect sun path (you say for R1, but do you want sun path to follow environment config variables as that's what I'm referring to); actor shadow for R2-R4; grass shadows; grass draw distance settings; removal of R1; improve weapon system (new optional animation types, new optional sound types, re-enable zoom and reload dof, add console-controlled manual reloading); I also believe OGSE had a transparent geometry fix so I could look into that too.

If any of that interests you let me know, as since I'm toying with your source in various ways while toying with my own project, I don't mind helping out to the extent that I'm capable (and I'm not anywhere near as terrible about things as I was a long while back when I tried a couple of bad commits to your repo ;) ).

Also, a suggestion: when browsing through ODE a bit I noticed it seems to have some shared code with Nvidia PhysX. Maybe instead of updating ODE to the new version you could use PhysX instead, as that would also easily allow other things such as non-performance draining particle collision, particle shadows, vegetation collision, etc. Just a thought.

One last thing: check out this game development newsletter that was sent out about common causes of stutter and micro-stutter in games and how they can be fixed: http://go.nvidianews.com/Lds0NF00d0sE3OCcD060E0M

**Comment by nitrocaster** [comment]
No, it doesn't. ai_cleanup branch doesn't work now (though every project can be compiled except for xrPostprocessEditor). See master and dev branches - they're required to be working.

**Comment by nitrocaster** [comment]
Regarding the tasks you could do: you're welcome, just reassign them to yourself. However, you should understand that one of our goals is to maintain the original game concept, so when it comes to some new features (see 'ideas to consider' sections in task list), please tell your suggestions so we could discuss them together.

**Comment by nitrocaster** [comment]
As for ODE/PhysX - there's a lot of work to be done before one should think about other physics engines.

**Comment by ghost** [comment]
Okay, I understand. I realize it's a working branch, I should have been more patient. I was just very eager to try out the multithreading synchronization fix, but it looks like it would be a lot of work if I tried merging that with my branch that's based off of Avotishin & Revolucas as you made a lot of changes to get that to work it looks like.

In terms of new features, what I listed is all I planned to do. I can go without doing those optional weapon features for instance. In fact maybe it would be best not to add any weapon features right now as a big weapons mod will be releasing their source code soon and will have better stuff, though not all of it may fit the original game concept.

I can also not remove the R1 renderer yet if you think you might still use it.

If I have any new feature ideas I will of course run them by you first.

**Comment by nitrocaster** [comment]
xrScriptEngine seems to be working now.

**Comment by ghost** [comment]
Yay! I'll grab the latest changes and try compiling again :)
