### ISSUE TITLE
[Linux] Shader compilation error due to OpenGL 4.5 requirement

### ISSUE THREAD

**Issue by ivdok** [OpenXRay/xray-16#293]
Runtime log: [openxray_ivdok.log](https://github.com/OpenXRay/xray-16/files/2645170/openxray_ivdok.log)
Shell arguments: `DRI_PRIME=1 ./xr_3da.sh -fsltx ../fsgame.ltx `
OpenGL capability matrix: [opengl.log](https://github.com/OpenXRay/xray-16/files/2645179/opengl.log)

Since Mesa 18.2.0 (I'm using 18.2.6 currently) has released, it has implemented OpenGL 4.5 API, but the version reported by glGetString or glGetIntegerv depends on the particular driver being used, and in my case, that's 4.4 Comptibility profile. Since I'm not really planning on using tesselation features, is it possible to set OpenGL requirements lower, and instead request glx extensions on-demand?

**Comment by LoneSimba** [comment]
Hmmm, may this be the cause of my launch failures on both Win and Ubuntu with the same "shader compilation" errors....

**Comment by johndoe71rus** [comment]
try
```
 MESA_GL_VERSION_OVERRIDE=4.5 ./xr_3da.sh -fsltx ../fsgame.ltx 
```

**Comment by ivdok** [comment]
>  MESA_GL_VERSION_OVERRIDE=4.5 ./xr_3da.sh -fsltx ../fsgame.ltx

That did work...ish. The game does proceed to the main menu, but launching the singleplayer craps out. Attaching log here: [openxray_ivdok.log](https://github.com/OpenXRay/xray-16/files/2659751/openxray_ivdok.log)
Wish I knew how to make, find and attach coredump - bet I'd be more useful here.

I forgot to specify this before, but I'm building this project on Manjaro Linux, and here are the packages involved:

- glew 2.1.0-1 (+ lib32-glew)
- freeimage 3.18.0-2
- liblockfile 1.14_1.1-1
- openal 1.19.1-1 (+ lib32-openal)
- intel-tbb 2019-1
- crypto++ 7.0.0-1
- pugixml 1.9-1
- libtheora 1.1.1-4 (+ lib32-libtheora 1.1.1-11)
- libogg 1.3.3-3 (+ lib32-libogg 1.3.3-2)
- sdl2 2.0.9-1 (+ sdl2-image 2.0.4-2, sdl2_mixer 2.0.4-1, sdl2_ttf 2.0.14-2, lib32-sdl2 2.0.9-1, lib32-sdl2_image 2.0.4-1, lib32-sdl2_mixer 2.0.4-1, lib32-sdl2_ttf 2.0.14-3)
- lzo 2.10-2
- libjpeg-turbo 2.0.1-1 (+ lib32-libjpeg-turbo 2.0.0-1)
- libjpeg6-turbo 1.5.3-1 (+ lib32-libjpeg6-turbo)

Build process has been relatively clean, with a few warnings unrelated to the packages mismatch. So I doubt it has anything to do with my issue, but maybe worth mentioning.

**Comment by johndoe71rus** [comment]
The launch of the new game is unstable. Presumably due to weather options. I managed to launch a new game on Linux.

**Comment by ivdok** [comment]
I've got a little bit further this time, here's the log: [openxray_ivdok.log](https://github.com/OpenXRay/xray-16/files/2659772/openxray_ivdok.log)
This time I've seen a HUD, weapon model and a bit of world geometry, but no intro movie, and and immediate CTD afterwards. I'll try to load pre-saved game now for comparison.

**Comment by johndoe71rus** [comment]
https://dropmefiles.com/8SatC start game save, store only 6 day

**Comment by ivdok** [comment]
[openxray_ivdok.log](https://github.com/OpenXRay/xray-16/files/2659786/openxray_ivdok.log)
Got to the gameplay part, but it's highly unstable - ultra low brightness, FPS issues, and a CTD while trying to call main menu. Not sure if I should file separate issue or continue this one - maybe it is realted to OpenGL 4.5 after all.

**Comment by johndoe71rus** [comment]
my video https://dropmefiles.com/5gxIs ultra low brightness too

**Comment by johndoe71rus** [comment]
now you can try key -use_gl_4.1 and MESA_GL_VERSION_OVERRIDE=,  the game behaves differently.
and you can enable flashlight key - L

**Comment by johndoe71rus** [comment]
Does https://github.com/OpenXRay/xray-16/commit/66945b9e668ce20a04b1b227201b471fd49c5f05 fix the problem?

**Comment by Xottab-DUTY** [comment]
Outdated
