### ISSUE TITLE
[Windows] Click on "Updates" button crashes the game

### ISSUE THREAD

**Issue by StalinEXE** [OpenXRay/xray-16#296]
**Операционная система**: Windows 10 1803
**Релиз игры**: GOG
**Язык**: Русский

**Описание проблемы**:
Если зайти в настройки и нажать на кнопку "Обновления", то через примерно секунд 10-15 случится вылет. Движок предлагает отправить баг-репорт, так что я прикрепляю сгенерированный им архив с логами.

[XRayEngine_error_report_181213-102548.zip](https://github.com/OpenXRay/xray-16/files/2674962/XRayEngine_error_report_181213-102548.zip)

**Путь воспроизведения ошибки**:
Просто зайти в настройки и нажать на кнопку "обновления".

**Ожидаемый результат/предложения**:
Ожидалось, что выскочит ошибка, или же не будет никакой реакции, так как это сторонний проект.
Теоретически можно удалить кнопку. Или реализовать появляющееся окно с текстом. Или сворачивать игру при нажатию и открывать главную страницу проекта на GitHub'e.

**Comment by collectioner** [comment]
@StalinEXE Привет. Можешь прикрепить скрин кнопки "Обновления"? Не совсем понял, где она. Интересно, что errorlog.log выводит некорректную информацию о системе.

**Comment by FreeZoneMods** [comment]
@collectioner, в настройках на вкладке "Игра" оно. Один из рудиментов системы автообновления игры(а вы все знали, что такая есть и успешно работает, начиная еще со времен глубокого ТЧ?)
@StalinEXE, попробуй то же самое сделать через консоль: команда check_for_updates. Тоже закрешится?

**Comment by StalinEXE** [comment]
> 
> 
> @StalinEXE Привет. Можешь прикрепить скрин кнопки "Обновления"? Не совсем понял, где она. Интересно, что errorlog.log выводит некорректную информацию о системе.

Пардоньте, уведомление не получил. Если ещё нужно, ещё могу сделать скриншот.
О системе смогу предоставить информацию с понедельника (компьютер не со мной будет на выходных).

> @StalinEXE, попробуй то же самое сделать через консоль: команда check_for_updates. Тоже закрешится?

Да. Ввёл команду, в консоли никакого выхлопа не было. Через несколько секунд игра закрылась. Прикрепляю новый лог.
[XRayEngine_error_report_181214-155107.zip](https://github.com/OpenXRay/xray-16/files/2680108/XRayEngine_error_report_181214-155107.zip)

**Comment by FreeZoneMods** [comment]
А, да там, похоже, очевидно все, классика жанра. Кто-то недоревьвленный из обработчика команды CCC_GSCheckForUpdates::Execute пытается кидаться локальным делегатом в CGameSpy_Patching::PatchCheckCallback cb. А так как у нас геймспай проверяет патчи в отдельном потоке, к моменту окончания проверки стековый делегат уже давно сдох.
Пофиксайте по-быстрому кто-нибудь, кому не лень :)

**Comment by eagleivg** [comment]
Может вообще выпилить апдейтер?

**Comment by FreeZoneMods** [comment]
Да зачем? Вроде есть, работает, кушать не просит. Проще починить, чем выпиливать. Может, потом благому делу научим - обновлять билды. Там, по сути, просто одну ссылку на motd поменять надо будет

**Comment by FreeZoneMods** [comment]
Запилил фикс по-быстрому, PR #298. Погоняйте, кому не лень, все ли там ок

**Comment by RomkaZVO** [comment]
Редиректить на свежие билды да и все

**Comment by FreeZoneMods** [comment]
Это в будущем уже думать надо будет. В идеале - готовый инсталлер-обновлятор собирать бы автоматом и выкачивать клиентом. Пока - просто пофиксим креш.

**Comment by Xottab-DUTY** [comment]
Fixed with #298
