### ISSUE TITLE
[Windows] xrRender_R* errors

### ISSUE THREAD

**Issue by LoneSimba** [OpenXRay/xray-16#306]
Trying to fire the latest commit and failing with this [new 1.txt](https://github.com/OpenXRay/xray-16/files/2713486/new.1.txt)
Is there a way to fix this (i assume, it's pretty easy)?

**Comment by Xottab-DUTY** [comment]
Do you compiled the renderers?

**Comment by LoneSimba** [comment]
Well, i checked this just AFTER published this, so renderers is fine now, sry for this topic (yep, i'm slow and stupid)

**Comment by Xottab-DUTY** [comment]
No problem! :smiley:
