### ISSUE TITLE
Enhancement request: fix cloud lerping

### ISSUE THREAD

**Issue by ghost** [OpenXRay/xray-16#31]
I have had two programmers look at this issue and neither could figure out why clouds_texture does not correctly lerp between two different sets of clouds_texture.

For example if I set 9:00 in the config to have one clouds_texture, and I set 10:00 to have a different one, rather than a smooth transition between the two, the second it turns to 10:00 it immediately changes to the new texture, which obviously works terrible.

If at some point you were interested in tackling this, or anyone else that's reading this, I would be really grateful.

**Comment by nitrocaster** [comment]
Has it ever worked?

**Comment by ghost** [comment]
No, it has never worked.
The weird thing is that the code for it seems to be pretty similar for the sky texture lerping, yet that works in the cloud layers don't.

**Comment by SkyLoaderr** [comment]
Timely fixed in 1cde883cd1448ddae46934804ece7de37edaf60e (RGL) and in OpenXRay Plus in PR https://github.com/OpenXRay/Plus/pull/2 (R1-R4)
