### ISSUE TITLE
GNOME 3 top bar stays on top of the game

### ISSUE THREAD

**Issue by tpimh** [OpenXRay/xray-16#310]
Probably this bug was introduced with 7948e63077ddd4a151f4386c7246192f258f9a1f: GNOME 3 top bar is rendered on top of the game and won't go away.

**Comment by eagleivg** [comment]
Which composer you use?

**Comment by tpimh** [comment]
I noticed strange resolution in the game settings menu and toggled fullscreen twice. That fixed both the resolution and the bar being on top of the game.
