### ISSUE TITLE
Clarify IRC channel address

### ISSUE THREAD

**Issue by uralets** [OpenXRay/xray-16#311]
Currently it says
> IRC channel #openxray on **freenode.org**

it was meant to be **freenode.net** wasn't it?

**Comment by Xottab-DUTY** [comment]
That's no matter if it's .org or .net since freenode.org redirects us to freenode.net anyway.

**Comment by Xottab-DUTY** [comment]
But, @nitrocaster, could you say something?

**Comment by uralets** [comment]
That's no matter if it's .org or .net since freenode.org redirects us to freenode.net anyway.

Yeah but its still a tad uborthodox.

Its soooo quiet there anyways...

**Comment by uralets** [comment]
Poked around a bit, and yeah I've found people sometimes specifying .org instead of .net

So probably a non-issue.

Let's change the $subj to **ALL DEVS TO IRC** now shall we?)

**Comment by Xottab-DUTY** [comment]
No. IRC is just a text chat without even chat history while you can speak with your voice in Discord, share your screen, share files and much more..

**Comment by uralets** [comment]
all these are very important to C++ game engine development ofc.
and history CAN be implemented, it's just not very frequently done.

**Comment by uralets** [comment]
Could we think of migrating to IRC in case we come up with a good chat history solution?

**Comment by uralets** [comment]
Come to think of it, file transfers also exists in IRC...
So is it just down to video calling/screen sharing then? Are we twitch'ing (pardon the pun) or doing development here?

**Comment by collectioner** [comment]
Chat history just a one feature. You forgot about sharing screens/files/roles/voice meetings and so on.

Again, IRC is just a text chat. 

Another side: we're connecting with many other devs. What should we do in this case? How we'll chat/ask for help?

Yes, we have Slack as special messanger for devs, but it doesn't have voice rooms/voice meetings.

If you're dev, you should know that communication is an important part of development. And Discord provides better experience and better possibilities for it. 

I think this questions is closed.

**Comment by Xottab-DUTY** [comment]
Just to say, you can use IRC and write messages there – we will see them in Discord and you'll see our messages. So, this isn't a big problem.

**Comment by uralets** [comment]
>If you're dev, you should know that communication is an important part of development.

yeah I'm fully aware.
what I didn't know is that a special chat for devs where you can show your post-NY mug to others is so important to development)))

have a sneaky feeling here that your choice of tools is mostly based on gaming/twitching/whatever activities not really tied to development...

thanks for answering tho.

closing.

**Comment by Xottab-DUTY** [comment]
> have a sneaky feeling here that your choice of tools is mostly based on gaming/twitching/whatever activities not really tied to development...

Nope. Choise is based on social communication.
Programmers can talk with other programmers on interesting subjects, they can even talk on subjects not related to S.T.A.L.K.E.R.
We can speak there with our players, testers and others..
Also we can mark users with roles like Tester, Programmer, OpenXRay team member, another project team member and such.

Social coding, wide communication, not just coding.

**Comment by uralets** [comment]
yeah yeah it's all good 'n all "social coding" thingie...
can't see that horde of "social testers" on here who helped debug the outright bug(s) on Linux which prevented event STARTING the damn thing....

**Comment by collectioner** [comment]
Maybe you should check our discord-server, if you aren't there yet?
You can see messages from just one channel of server on freenode, but we have a few channels.
We have many testers that help us find and fix bugs.
Also, porting is not completed yet. And we didn't make a release.

So I don't understand your position.

**Comment by a1batross** [comment]
Just another troll. Don't feed them.

**Comment by uralets** [comment]
> Just another troll. Don't feed them.

eeehhhhrm... K den. lol.
