### ISSUE TITLE
CMake removes SDK/include/tbb

### ISSUE THREAD

**Issue by xrombik** [OpenXRay/xray-16#313]
Commit 182db49c0ff3308c3f2128574268d5b99978b088 should be removed from PR.

_Originally posted by @drug007 in https://github.com/OpenXRay/xray-16/pull/312#issuecomment-450735753_

These changes appear after running cmake in a Linux environment. Even if I roll back to the prev commit, these changes will still exist.

**Comment by Xottab-DUTY** [comment]
Wrong name for the issue.

Why CMake removes SDK/include/tbb folder? That's the question.

**Comment by Xottab-DUTY** [comment]
Or... Or CMake doesn't do that?

When you are rolling back your changes, you should push the changes. Did you do this?

**Comment by xrombik** [comment]
Yes, but only after rebuild.

**Comment by Xottab-DUTY** [comment]
Ok. We have fixed this with @xrombik

**Comment by Xottab-DUTY** [comment]
This is the issue reason:
https://github.com/OpenXRay/xray-16/blob/xd_dev/CMakeLists.txt#L114
```cmake
if(EXISTS ${CMAKE_SOURCE_DIR}/sdk/include/tbb/tbb.h)
    file(REMOVE_RECURSE ${CMAKE_SOURCE_DIR}/sdk/include/tbb)
    file(REMOVE_RECURSE ${CMAKE_SOURCE_DIR}/sdk/include/serial/tbb)
endif()
```

We should not delete these files.

**Comment by drug007** [comment]
This was introduced by commit 28015822145e2aca98b5b2a3100a97101ff05c9b

**Comment by eagleivg** [comment]
This removing do for avoid potential problem with mismath of tbb headers with library in distributive(for windows need use sdk headers). Single problem - git status command show this as changed and do not hide with .gitignore
May be resolve this by add second ugly workarround - do `git checkout sdk` after build ending?

**Comment by uralets** [comment]
> This removing do for avoid potential problem with mismath of tbb headers with library in distributive(for windows need use sdk headers). Single problem - git status command show this as changed and do not hide with .gitignore
> May be resolve this by add second ugly workarround - do `git checkout sdk` after build ending?

in all honesty this is sad.

зачем вводить политику общения на английском, если разработчики не могут в него? до такой степени, что нужно угадывать контекст, чтобы расшифровать, что здесь написано.

**Comment by collectioner** [comment]
Потому что проект международный. Комментарии не по теме issue будут удаляться.

**Comment by Xottab-DUTY** [comment]
Ну, ты же угадал контекст?)

В репозитории не может не быть приоритета английского в общении. Гитхаб сайт международный и даже не имеет других языков, кроме английского. Ну, а так как английский – язык международного общения, то мы не хотим себя ограничивать только русскоязычными участниками.

На русском можно общаться в дискорде.

**Comment by uralets** [comment]
я ниразу не призываю снять требование общения на англ. у меня с этим нет проблем.
но что-то делать-то надо?)))
ЗЫ кстати нет не угадал, всё слишком плохо.

PPS to stay on topic - I also experience the issue (like every1 else should ofc). just my 2 cents.

**Comment by eagleivg** [comment]
Fixed at 8f6af2bc195831d35d66e204f91ce249ef97acc1
