### ISSUE TITLE
[Linux] Game is unusably dark. Adjusting Gamma/Brightness/Contrast has no effect.

### ISSUE THREAD

**Issue by uralets** [OpenXRay/xray-16#317]
The game is very dark from the start.
Changing Gamma/Brightness/Contrast controls won't do anything.
Tried setting it from the menu as well as in-game (rs_c_* variables).

Ubuntu 18.04 x64
ATI Radeon HD 7770 (Cape Verde)
radeon driver
<details>
  <summary>glxinfo -B</summary>

```
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: X.Org (0x1002)
    Device: AMD VERDE (DRM 2.50.0, 4.20.0-042000-generic, LLVM 8.0.0) (0x683d)
    Version: 19.0.0
    Accelerated: yes
    Video memory: 1024MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.5
    Max compat profile version: 4.5
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL vendor string: X.Org
OpenGL renderer string: AMD VERDE (DRM 2.50.0, 4.20.0-042000-generic, LLVM 8.0.0)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 19.0.0-devel - padoka PPA
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.5 (Compatibility Profile) Mesa 19.0.0-devel - padoka PPA
OpenGL shading language version string: 4.50
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 19.0.0-devel - padoka PPA
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```
</details>
<details>
  <summary>Libs</summary>

```
xserver-xorg 7.7+19ubuntu7.1
xserver-xorg-core 1.19.6-1ubuntu4.2
libsdl2-2.0-0 2.0.8+dfsg1-1ubuntu1
libglew2.0 2.0.0-5
```
</details>

![2019-01-03 23-43-01](https://user-images.githubusercontent.com/45916341/50656608-9e3ff680-0fb5-11e9-88a4-d027a51bb7b9.png)
![2019-01-03 23-43-28](https://user-images.githubusercontent.com/45916341/50656626-ac8e1280-0fb5-11e9-8971-a8e77ad4a161.png)
![2019-01-03 23-45-58](https://user-images.githubusercontent.com/45916341/50656647-ba439800-0fb5-11e9-8245-d2cd7b5e06f4.png)

**Comment by uralets** [comment]
Maybe I'm being too simplistic in my quick investigation here, but is brightness setting even hooked into the OpenGL renderer? (UPD: acc to IRC/discord no, it's not...)

xray-16$ **ag setbrightness**
```
src/xrEngine/Render.h
393:    virtual void setBrightness(float fGamma) = 0;

src/xrEngine/xr_ioc_cmd.cpp
482:        GEnv.Render->setBrightness(ps_brightness);

src/Layers/xrRender/r__dsgraph_build.cpp
767:void D3DXRenderBase::setBrightness(float fGamma)

src/Layers/xrRender/D3DXRenderBase.h
182:    virtual void setBrightness(float fGamma) override;
```
xray-16$ **ag brightness|grep -i dx**
```
src/Layers/xrRender/r__dsgraph_build.cpp:767:void D3DXRenderBase::setBrightness(float fGamma)
src/Layers/xrRender/D3DXRenderBase.h:182:    virtual void setBrightness(float fGamma) override;
```
xray-16$ **ag brightness|grep -i sdl**
```
src/xrGame/key_binding_registrator_script.cpp:345:                value("DIK_BRIGHTNESSDOWN", int(SDL_SCANCODE_BRIGHTNESSDOWN)),
src/xrGame/key_binding_registrator_script.cpp:346:                value("DIK_BRIGHTNESSUP", int(SDL_SCANCODE_BRIGHTNESSUP)),
src/xrEngine/xr_input_xinput.cpp:399:    { "kBRIGHTNESSDOWN",        SDL_SCANCODE_BRIGHTNESSDOWN,     "Brightness Down" },
src/xrEngine/xr_input_xinput.cpp:400:    { "kBRIGHTNESSUP",          SDL_SCANCODE_BRIGHTNESSUP,       "Brightness Up" },
```

**Comment by SkyLoaderr** [comment]
You can try to use -no_vtf key and check it again.

**Comment by uralets** [comment]
(why email replies won't appear here?)
=====================================
sorry no effect

is there even such a switch?
grep -i vtf xr_3da
returns nothing

unless it was added pretty recently, I haven't pulled for a while. 
=====================================

PS built on the latest commit - now it just crashes after PRESSING ANY KEY on the loading screen (with or w/o the switch)

**Comment by Xottab-DUTY** [comment]
The bug should be fixed for a quite some time ago now.
