### ISSUE TITLE
LuaJit replace on a compiled dll

### ISSUE THREAD

**Issue by alexgdi** [OpenXRay/xray-16#33]
[Google Translate] I analyzed the source code LuaJit. There's only one slight change. Maybe we should bring this LuaJit project as a separate library compiled dll? This will allow the library to make updates to newer versions.

**Comment by nitrocaster** [comment]
Could you provide a diff that shows that change?

**Comment by alexgdi** [comment]
changes.txt
http://rghost.ru/8khLKkDBb

**Comment by nitrocaster** [comment]
Next time use [GitHub Gist](https://gist.github.com/), please.

**Comment by nitrocaster** [comment]
Well, I don't see any functional changes there. We can remove luajit from the source control and add it as git submodule.

**Comment by Xottab-DUTY** [comment]
If you haven't seen it, I recommend you look at this repository: https://github.com/avoitishin/xray-16 (branch "working"). In this repo LuaJIT already updated to version 2.1-alpha.

**Comment by nitrocaster** [comment]
LuaJIT updated to 2.0.4 and now included as submodule.
