### ISSUE TITLE
Shader folder not found

### ISSUE THREAD

**Issue by ghost** [OpenXRay/xray-16#333]
Hello,

I just compiled the engine on Ubuntu without errors (and ran make install)
I reinstalled CoP to try it out (I play CoC normally), but I cannot get the game to run - it halts with a fatal error:

```
[error] Expression    : folder
[error] Function      : LS_Load
[error] File          : /junk/downloads/xray-16/src/Layers/xrRenderPC_GL/glResourceManager_Scripting.cpp
[error] Line          : 417
[error] Description   : Shader folder not found: 
[error] Arguments     : gl\
```
Did I miss something?

**Comment by ChugunovRoman** [comment]
Same problem.
As I understand it, I need found shader for OpenGL and put them into gamedata/shaders/gl ?
But I don't know where I can find this shader :(

**Comment by Xottab-DUTY** [comment]
You could just lurk a bit this repo..
https://github.com/OpenXRay/xray-16/tree/xd_dev/res

**Comment by ChugunovRoman** [comment]
Thx! The CoP works fine on Ubuntu 18.04.2! ))
But, can I play on any mods for CoP?

**Comment by ChugunovRoman** [comment]
I installed the "Долина Шорохов" mod, and when I try to run by command:
```bash
./xr_3da.sh -fsltx ../fsgame.ltx
```
<details>
  <summary>I got next log:</summary>
  Couldn't create surface from image: Couldn't open logo.bmp
OpenXRay Rx64 build 7335, Mar  7 2019
Custom build from commit[6d5aee2bf0f26fe8463e93afe0dbf6be37bd885e] branch[xd_dev]
 
command line -fsltx ../fsgame.ltx 

* CPU features: RDTSC, MMX, SSE, SSE2, SSE3, SSE4.1, SSE4.2, AVX, AVX2
* CPU cores/threads: 8/8
* CPU current freq: 1154 MHz

Initializing File System...
using fs-ltx ../fsgame.ltx
FS: 43723 files cached 28 archives, 11Kb memory used.
Init FileSystem 0.293621 sec
-----loading \media\dick1\home\ruut\stalker\CoP\gamedata\configs\system.ltx
-----loading \media\dick1\home\ruut\stalker\CoP\gamedata\configs\system.ltx
Starting INPUT device...
Loading module: xrRender_GL
Available render modes[2]:
renderer_gl
Executing config-script "user.ltx"...
[\media\dick1\home\ruut\stalker\CoP\_appdata_\user.ltx] successfully loaded.
Initializing Engine...
Loading module: xrGame
Executing config-script "\media\dick1\home\ruut\stalker\CoP\gamedata\configs\default_controls.ltx"...
! Can't find a key name for kPOWER
! Can't find a key name for kF13
! Can't find a key name for kF14
! Can't find a key name for kF15
! Can't find a key name for kF16
! Can't find a key name for kF17
! Can't find a key name for kF18
! Can't find a key name for kF19
! Can't find a key name for kCUT
! Can't find a key name for kCOPY
! Can't find a key name for kPASTE
! Can't find a key name for kMUTE
! Can't find a key name for kVOLUMEUP
! Can't find a key name for kVOLUMEDOWN
! Can't find a key name for kINTERNATIONAL1
! Can't find a key name for kINTERNATIONAL2
! Can't find a key name for kYEN
! Can't find a key name for kINTERNATIONAL4
! Can't find a key name for kINTERNATIONAL5
! Can't find a key name for kINTERNATIONAL6
! Can't find a key name for kINTERNATIONAL7
! Can't find a key name for kINTERNATIONAL8
! Can't find a key name for kINTERNATIONAL9
! Can't find a key name for kHANGUL
! Can't find a key name for kHANJA
! Can't find a key name for kKATAKANA
! Can't find a key name for kHIRAGANA
! Can't find a key name for kZENHANKAKU
! Can't find a key name for kLANG6
! Can't find a key name for kLANG7
! Can't find a key name for kLANG8
! Can't find a key name for kLANG9
! Can't find a key name for kAUDIONEXT
! Can't find a key name for kAUDIOPREV
! Can't find a key name for kAUDIOSTOP
! Can't find a key name for kAUDIOPLAY
! Can't find a key name for kMEDIASELECT
! Can't find a key name for kWWW
! Can't find a key name for kMAIL
! Can't find a key name for kCALCULATOR
! Can't find a key name for kCOMPUTER
! Can't find a key name for kNUMPAD_AC_SEARCH
! Can't find a key name for kNUMPAD_AC_HOME
! Can't find a key name for kNUMPAD_AC_BACK
! Can't find a key name for kNUMPAD_AC_FORWARD
! Can't find a key name for kNUMPAD_AC_REFRESH
! Can't find a key name for kNUMPAD_AC_BOOKMARKS
! Can't find a key name for kBRIGHTNESSDOWN
! Can't find a key name for kBRIGHTNESSUP
! Can't find a key name for kDISPLAYSWITCH
! Can't find a key name for kKBDILLUMTOGGLE
! Can't find a key name for kKBDILLUMDOWN
! Can't find a key name for kKBDILLUMUP
! Can't find a key name for kEJECT
! Can't find a key name for kSLEEP
! Can't find a key name for kAPP1
! Can't find a key name for kAPP2
[\media\dick1\home\ruut\stalker\CoP\gamedata\configs\default_controls.ltx] successfully loaded.
Executing config-script "user.ltx"...
Executing config-script "\media\dick1\home\ruut\stalker\CoP\gamedata\configs\rspec_default.ltx"...
[\media\dick1\home\ruut\stalker\CoP\gamedata\configs\rspec_default.ltx] successfully loaded.
Executing config-script "\media\dick1\home\ruut\stalker\CoP\gamedata\configs\default_controls.ltx"...
[\media\dick1\home\ruut\stalker\CoP\gamedata\configs\default_controls.ltx] successfully loaded.
~ Invalid syntax in call to 'r2_aa_break'
~ Valid arguments: vector3 in range [0.000000e+00,0.000000e+00,0.000000e+00]-[1.000000e+00,1.000000e+00,1.000000e+00]
~ Invalid syntax in call to 'r2_aa_weight'
~ Valid arguments: vector3 in range [0.000000e+00,0.000000e+00,0.000000e+00]-[1.000000e+00,1.000000e+00,1.000000e+00]
~ Invalid syntax in call to 'sv_adm_menu_ban_time'
~ Valid arguments: ui_mp_am_10_minutes/ui_mp_am_30_minutes/ui_mp_am_1_hour/ui_mp_am_6_hours/ui_mp_am_1_day/ui_mp_am_1_week/ui_mp_am_1_month/ui_mp_am_3_monthes/ui_mp_am_forever
~ Invalid syntax in call to 'vid_monitor'
~ Valid arguments: change monitor
~ It's unsafe to set refresh rate for your resolution
[\media\dick1\home\ruut\stalker\CoP\_appdata_\user.ltx] successfully loaded.
SOUND: OpenAL: enumerate devices...
SOUND: OpenAL: EnumerationExtension Present
devices OpenAL Soft
SOUND: OpenAL: system  default SndDevice name is OpenAL Soft
SOUND: OpenAL: All available devices:
1. OpenAL Soft, Spec Version 1.1 (default) eax[0] efx[yes] xram[no]
SOUND: Selected device is OpenAL Soft
* sound: EAX 2.0 extension: absent
* sound: EAX 2.0 deferred: absent
* sound : cache: 65537 kb, 4856 lines, 13820 bpl
Starting RENDER device...
* GPU vendor: [NVIDIA Corporation] device: [GeForce GTX 1050 Ti/PCIe/SSE2]
* GPU OpenGL version: 4.1.0 NVIDIA 390.116
* GPU OpenGL shading language version: 4.10 NVIDIA via Cg compiler
* GPU OpenGL VTF units: [32] CTI units: [192]
* DVB created: 4096K
* DIB created: 512K
! Renderer doesn't support blender 'effects\shadow_world'
 
FATAL ERROR
 
[error] Expression    : <no expression>
[error] Function      : handler_base
[error] File          : /home/ruut/otherProjects/xray-16/src/xrCore/xrDebug.cpp
[error] Line          : 781
[error] Description   : segmentation fault
 

stack trace:

/media/dick1/home/ruut/stalker/CoP/bin/xrCore.so(_ZN7xrDebug10GatherInfoEPcmRK13ErrorLocationPKcS5_S5_S5_+0x1f0) [0x7f949c7a7440]
/media/dick1/home/ruut/stalker/CoP/bin/xrCore.so(_ZN7xrDebug4FailERbRK13ErrorLocationPKcS5_S5_S5_+0x8a) [0x7f949c7a760a]
/media/dick1/home/ruut/stalker/CoP/bin/xrCore.so(+0x3eb17) [0x7f949c7a7b17]
/lib/x86_64-linux-gnu/libc.so.6(+0x3ef20) [0x7f949bae5f20]
/media/dick1/home/ruut/stalker/CoP/bin/xrCore.so(_ZN7IReader10find_chunkEjPi+0x27) [0x7f949c78c7e7]
/media/dick1/home/ruut/stalker/CoP/bin/xrRender_GL.so(+0x13f88f) [0x7f948ac5988f]
/media/dick1/home/ruut/stalker/CoP/bin/xrRender_GL.so(+0x13fb9c) [0x7f948ac59b9c]
/usr/lib/x86_64-linux-gnu/libtbb.so.2(+0x26b46) [0x7f9499f00b46]
/media/dick1/home/ruut/stalker/CoP/bin/xrRender_GL.so(+0x13e9f5) [0x7f948ac589f5]
/usr/lib/x86_64-linux-gnu/libtbb.so.2(+0x26b46) [0x7f9499f00b46]
/media/dick1/home/ruut/stalker/CoP/bin/xrRender_GL.so(+0x13f290) [0x7f948ac59290]
/media/dick1/home/ruut/stalker/CoP/bin/xrRender_GL.so(+0x13f390) [0x7f948ac59390]
/media/dick1/home/ruut/stalker/CoP/bin/xrRender_GL.so(+0x118636) [0x7f948ac32636]
/media/dick1/home/ruut/stalker/CoP/bin/xrRender_GL.so(+0x1187be) [0x7f948ac327be]
/media/dick1/home/ruut/stalker/CoP/bin/xrRender_GL.so(+0xbfc97) [0x7f948abd9c97]
/media/dick1/home/ruut/stalker/CoP/bin/xrEngine.so(_ZN13CRenderDevice6CreateEv+0x1ab) [0x7f949cceea3b]
/media/dick1/home/ruut/stalker/CoP/bin/xrEngine.so(_Z7Startupv+0xab) [0x7f949cd56f3b]
/media/dick1/home/ruut/stalker/CoP/bin/xrEngine.so(_Z14RunApplicationv+0xd7) [0x7f949cd57ad7]
/media/dick1/home/ruut/stalker/CoP/bin/xr_3da(+0x1673) [0x559f64556673]
/media/dick1/home/ruut/stalker/CoP/bin/xr_3da(+0x129f) [0x559f6455629f]
Trace/breakpoint trap (core dumped)
</details>
