### ISSUE TITLE
--std=c++17 trash

### ISSUE THREAD

**Issue by grandmaster8** [OpenXRay/xray-16#342]
https://github.com/OpenXRay/xray-16/blob/edef4df84555a4d37afa94ded0e99ff64c9ce11e/CMakeLists.txt#L71

Используйте set(CMAKE_CXX_STANDARD 17)

**Comment by eagleivg** [comment]
Кажется, с CMAKE_CXX_STANDARD была какая-то шляпа - он подключал гнутые расширения и это ломало сборку.

**Comment by grandmaster8** [comment]
не может быть такого.

**Comment by grandmaster8** [comment]
надо исправлять

**Comment by danfe** [comment]
А в чем вообще великий смысл собирать с `--std=c++=17` (при том, что части проекта собираются с `--std=c++14`)?  Например, из-за того, что в C++17 убрали `std::random_shuffle()`, который до этого был просто deprecated, сейчас код не собирается цлангом 7.0.1 без такого патча:
```diff
--- Externals/ode/ode/src/quickstep.cpp.orig
+++ Externals/ode/ode/src/quickstep.cpp
@@ -33,7 +33,8 @@
 #include "util.h"
 #include "stdlib.h"

-#include <algorithm>
+//#include <algorithm>
+#include <random>



@@ -425,7 +426,9 @@ static void SOR_LCP (int m, int nb, dRealMutablePtr J,
 #endif
 #ifdef RANDOMLY_REORDER_CONSTRAINTS
                if ((iteration & 3) == 0) {
-                       std::random_shuffle     (order,order+m);
+                       std::random_device rng;
+                       std::mt19937 urng(rng());
+                       std::shuffle(order, order + m, urng);
                        /*
                        for (i=1; i<m; ++i) {
                                IndexError tmp = order[i];

```
Я так понимаю, C++17 нужен для `std::is_base_of_v`, но неужели это насколько нужная штука?  Или 14-я версия (и более ранние) не устраивают по каким-то другим причинам?

**Comment by kacejot** [comment]
@danfe, да, это нужная штука, очень красивая и удобная. Поддержка последних стандартов - неотъемлемая часть rolling проектов. Если часть проекта уже использует 17ый стандарт, то следует добиться полной его компиляции с этим стандартом. 

P.S. Планируется ли редизайн под модули из C++20?
