### ISSUE TITLE
OpenXRay 221 issues with sight attachments from weapon mods.

### ISSUE THREAD

**Issue by dyharlan** [OpenXRay/xray-16#358]
When using the multitool from AO3.1, the game crashes after removing the attachments from the weapon. Thus preventing the use of scopes and red dot sights. Grenade Launchers and Silencers aren't affected. With STCoP, sights don't work properly at all, even with the oxr specific version installed. Dropped weapons with scopes are permanent and, "using" scopes from inventory only makes it disappear.

Attached are the logs from AO3.1 bug. 
[XRayEngine_error_report_190215-113207.zip](https://github.com/OpenXRay/xray-16/files/2867756/XRayEngine_error_report_190215-113207.zip)

**Comment by ShokerStlk** [comment]
It's a script bug, not engine one (wonder how it even work before). Add this line to gamedata\scripts\m_wpn_addons.script

![image](https://user-images.githubusercontent.com/17707013/53523809-d44db280-3aee-11e9-9c75-1797033d9537.png)
