### ISSUE TITLE
Game crashes when moving medicine from inventory to personal container

### ISSUE THREAD

**Issue by IriaSomobu** [OpenXRay/xray-16#365]
**Problem**: see title
**Log**: [XRayEngine_error_report_190301-235937.zip](https://github.com/OpenXRay/xray-16/files/2921885/XRayEngine_error_report_190301-235937.zip)
**Savegame**: [medicine stocking bug.zip](https://github.com/OpenXRay/xray-16/files/2921883/medicine.stocking.bug.zip)
**Video**: [on youtube](https://youtu.be/D373GMUyuB0)
**Game**: Stalker COP 1.6.0.2 with OpenXRay 221 Rx64

**Comment by Xottab-DUTY** [comment]
This happens on existing CoP gamesave, or you had started a new game after installing OpenXRay?

It is required to start a new game after installing OpenXRay.

**Comment by IriaSomobu** [comment]
This happens on existing CoP savegame.

OK, I'll check this issue on new game.

**Comment by IriaSomobu** [comment]
So looks like this problem is gone after clean new game.
