### ISSUE TITLE
A huge framerate in video and whistle videocard

### ISSUE THREAD

**Issue by justtails** [OpenXRay/xray-16#366]
Videocard whistle on a huge framerate in in-game video with **rs_fullscreen 0** option (in "fullscreen on" mode without vsync the problem is the same) . On screenshot you see about 1600 FPS, but it's a mixed build. In release build I saw about 2000 or 3000 FPS. It isn't normal. Videocard whistle like a b*tch in this moment 😄 
Can you fix it or set locked framerate?
Configuration:
- **Pentium G4600** 3,6GHz
- GeForce **GTX 1050 Ti**
- OpenXRay **Mixed x64** from repo with latest commits
- **Fullscreen Off**

![openxray_over9000fps](https://user-images.githubusercontent.com/42806009/53682520-ab543a00-3d07-11e9-9443-0c5942247829.png)

**Comment by katastic** [comment]
Is this Windows or Linux? Have you tried turning VSYNC on inside the game? Force VSYNC in the GeForce panel? Additionally, you should be able to use to force your GeForce to remain underclocked / low-power-mode using MSI Afterburner. This will prevent the heat that engages the fans.

**Comment by justtails** [comment]
> Is this Windows or Linux?

This is on Windows, but I think, Linux have that problem too.
> Have you tried turning VSYNC on inside the game?

Of course. It makes no sense to say about problem without turning VSYNC on inside the game.
> Force VSYNC in the GeForce panel?

Nope. But i know about panel functionality.

Dude, I'm not a noob in PC. If you can help to fix it in the source code, just make a pull request. I don't need to fix my PC : )

**Comment by Xottab-DUTY** [comment]
Fixed with de9362d115506ee79cd35c00cae4a6501fefe12f
