### ISSUE TITLE
Endless cutscene in 'chimera hunt' quest on Zaton

### ISSUE THREAD

**Issue by IriaSomobu** [OpenXRay/xray-16#367]
**Savegame**: [chimera hunt.zip](https://github.com/OpenXRay/xray-16/files/2922200/chimera.hunt.zip)
**Video**: [on youtube](https://youtu.be/eK0odSPkyV0)
**Game**: Stalker COP 1.6.0.2 with OpenXRay 221 Rx64

**Comment by Xottab-DUTY** [comment]
This is reaallly old.
