### ISSUE TITLE
Crash into BugTrap on clicking 'Options'

### ISSUE THREAD

**Issue by IriaSomobu** [OpenXRay/xray-16#391]
Version: 221 Rx64

[XRayEngine_error_report_190426-150124.zip](https://github.com/OpenXRay/xray-16/files/3121830/XRayEngine_error_report_190426-150124.zip)

Steps:
1. Start new game;
Skip intro and walk forward, to the edge of starting plato
2. Open extended graphics settings
3. Change (max to low or vice versa) this settings at once: grass denisity, grass radius, anti-aliasing, wetness near and far and wetness quality
4. Try to apply
5. Game freezes or crashes

**Comment by Xottab-DUTY** [comment]
Log says:
> Not enough memory resources are available to process this command.

What amount of RAM you have?

**Comment by IriaSomobu** [comment]
8gb

**Comment by LVutner** [comment]
Looks like that error is related to secondary viewport in xrEngine.

**Comment by Xottab-DUTY** [comment]
@iillyyaa2033, can you confirm this crash on the latest build?

**Comment by IriaSomobu** [comment]
No. I cannot make game crash after applying extended settings.

But game still freezes when you hit 'Apply' button: 'Do u wanna apply' dialog shown, but in-game mouse cursor stopped working and you can see and move default windows cursor. After 1..20s everything unfreezes and you can confirm this dialog.

**Comment by Xottab-DUTY** [comment]
Freeze is normal, because renderer restarts.

P.S. @MonoLityczny, this is not related to second viewport.

**Comment by Xottab-DUTY** [comment]
So, it seems that crash doesn't happen now, it's reasonable to close this issue. @iillyyaa2033, thanks for the assistance.
