### ISSUE TITLE
Compile error in recent git commit

### ISSUE THREAD

**Issue by vpelcak** [OpenXRay/xray-16#396]
$ CFLAGS="-march=native" CXXFLAGS="-march=native" cmake ..
$ make
...
[  9%] Building CXX object src/utils/xrMiscMath/CMakeFiles/xrMiscMath.dir/vector.cpp.o
In file included from /home/vita/!files/programy/xray-16/src/utils/xrMiscMath/../../xrCore/vector.h:23,
                 from /home/vita/!files/programy/xray-16/src/utils/xrMiscMath/vector.cpp:3:
/home/vita/!files/programy/xray-16/src/utils/xrMiscMath/../../xrCore/_color.h: In function ‘constexpr u32 color_argb_f(f32, f32, f32, f32)’:
/home/vita/!files/programy/xray-16/src/utils/xrMiscMath/../../xrCore/_color.h:35:34: error: call to non-‘constexpr’ function ‘int iFloor(float)’
     s32 _r = clamp_to_8bit(iFloor(r*255.f));
                            ~~~~~~^~~~~~~~~
make[2]: *** [src/utils/xrMiscMath/CMakeFiles/xrMiscMath.dir/build.make:178: src/utils/xrMiscMath/CMakeFiles/xrMiscMath.dir/vector.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:947: src/utils/xrMiscMath/CMakeFiles/xrMiscMath.dir/all] Error 2

**Comment by eagleivg** [comment]
Unfortunately, while the build is only available for gcc5 - gcc7, earlier or later versions may give errors. Patches are welcome!

**Comment by vpelcak** [comment]
Sorry, I'm not a programmer to help with this.
In the new commit the issue is gone but there is another one.

/home/vita/!files/programy/xray-16/src/xrGame/ui/FactionState.cpp: In constructor ‘FactionState::FactionState(const shared_str&)’:
/home/vita/!files/programy/xray-16/src/xrGame/ui/FactionState.cpp:39:22: error: cannot call constructor ‘FactionState::FactionState’ directly
  this->FactionState::FactionState();
                      ^~~~~~~~~~~~
make[2]: *** [src/xrGame/CMakeFiles/xrGame.dir/build.make:23825: src/xrGame/CMakeFiles/xrGame.dir/ui/FactionState.cpp.o] Error 1

**Comment by vpelcak** [comment]
I commented out:

//FactionState::FactionState( shared_str const& id )
//{
//      this->FactionState::FactionState();
//      set_faction_id2( id );
//}

in src/xrGame/ui/FactionState.cpp

But then I ran into following errors:

[ 45%] Building CXX object src/xrGame/CMakeFiles/xrGame.dir/ui/UIHelper.cpp.o
/home/vita/!files/programy/xray-16/src/xrGame/ui/UIHelper.cpp:111:60: error: macro "R_ASSERT" passed 2 arguments, but takes just 1
         R_ASSERT(!critical, "Failed to create progress bar");
                                                            ^
/home/vita/!files/programy/xray-16/src/xrGame/ui/UIHelper.cpp:131:62: error: macro "R_ASSERT" passed 2 arguments, but takes just 1
         R_ASSERT(!critical, "Failed to create progress shape");
                                                              ^
/home/vita/!files/programy/xray-16/src/xrGame/ui/UIHelper.cpp:151:58: error: macro "R_ASSERT" passed 2 arguments, but takes just 1
         R_ASSERT(!critical, "Failed to create frame line");
                                                          ^
/home/vita/!files/programy/xray-16/src/xrGame/ui/UIHelper.cpp:171:60: error: macro "R_ASSERT" passed 2 arguments, but takes just 1
         R_ASSERT(!critical, "Failed to create frame window");
                                                            ^
/home/vita/!files/programy/xray-16/src/xrGame/ui/UIHelper.cpp: In static member function ‘static CUIProgressBar* UIHelper::CreateProgressBar(CUIXml&, LPCSTR, CUIWindow*, bool)’:
/home/vita/!files/programy/xray-16/src/xrGame/ui/UIHelper.cpp:111:9: error: ‘R_ASSERT’ was not declared in this scope
         R_ASSERT(!critical, "Failed to create progress bar");
         ^~~~~~~~
/home/vita/!files/programy/xray-16/src/xrGame/ui/UIHelper.cpp: In static member function ‘static CUIProgressShape* UIHelper::CreateProgressShape(CUIXml&, LPCSTR, CUIWindow*, bool)’:
/home/vita/!files/programy/xray-16/src/xrGame/ui/UIHelper.cpp:131:9: error: ‘R_ASSERT’ was not declared in this scope
         R_ASSERT(!critical, "Failed to create progress shape");
         ^~~~~~~~
/home/vita/!files/programy/xray-16/src/xrGame/ui/UIHelper.cpp: In static member function ‘static CUIFrameLineWnd* UIHelper::CreateFrameLine(CUIXml&, LPCSTR, CUIWindow*, bool)’:
/home/vita/!files/programy/xray-16/src/xrGame/ui/UIHelper.cpp:151:9: error: ‘R_ASSERT’ was not declared in this scope
         R_ASSERT(!critical, "Failed to create frame line");
         ^~~~~~~~
/home/vita/!files/programy/xray-16/src/xrGame/ui/UIHelper.cpp: In static member function ‘static CUIFrameWindow* UIHelper::CreateFrameWindow(CUIXml&, LPCSTR, CUIWindow*, bool)’:
/home/vita/!files/programy/xray-16/src/xrGame/ui/UIHelper.cpp:171:9: error: ‘R_ASSERT’ was not declared in this scope
         R_ASSERT(!critical, "Failed to create frame window");
         ^~~~~~~~
make[2]: *** [src/xrGame/CMakeFiles/xrGame.dir/build.make:24825: src/xrGame/CMakeFiles/xrGame.dir/ui/UIHelper.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1900: src/xrGame/CMakeFiles/xrGame.dir/all] Error 2

**Comment by Xottab-DUTY** [comment]
Oh, ...! It's my bad again. I always forget to set 2, 3 or 4 when I specify more than one argument to `R_ASSERT`, sorry 😃 
Please, replace `R_ASSERT` with `R_ASSERT2`
And, instead of commenting entire function, only comment one line of it:
```cpp
FactionState::FactionState( shared_str const& id )
{
    //this->FactionState::FactionState();
    set_faction_id2( id );
}
```

**Comment by vpelcak** [comment]
That helped.

Thank you.

Now it is:
/home/vita/!files/programy/xray-16/src/xrGame/ui/UIRankFaction.cpp:8:10: fatal error: stdafx.h: Adresář nebo soubor neexistuje
 #include "stdafx.h"
          ^~~~~~~~~~
compilation terminated.

**Comment by vpelcak** [comment]
Sorry.

/home/vita/!files/programy/xray-16/src/xrGame/ui/UIRankFaction.cpp:8:10: fatal error: stdafx.h: No such a file or directory
 #include "stdafx.h"
          ^~~~~~~~~~
compilation terminated.

**Comment by Xottab-DUTY** [comment]
Replace `stdafx.h` with `StdAfx.h` 😉

**Comment by vpelcak** [comment]
All works.
Thank you.

**Comment by Xottab-DUTY** [comment]
Yay! That's nice)

But until compilation isn't fixed in the repository, we should leave this issue open.

**Comment by vpelcak** [comment]
For sure

**Comment by vpelcak** [comment]
Hello.

More issues appeared in recent git:
[ 10%] Building CXX object src/xrCore/CMakeFiles/xrCore.dir/xrDebug.cpp.o
/home/vita/!files/programy/xray-16/src/xrCore/xrDebug.cpp: In static member function ‘static void xrDebug::DoExit(const string&)’:
/home/vita/!files/programy/xray-16/src/xrCore/xrDebug.cpp:593:9: error: ‘IsDebuggerPresent’ was not declared in this scope
     if (IsDebuggerPresent())
         ^~~~~~~~~~~~~~~~~
/home/vita/!files/programy/xray-16/src/xrCore/xrDebug.cpp:593:9: note: suggested alternative: ‘SDL_RenderPresent’
     if (IsDebuggerPresent())
         ^~~~~~~~~~~~~~~~~
         SDL_RenderPresent
/home/vita/!files/programy/xray-16/src/xrCore/xrDebug.cpp: In static member function ‘static void xrDebug::OnFilesystemInitialized()’:
/home/vita/!files/programy/xray-16/src/xrCore/xrDebug.cpp:727:9: error: ‘BT_SetReportFilePath’ was not declared in this scope
         BT_SetReportFilePath(dumpPath);
         ^~~~~~~~~~~~~~~~~~~~
/home/vita/!files/programy/xray-16/src/xrCore/xrDebug.cpp:727:9: note: suggested alternative: ‘BugReportFile’
         BT_SetReportFilePath(dumpPath);
         ^~~~~~~~~~~~~~~~~~~~
         BugReportFile
make[2]: *** [src/xrCore/CMakeFiles/xrCore.dir/build.make:753: src/xrCore/CMakeFiles/xrCore.dir/xrDebug.cpp.o] Chyba 1
make[1]: *** [CMakeFiles/Makefile2:1662: src/xrCore/CMakeFiles/xrCore.dir/all] Chyba 2
make: *** [Makefile:130: all] Chyba 2

**Comment by Xottab-DUTY** [comment]
Thank you! Should be ok now 😃
