### ISSUE TITLE
segmentation fault right at the start - latest git

### ISSUE THREAD

**Issue by vpelcak** [OpenXRay/xray-16#398]
./xr_3da.sh -fsltx ../fsgame.ltx
! Failed to copy text to the clipboard: Video subsystem must be initialized to set clipboard text
 
FATAL ERROR
 
[error] Expression    : <no expression>
[error] Function      : handler_base
[error] File          : /home/vita/!files/programy/xray-16/src/xrCore/xrDebug.cpp
[error] Line          : 855
[error] Description   : segmentation fault
 

./xr_3da.sh: line 29: 12177 (SIGTRAP)          ${DEBUGGER} "${GAMEROOT}"/"${GAMEEXE}" "$@"

**Comment by johndoe71rus** [comment]
Let's check a guess
go to xray-16/Externals/LuaJIT/
run make
copy xray-16/Externals/LuaJIT/src/libluajit.so to the game folder. or rename to libluajit-debug.so if you run debug version

**Comment by vpelcak** [comment]
I moved it to bin-linux and problem is still there

**Comment by vpelcak** [comment]
I did a clean install and now it works fine.
