### ISSUE TITLE
gamedata/configs/default_controls.ltx missing

### ISSUE THREAD

**Issue by vpelcak** [OpenXRay/xray-16#399]
Hello.

When starting STALKER, I get errors like:
Executing config-script "\mnt\Programy\Games\S.T.A.L.K.E.R. - Call of Pripyat - Linux\gamedata\configs\default_controls.ltx"...
! Can't find a key name for kUNKNOWN
! Can't find a key name for kPOWER
! Can't find a key name for kF13
! Can't find a key name for kF14
! Can't find a key name for kF15
! Can't find a key name for kF16
! Can't find a key name for kF17
! Can't find a key name for kF18

It is because gamedata/configs/default_controls.ltx doesn't exist at all.

**Comment by vpelcak** [comment]
And yet I get false negative message:
gamedata\configs\default_controls.ltx] successfully loaded.

**Comment by Xottab-DUTY** [comment]
Nope, default_controls.ltx exist in the game archives and the message is not false.
These errors happen because SDL don't have names for mentioned keys.
