### ISSUE TITLE
Get Dedicated Server Running

### ISSUE THREAD

**Issue by awdavies** [OpenXRay/xray-16#4]
Dedicated server appears to crash when run with _Debug_ configuration.  From @nitrocaster the following log output is common:

```
"ID3DDepthStencilState #%d created"
```

And may be of use. 

When posting debug logs, please use some paste service like pastebin, please.

**Comment by awdavies** [comment]
@nitrocaster uses the following batch script to run the dedi:

```
@echo off
dedicated\xrEngine.exe -i -nosound -fsltx ..\fsgame_dbg.ltx -start
server(mp_training_camp/dm/public=1/hname=test/psw=009/maxplayers=16/reinf=15/battleye_update=0/estime=9:00/etimef=0/vote=255/spectrmds=30/fraglimit=555/timelimit=0/dmgblock=4/dmbi=0/ans=0/anslen=3/warmup=0/pdahunt=1/abalance=0/aswap=1/fn=1/ffire=0.0/portgs=5401/portsv=5400)
client(localhost/portcl=5402/name=ServerAdmin)
```

**Comment by nitrocaster** [comment]
> "ID3DDepthStencilState #%d created"

That's unrelated to dedicated server.

If you've got it crashed, post log here, pls.

**Comment by nitrocaster** [comment]
Anyway, here's the crash I mean:

> Loading DLL: xrGameSpy.dll
> xrGS::xrGS_qr2_initA returned code is [0]
> xrGS::QR2 : Initialized
> 
> FATAL ERROR
> 
> [error]Expression    : assertion failed
> [error]Function      : CObjectFactory::item
> [error]File          : e:\git\xray-16\src\xrserverentities\object_factory_inline.h
> [error]Line          : 63
> [error]Description   : (I != clsids().end()) && ((*I)->clsid() == clsid)

I've debugged it and here's what I've found:
When the engine is loading, it registers all game object classes by calling CObjectFactory::register_classes function.
Here we're interested in this line:

> ADD(CHangingLamp, CSE_ALifeObjectHangingLamp, CLSID_OBJECT_HLAMP, "hanging_lamp");

CLSID_OBJECT_HLAMP macro is defined in xrServerEntities/clsid_game.h:

> #define CLSID_OBJECT_HLAMP MK_CLSID('O','_','H','L','A','M','P',' ')

However, if we take a look at gamedata/configs/system.ltx, we'll find that object 'lights_hanging_lamp' uses slightly altered clsid:

> [lights_hanging_lamp]
> GroupControlSection = spawn_group
> $spawn        = "physics\hanging lamp"
> class       = SO_HLAMP
> script_binding      = bind_physic_object.init

So when server tries to spawn 'lights_hanging_lamp' object it just can't find 'O_HLAMP' clsid because 'SO_HLAMP' was loaded instead.

The question is how did it work in original release. I just have no idea.

**Comment by nitrocaster** [comment]
I've tested dedicated server with fixed system.ltx - works good. Going to push VS2013 solution soon.

**Comment by nitrocaster** [comment]
I'll fix that soon.

**Comment by awdavies** [comment]
Excellent!

**Comment by ShokerStlk** [comment]
This issue need to be opened again to find a better solution.

**Comment by nitrocaster** [comment]
Reopened.

**Comment by Xottab-DUTY** [comment]
> FATAL ERROR
> 
> [error]Expression    : assertion failed
> [error]Function      : CObjectFactory::item
> [error]File          : e:\git\xray-16\src\xrserverentities\object_factory_inline.h
> [error]Line          : 63
> [error]Description   : (I != clsids().end()) && ((*I)->clsid() == clsid)

Dedicated server works, but the failed assertion still persist on Mixed and Debug configurations.
It's possible, that this problem was even in original engine, but was hidden.

Definitely it should be fixed, but however, as I said, dedicated server works.
