### ISSUE TITLE
Project (Engine) logo design-redisgn?

### ISSUE THREAD

**Issue by Ridten** [OpenXRay/xray-16#400]
How about to refresh project logo? I totally not a designer, but made for start dark and light sample. What do you think? Maybe make contest for new look?

![OpenXrayLogo-Dark](https://user-images.githubusercontent.com/10984003/57954229-a197a700-78f2-11e9-90c8-35ad60aee78b.png)
![OpenXrayLogo-Light](https://user-images.githubusercontent.com/10984003/57954239-a65c5b00-78f2-11e9-8886-a69278979524.png)

**Comment by Xottab-DUTY** [comment]
@OpenXRay what do you think?

I believe that logo should have `X` and `X-Ray` as in the current logo and basically, the new logo should just be a redesign of the old logo, so that we can firmly say: this is X-Ray, but much improved and open source.

**Comment by lonelyfootpad** [comment]
Is the current logo somewhere for reference? I'd be keen to have a go at creating a logo.

**Comment by Xottab-DUTY** [comment]
Logo that we currently use for OpenXRay:
![image](https://user-images.githubusercontent.com/2989212/57955473-7d968e80-790f-11e9-8807-12e0589ff431.png)

Full original X-Ray logotypes:
![X-ray_logo](https://user-images.githubusercontent.com/2989212/57955619-cb12fb80-790f-11e9-8ea2-8b1dc8118ec5.jpg)
![X-Ray](https://user-images.githubusercontent.com/2989212/57955580-b7679500-790f-11e9-96cd-298d78bb0aea.png)

**Comment by Xottab-DUTY** [comment]
> I believe that logo should have X and X-Ray as in the current logo

But if it will fit, we should write `OpenXRay` instead of `X-Ray` in new logo.

**Comment by Ridten** [comment]
That's why we need new fresh logo. Nice looking splash for github and icon for discord and executable.

**Comment by Xottab-DUTY** [comment]
Oh sorry me, I totally forgot to send here the logo we currently use along with `X-Ray` logo on our YouTube channel and VK.com social page.
It was drawn by Calciumtrice for OpenXRay.

![watermark](https://user-images.githubusercontent.com/2989212/57964192-a38d5480-794a-11e9-88aa-e2392bbec224.png)

(It's white, you probably won't see anything on GitHub with white background. Open it in a new tab)

**Comment by lonelyfootpad** [comment]
Thanks. I'll start thinking and planning something... anyone else is welcome to do so too of course. I enjoy this sort of thing but don't claim to be good at it. haha.
