### ISSUE TITLE
Warnings in CMAKE setup

### ISSUE THREAD

**Issue by vpelcak** [OpenXRay/xray-16#414]
/xray-16/bin $ CFLAGS="-march=native" CXXFLAGS="-march=native" cmake ..
-- cotire 1.8.0 loaded.
CMake build Release, CFLAGS=-march=native , CXXFLAGS=-march=native -fpermissive --std=c++17 -Wno-attributes -pipe -Wl,--no-undefined -fvisibility=hidden 
-- Found FreeImage: /usr/include, /usr/lib64/libfreeimage.so
-- Found Intel TBB, includes /usr/include, /usr/lib64/libtbb.so;/usr/lib64/libtbbmalloc.so
CMake Warning (dev) at Externals/luajit.cmake:25 (set):
  implicitly converting 'NUMBER' to 'STRING' type.
Call Stack (most recent call first):
  Externals/CMakeLists.txt:1 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at Externals/luajit.cmake:28 (set):
  implicitly converting 'NUMBER' to 'STRING' type.
Call Stack (most recent call first):
  Externals/CMakeLists.txt:1 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at Externals/luajit.cmake:53 (set):
  implicitly converting 'NUMBER' to 'STRING' type.
Call Stack (most recent call first):
  Externals/CMakeLists.txt:1 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at Externals/luajit.cmake:54 (set):
  implicitly converting 'NUMBER' to 'STRING' type.
Call Stack (most recent call first):
  Externals/CMakeLists.txt:1 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at Externals/luajit.cmake:55 (set):
  implicitly converting 'NUMBER' to 'STRING' type.
Call Stack (most recent call first):
  Externals/CMakeLists.txt:1 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at Externals/luajit.cmake:56 (set):
  implicitly converting 'NUMBER' to 'STRING' type.
Call Stack (most recent call first):
  Externals/CMakeLists.txt:1 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at Externals/luajit.cmake:57 (set):
  implicitly converting 'NUMBER' to 'STRING' type.
Call Stack (most recent call first):
  Externals/CMakeLists.txt:1 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Found readline: /usr/lib64/libreadline.so  
-- Found Curses: /usr/lib64/libcurses.so

**Comment by eagleivg** [comment]
what version of cmake do you use?

**Comment by vpelcak** [comment]
Hello.
I have version 3.14.3.

**Comment by Xottab-DUTY** [comment]
Confirming the issue. Log from Travis has this warns too
https://travis-ci.org/OpenXRay/xray-16/jobs/560026445

**Comment by kacejot** [comment]
I have fixed this ones in my fork. I will to create PR without any other changes ASAP.
