### ISSUE TITLE
CRASH on new game

### ISSUE THREAD

**Issue by katastic** [OpenXRay/xray-16#416]
I can't even start a mission. As soon as I click new game, then select a difficulty, it freezes and crashes on loadup. I've tried the latest release in x64 and x86, as well as developer one. I've tried every draw mode (OpenGL, DX11, DX10, and the one right above it the highest DX9 mode.) I tried fullscreen and windowed. I tried 4K and the default 1024x768 resolution.

Fresh ZIP installed over a fresh install of GOG Stalker CoP. I also re-installed COP to be sure.

--------------------

xrEngine.exe caused BREAKPOINT in module "C:\Program Files (x86)\GOG Galaxy\Games\S.T.A.L.K.E.R. Call of Pripyat\bin\xrCore.dll" at 0023:54AA814E, xrDebug::Fail()+478 byte(s)
```

xrDebug:Fail()
xrDebug::Fatal()
.
.
.
IGame_Persistent::Prefetch()+101 bytes

```
[see report]

[XRayEngine_error_report_190616-072034.zip](https://github.com/OpenXRay/xray-16/files/3294089/XRayEngine_error_report_190616-072034.zip)

**Comment by katastic** [comment]
NOW THAT'S INTERESTING.

> 
> Loading objects...
> Loading models...
>  
> FATAL ERROR
>  
> [error] Expression    : <no expression>
> [error] Function      : CModelPool::Instance_Load
> [error] File          : c:\projects\xray-16\src\layers\xrrender\modelpool.cpp
> [error] Line          : 99
> [error] Description   : fatal error
> [error] Arguments     : Can't find model file 'actors\stalker_merc\stalker_merc_sun1.ogf'.

How could I be missing a model?

**Comment by Xottab-DUTY** [comment]
Our engine's filesystem is case sensitive and GOG edition has messed up cases in paths to files. Most likely, this is the reason why it can't find a model.

Basically, you need to check that folders mentioned in `fsgame.ltx` and the folders itself has the same case.

**Comment by Xottab-DUTY** [comment]
I have checked unpacked gamedata from Steam version and there's no `stalker_merc_sun1.ogf` model.
![image](https://user-images.githubusercontent.com/2989212/59564144-c2bbf680-905c-11e9-9b3d-14d8941ffa2b.png)

And this thing becomes a bit strange because you said:
> Fresh ZIP installed over a fresh install of GOG Stalker CoP. I also re-installed COP to be sure.

GOG has some new models? But why it can't find it? Or maybe it's previously installed mod tails that weren't deleted?

**Comment by katastic** [comment]
Well this is incredibly embarrassing but it appears even though I hit delete on my GOG copy, it still had Stalker COP COMPLETE files in it. So apparently GOG doesn't delete mod files when you select uninstall.

**Comment by katastic** [comment]
I deleted everything manually, and reinstalled, and tried Xray, and it works fine. Thank you for your super-quick response.

**Comment by Xottab-DUTY** [comment]
Ok then, I'm glad to that problem is solved 😃
