### ISSUE TITLE
Есть ли гайд по сборке исходников?

### ISSUE THREAD

**Issue by aka-sektor** [OpenXRay/xray-16#420]
Например, такого вида:
Установите Visual Studio 2019 (или выше) и запустите.
Откройте файл xrEngine.sln исходников.
Выберите в панели инструментов: Сборка -> Собрать решение
Предварительно выставите платформу x64, а также конфигурацию Release.

**Comment by Xottab-DUTY** [comment]
Есть же вики и ты уже там был. Как получилось, что ты не увидел там инструкцию?(

Да, вот она:
https://github.com/OpenXRay/xray-16/wiki/%5BRU%5D-Как-собрать-движок-на-Windows

**Comment by aka-sektor** [comment]
Просто. Написано же: Changelist is available in wiki.

Думал там ток изменения.

Вот у OGSR например, сборка сразу на главной.

**Comment by Xottab-DUTY** [comment]
У нас тоже, справа.
![image](https://user-images.githubusercontent.com/2989212/59877088-87a02700-93be-11e9-9da1-70bac5e14e6b.png)

**Comment by Xottab-DUTY** [comment]
Правда, то на английском. Но если есть на английском, то на русском ведь тоже должно быть?)

**Comment by aka-sektor** [comment]
Кстати да, вопрос видимо к тебе, почему русского нету.

**Comment by justtails** [comment]
Тебе перевести сложно?

**Comment by aka-sektor** [comment]
Тут полно тех, кто понимает английский. Странно что русского нет.

Если начну я переводить, могут засмеять.

**Comment by justtails** [comment]
Переводи для себя. Другим и так понятно.

**Comment by Xottab-DUTY** [comment]
Инструкция по сборке на русском есть! А, вот, ридми на английском. Потому что проект международный. Хотя, когда нибудь и оно тоже будет переведено на русский... И не только)

**Comment by aka-sektor** [comment]
Хотелось бы уточнить по исходникам, написано что "Склонируйте репозиторий (но не скачивайте его архивом, нельзя скачивать архивом)". Эт почему нельзя?

> Переводи для себя.

Это лежит только на участниках проекта, как по мне.

**Comment by Xottab-DUTY** [comment]
Потому что используются подмодули, которые не гитхаб не добавляет в архив. Это почти половина папки Externals и без подмодулей, от который движок зависит, он просто не соберётся.

> Это лежит только на участниках проекта, как по мне.

И на неравнодушных людях. Любой может взять и помочь проекту)

**Comment by aka-sektor** [comment]
А вот, собирается же автоматически архив с бинарниками. Почему исходники также не сделать?
Я видел в других проектах есть.

Насчет гайда, чет непонятно. Файл Engine.sln открывать? Как называются платформы? x86, x64 и unix? Конфигурация Release есть?

**Comment by justtails** [comment]
Скажи мне, мил человек, вот ты слепенький или тупенький?
![image](https://user-images.githubusercontent.com/42806009/59878482-15751580-93b1-11e9-8963-e89e97bacf8a.png)

**Comment by aka-sektor** [comment]
Ссылку может дашь, умник?

Я вообще то читал "Archives with debug symbols are named as Symbols.YxZZ.7z (needed only for developers)".

Тут нету слова SOURCES.

Здесь же, есть только: https://ci.appveyor.com/project/OpenXRay/xray-16/build/job/gaey5c6g97a925cr/artifacts
res\Symbols.Rx64.7z

**Comment by Xottab-DUTY** [comment]
@mrnotbadguy, тут ты не прав конечно, бо в тех архивах тоже подмодулей нет.
А делать полностью готовый для сборки архив нет желания и это не нужно.

Это маленький барьер, которым мы успешно огораживаемся от начинающих, которые не знают и не хотят разобраться как работает Git, чтобы элементарно склонировать репозиторий.

**Comment by aka-sektor** [comment]
> барьер

Зря вы это делаете. Ох зря.

> Насчет гайда, чет непонятно. Файл Engine.sln открывать? Как называются платформы? x86, x64 и unix? Конфигурация Release есть?

По этому ответите или как? Заскриньте хоть, как релиз собирается. Как у Оксинген на вики.

**Comment by Xottab-DUTY** [comment]
Барьер легко преодолевается, хотя бы элементарным вопросом о том, как скачать репозиторий.
Мы на такие вопросы отвечаем и помогаем.
> которые не знают и не хотят разобраться как работает Git

Я же говорю, барьер для тех, кто не только не знает, но и не хочет разбираться, а просто хочет готовенькое.

**Comment by Xottab-DUTY** [comment]
> По этому ответите или как? Заскриньте хоть, как релиз собирается. Как у Оксинген на вики.

Да, engine.sln. А скрины-то зачем? Вполне без них хорошо, только лишняя нагрузка.

По конфигурациям, всё есть в ридми:
![image](https://user-images.githubusercontent.com/2989212/59879413-12cfeb80-93c4-11e9-8ee0-3f371593b270.png)

**Comment by justtails** [comment]
[https://github.com/OpenXRay/xray-16/releases](Ссылка?) Да изи бро. Почему ты сам не можешь их найти, мне не понятно.

**Comment by aka-sektor** [comment]
> изи

Хуизи молодой. Там старый билд.

> А скрины-то зачем?

На скрине замечательно видно. Без лишних вопросов, че почему зачем.

> Мы на такие вопросы отвечаем и помогаем.

Я видел как у вас там отвечают. Думаю, многие предпочли бы обходить стороной ваш дискорд.
Тем не менее, решительно не понимаю, зачем городить барьеры, а не прокладывать мосты.

**Comment by aka-sektor** [comment]
> А скрины-то зачем?

На скрине замечательно видно. Без лишних вопросов, че почему зачем.

> Мы на такие вопросы отвечаем и помогаем.

Я видел как у вас там отвечают. Думаю, многие предпочли бы обходить стороной ваш дискорд.
Те не менее, решительно не понимаю, зачем городить барьеры, а не прокладывать мосты.

**Comment by justtails** [comment]
Ну так клонируй репо) Только зачем тебе это, если ты вроде как не погромист. Вот честно, на кой черт поднимать целый Issue, если все находится самостоятельно путем изучения репо и гугления. Issue созданы для того, чтобы люди могли оставлять отклики о проблемах, а не для вопросов, решаемых анализом и через усидчивость.

**Comment by Seakad** [comment]
Был какой-то стрим у Oxy, там чувак показывал как собирать.
Тут тоже самое, и как сказал Султан, надо именно клонировать на винт, чтобы подмодули скачались.
А далее просто выбираешь x64/x86 и Release, и собираешь решение "Engine" сразу, студия сама собирает либы в нужном порядке.

**Comment by aka-sektor** [comment]
> зачем тебе это

Потому что, я уже сказал

> у OGSR например, сборка сразу на главной.

Здесь же приходится узнавать у того кто в курсе.
В общем, я все что хотел узнал. И да:

> ты вроде как не погромист

Нет. И я не пытался выяснить подробную инструкцию по сборке. Я лишь узнавал тут общие вещи.
Разумеется на основе этих данных, собрать исходники просто установив нужную версию VS - не выйдет. Потребуется куча сопутствующего софта.

**Comment by Xottab-DUTY** [comment]
Не куча, а, максимум, две дополнительных программы: клиент для гитхаба и гит консоль.

**Comment by Seakad** [comment]
> Потребуется куча сопутствующего софта

Вот сдк собрать, да, куча софта, а двигла опена достаточно одной студии и исходников.

**Comment by aka-sektor** [comment]
Думаю, в будущем вернемся к вопросу, как реально собрать исходники. А пока мне честно говоря не до этого.
