### ISSUE TITLE
Switch on animation camera glitch

### ISSUE THREAD

**Issue by romanpopulik** [OpenXRay/xray-16#423]
I noticed strange camera glitch at the end of switch on animation:
https://youtu.be/eqhxLNcdn6A

There is everything fine with animation itself for sure, so I think it is engine related problem.

**Comment by romanpopulik** [comment]
As you can see in COC, everything is fine:
https://youtu.be/i-ZS_ZZh2jM
So it must be Openxray problem.

**Comment by romanpopulik** [comment]
Still not fixed in the latest release :-/

**Comment by LVutner** [comment]
https://github.com/revolucas/CoC-Xray/commit/8bc50bb7ed42c5ff9b6019e61d7bc09252be5c6d

Maybe this could be useful?

**Comment by LVutner** [comment]
and this: https://github.com/revolucas/CoC-Xray/commit/b6f09b89a42815a46dee6b7020cfc3b95b9f3c65

**Comment by SkyLoaderr** [comment]
Fixed with ec743e9efc659988e9f36cf7cef8edc27681da32
