### ISSUE TITLE
Merge xrXMLParser into xrCore

### ISSUE THREAD

**Issue by nitrocaster** [OpenXRay/xray-16#43]
Also consider if it's possible to delete tinyxml (which xrXMLParser is based on) sources and add it as a submodule or 3rd party library.

**Comment by Xottab-DUTY** [comment]
I think we need to update TinyXML to TinyXML2 together with merging xrXMLParser into xrCore.

**Comment by alexgdi** [comment]
Ok, xrXMLParser dont have functional changes except edited 1 param in class
