### ISSUE TITLE
SSAO techniques questions

### ISSUE THREAD

**Issue by donizettilorenzo** [OpenXRay/xray-16#435]
2 Simple questions: 

What is now (build 421) the best SSAO implementation talking about graphic fidelity among Default/HBAO/HDAO ?

HDAO  (Very High) uses *compute* shaders in D3D11 rendering path as in the original game?
Now I see "Very High" in D3D10 too for HDAO, why?

**Comment by LVutner** [comment]
SSAO is okay. 
HBAO is too powerful, and noisy. 

IMO better try to implement better AO solution, like SSDO - looks way better. Everything will be better than GSC AO :P 

You see that option because HDAO was modified. Maybe Xottab can tell you more details about it
