### ISSUE TITLE
FPS limiter

### ISSUE THREAD

**Issue by donizettilorenzo** [OpenXRay/xray-16#436]
Simple request: can you implement an FPS limiter for who plays in windowed mode (VSync is related to fullscreen mode) or simply who wants to cap the framerate (I really like it to avoid stress to the GPU)?

**Comment by Xottab-DUTY** [comment]
Already done with de9362d115506ee79cd35c00cae4a6501fefe12f. (not in the latest pre-release though, will be included with next release)

**Comment by Xottab-DUTY** [comment]
Crosses with #366.
