### ISSUE TITLE
Refresh coding standards

### ISSUE THREAD

**Issue by kacejot** [OpenXRay/xray-16#444]
Hi guys!
Your coding conventions are outdated at some places. Like this

```cpp
namespace XRay
{
namespace Math
{
#define PI 3.14159265359
}
}
```

If you already support c++17 standard, you should replace it with nested namespaces:
```cpp
namespace XRay::Math
{
#define PI 3.14159265359
}

```

Also this one is absolutely not necessary:
Don't put empty lines between code inside functions. If you want to separate code fragments, put a comment line.

Logical code indentation  is OK, but useless comments that are just repeating the code are terrible - code should describe the logic without excess comments.

Also code rules should be better structured because some of them are visually merged with each other. Possible solution is to give each rule number and indentation. In addition some rules can be separated into groups.

I can modify this page but I need to have a conversation with authors of this coding standard before I can start.

**Comment by nitrocaster** [comment]
Completely agreed on nested namespaces.

> Logical code indentation is OK, but useless comments that are just repeating the code are terrible - code should describe the logic without excess comments.

This is actually the point. If you want to just insert a blank line without putting a meaningful comment in there - you shouldn't do that.
