### ISSUE TITLE
Refresh wiki page

### ISSUE THREAD

**Issue by kacejot** [OpenXRay/xray-16#445]
For now the wiki page of OpenXRay is a mess!
I mean all necessary pages on all possible languages are trying to fit into main wiki page. 
I haven't even found coding conventions from the first time!

That should be structured by the next design:
- Main page contains only links to language main wiki page.
- Language main page contains thematic sections like: Development, Modding, Using, Contributing, etc.

I can do this, if you agree for these changes

**Comment by kacejot** [comment]
Do we really need this [wiki page](https://github.com/OpenXRay/xray-16/wiki/%5BEN%5D-Linux-progress-status)? It looks as Linux roadmap and could be observed [here](https://github.com/OpenXRay/xray-16/projects/3).

**Comment by kacejot** [comment]
The same thing with [Changelog](https://github.com/OpenXRay/xray-16/wiki/Changes) page. Guys can find changelog info under each release. And fixed issues are located [here](https://github.com/OpenXRay/xray-16/issues?q=is%3Aissue+is%3Aclosed).

**Comment by Xottab-DUTY** [comment]
We definitely need a page with a good detailed changelog. Users ask it. Changelog under each release in not enough and it's not handy.

**Comment by kacejot** [comment]
@Xottab-DUTY, OK, I see, but it was updated long time ago

**Comment by Xottab-DUTY** [comment]
> Main page contains only links to language main wiki page.

I decided to left main homepage in English, but the wiki now has not only the sidebar, but also bottom bar which both contain links to the translated versions of the wiki.

> Language main page contains thematic sections like: Development, Modding, Using, Contributing, etc.

Done.

> Do we really need this [wiki page](https://github.com/OpenXRay/xray-16/wiki/%5BEN%5D-Linux-progress-status)? It looks as Linux roadmap and could be observed [here](https://github.com/OpenXRay/xray-16/projects/3).

Transferred this page to #704, deleted it from the wiki.
<hr>
The only thing left is changelog...

**Comment by Xottab-DUTY** [comment]
That's an old one. I'd like to close it and suggest to move documentation questions to #207.
