### ISSUE TITLE
Remove -fpermissive flag for Linux builds

### ISSUE THREAD

**Issue by kacejot** [OpenXRay/xray-16#446]
Consider removing it for two reasons:

1. Projects used to not have warnings in builds, but this flag downgrades errors to warnings. That is bad and can be a source of serious problems in future.
2. Once this flag is removed, a large part of code will be refactored for successful project builds. This will solve problems like include cycles and deprecated language constructions.

**Comment by Xottab-DUTY** [comment]
Done.
