### ISSUE TITLE
Is it possible to build engine on macOS?

### ISSUE THREAD

**Issue by eanekrasov** [OpenXRay/xray-16#450]
The only dependency I've failed to resolve is liblockfile-dev.
Is it possible theoretically?

**Comment by 375gnu** [comment]
liblockfile is available in homebrew (i'm not an osx user, just a passerby :) )

**Comment by nextgeniuspro** [comment]
brew install liblockfile

**Comment by Dx74rghs** [comment]
> The only dependency I've failed to resolve is liblockfile-dev.
> Is it possible theoretically?

Did you made a build?
I tried to do it but no luck. All dependencies are solved, but got missing header files during make.

**Comment by eagleivg** [comment]
Nope. None of the interested developers have a mac.

**Comment by GeorgeIvlev** [comment]
@eagleivg
I have one. But question in other thing, do we need to build engine on MacOS for now? I think no, for what purpose? Many gamers and game developers prefer to use linux or windows operating systems, maybe in some future, but compilation should be fine on  OSX too. 
@eanekrasov
I will check that problem by the end of the week.

**Comment by GeorgeIvlev** [comment]
@eanekrasov 
I have checked build on MacOS. Nope, currently build will fail because of many non supported and not implemented crossplatform "things" in code. I'm not sure that we will support osx systems. Maybe in some future.

**Comment by Xottab-DUTY** [comment]
macOS will be one of the next possible platforms to which we will port the engine.

**Comment by naymapl** [comment]
Any news with macOS. Try to cmake.. but always got error:

```
-- Found LZO: /usr/local/lib/liblzo2.dylib
git commit: 35fbe9728941dda2654dd62249c3a22c8b758e3b
git branch: dev
-- The ASM compiler identification is Clang
-- Found assembler: /Library/Developer/CommandLineTools/usr/bin/cc
Makefile:320: *** missing: export MACOSX_DEPLOYMENT_TARGET=XX.YY.  Stop.
lj_arch.h:82:10: fatal error: 'TargetConditionals.h' file not found
#include "TargetConditionals.h"
         ^~~~~~~~~~~~~~~~~~~~~~
1 error generated.
CMake Error at Externals/LuaJIT-proj/luajit.cmake:191 (if):
  if given arguments:

    "STREQUAL" ""

  Unknown arguments specified
Call Stack (most recent call first):
  Externals/LuaJIT-proj/CMakeLists.txt:1 (include)


-- Configuring incomplete, errors occurred!
```

https://github.com/LuaJIT/LuaJIT/issues/653 - solution

**Comment by Xottab-DUTY** [comment]
> Any news with macOS. Try to cmake.. but always got error:
> 
> ```
> -- Found LZO: /usr/local/lib/liblzo2.dylib
> git commit: 35fbe9728941dda2654dd62249c3a22c8b758e3b
> git branch: dev
> -- The ASM compiler identification is Clang
> -- Found assembler: /Library/Developer/CommandLineTools/usr/bin/cc
> Makefile:320: *** missing: export MACOSX_DEPLOYMENT_TARGET=XX.YY.  Stop.
> lj_arch.h:82:10: fatal error: 'TargetConditionals.h' file not found
> #include "TargetConditionals.h"
>          ^~~~~~~~~~~~~~~~~~~~~~
> 1 error generated.
> CMake Error at Externals/LuaJIT-proj/luajit.cmake:191 (if):
>   if given arguments:
> 
>     "STREQUAL" ""
> 
>   Unknown arguments specified
> Call Stack (most recent call first):
>   Externals/LuaJIT-proj/CMakeLists.txt:1 (include)
> 
> 
> -- Configuring incomplete, errors occurred!
> ```
> 
> [LuaJIT/LuaJIT#653](https://github.com/LuaJIT/LuaJIT/issues/653) - solution

There is a progress in #923, @Vertver managed to compile and launch it to the main menu, but didn't get into the game yet.
(though, the pull request is only for macOS with Apple M1 processor. But it can be ported to older macOS versions in future)

**Comment by Xottab-DUTY** [comment]
Technically, the issue is solved, engine can be built on macOS and I want to reduce the number of open issues...

It won't run though, feel free to reopen this issue and rename it or open a new issue with wording something like: "Run on macOS". :)

**Comment by Xottab-DUTY** [comment]
> feel free to reopen this issue and rename it or open a new issue with wording something like: "Run on macOS". :)

The issue about running macOS is open!
#1104
