### ISSUE TITLE
MASSIVE fps drop when looking to certain areas around skadovsk and beyond

### ISSUE THREAD

**Issue by moussechoco** [OpenXRay/xray-16#452]
There is still a MAJOR issue with the game that needs an absolute fix. It is near unplayable when you are hanging out around skadovsk or looking to certain area .  From 50 fps to 9 . Low gpu usage, low CPU usage. Can't see where the bottleneck is.

Lowering vision distance and LOD to minimum help a bit but i can't go over 20 fps and the game becomes ugly as never.  Disabling grass shadowing improves it a bit too .

I play at 4K, and am not at maximum settings ( 2K shadows, 200 radius for grass and 0.3 density, 0.5 lod, 1 vision distance) .

My setup : 

Amd ryzen 2600 @ 4.2 ghz .
Radeon Vega 64 @ 1717 mhz ( 1110 mhz for HBM2 )
16 gb @3200 mhz

This issue is present on all of API, and can be reproduced with other setups too ( intel + Nvidia ).

Thanks for your attention and your work, and good luck.

**Comment by Xottab-DUTY** [comment]
I have some thoughts on it. Will try to find the reason.
Thank you for the bugreport!

**Comment by moussechoco** [comment]
It drove me insane. I couldn't find the bottleneck. I tried to edit alife.ltx, but it seemed to do nothing ( maybe i failed here) . I thought about an issue with npc, or maybe  number of drawcalls .
This issue can be sometimes see on ShoC or CS with absurd amount of grass density and/or very very high vision distance and LOD . Exactly the same symptoms. Low gpu usage low cpu usage, low fps.
But it is very rare and easily avoidable in those games.
 
Sorry for not being able to tell more. Have a good day.

**Comment by eagleivg** [comment]
Can you try swith off dynamic sun lighting (r2_sun off)?

**Comment by moussechoco** [comment]
> 
> 
> Can you try swith off dynamic sun lighting (r2_sun off)?

I did. No effect at all.

**Comment by Roman-n** [comment]
Xottab-DUTY and what kind of thoughts on this issue?
As previously assumed - is it in the light sources?
Is there any way to fix this? In the original, there are no such problems ..
> I have some thoughts on it. Will try to find the reason.

**Comment by Xottab-DUTY** [comment]
Sad, but currently I didn't found the reason..

**Comment by Xottab-DUTY** [comment]
Fixed in 3560f0479d235904938b90caf774ffa0e1a8b3b7 (And b0b36189220270309ffbb6131fa5fdeb18cf6c18 is related too)
