### ISSUE TITLE
Portable install?

### ISSUE THREAD

**Issue by andrew-mcmahon** [OpenXRay/xray-16#458]
First off all excellent work! It's been several months since I tried compiling the openxray engine and the improvements are significant.
  
I'm using an outdated Phenom II + R9 285 (mesa-git 19.3.0-devel) and no longer suffer from the [darkness problem](https://github.com/OpenXRay/xray-16/issues/317). If anything the performance is quite reasonable now between 30-60 fps @ 1080p and the game seems a lot more stable - [I recorded my screen](https://drive.google.com/open?id=1wiB7pyrDUo6dh-tXoLeo1WMLbLsCKE_h) with ffmpeg whilst playing.

The [build instructions](https://github.com/OpenXRay/xray-16/wiki/%5BEN%5D-How-to-build-and-setup-on-Linux) seem a bit out-of-date again but they do work - I had no trouble compiling the game under Debian Testing.  
  
As [this post mentions](https://github.com/OpenXRay/xray-16/issues/440) the game expects to install system wide but I was wondering if a portable install would be possible? openxcom, nblood, gzdoom, eduke32, dhewm3, quakespasm, etc - all of those can be run from the same directory which contains the game data. I usually use [innoextract](https://github.com/dscharrer/innoextract) to get the game data from the GOG installer.

I did get it working this way - now assuming the game data is located in a subdirectory in a user's home i.e: 
`~/pripyat`

Add the **gamedata** folder & **fsgame.ltx**.  
Change the make DESTDIR command to:
`make DESTDIR=~/pripyat install`

Add the newly created **usr/lib** directory to library path:
`export LD_LIBRARY_PATH=~/pripyat/usr/lib/`

Then I could run the game as normal by starting **xr_3da**:
`./xr_3da -fsltx ~/pripyat/fsgame.ltx`

_There's a strange quirk where if I copy the executable into the main game folder alongside **fsgame.ltx** the game won't launch with either of these commands - it must require an absolute pathname?_
`./xr_3da -fsltx fsgame.ltx`
`./xr_3da -fsltx ./fsgame.ltx`

**Comment by Xottab-DUTY** [comment]
Yes, I agree with you. We plan to restore support for portable installation.

**Comment by Xottab-DUTY** [comment]
@eagleivg this should be fixed, isn't it?

**Comment by eagleivg** [comment]
Yes, fixed.
