### ISSUE TITLE
xr_3da.sh not present in bin-linux folder

### ISSUE THREAD

**Issue by Jerickman** [OpenXRay/xray-16#469]
Error from terminal when attempting to execute binaries from bin-linux folder in Call of Pripyat installation directory:
./xr_3da.sh -fsltx ../fsgame.ltx
bash: ./xr_3da.sh: No such file or directory

**To Reproduce**
Follow steps outlined to build xray-16 on Linux
bash script is not present in bin-linux

[error.log](https://github.com/OpenXRay/xray-16/files/3636369/error.log)
[out.log](https://github.com/OpenXRay/xray-16/files/3636370/out.log)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - OpenXRay build version 16

**Comment by eagleivg** [comment]
./xr_3da.sh - is outdated method for run, i`m update english wiki:
https://github.com/OpenXRay/xray-16/wiki/[EN]-How-to-build-and-setup-on-Linux

**Comment by 007exe** [comment]
If you need a portable version, you can use the Portable installation item from this manual https://github.com/OpenXRay/xray-16/wiki/%5BRU%5D-Как-собрать-движок-на-Linux But it is in Russian
