### ISSUE TITLE
Implement wetness on HUD (raindrops on glass effect)

### ISSUE THREAD

**Issue by JIuBeP** [OpenXRay/xray-16#470]
Добавьте пожалуйста поддержку шейдера намокания на стекле, как в OGSR или xrOxygen! Довольно клевый эффект :)

**Comment by Xottab-DUTY** [comment]
Это не стоит того.

**Comment by JIuBeP** [comment]
Есть какие то трудности с этим?

**Comment by Xottab-DUTY** [comment]
Придётся добавлять новые шейдеры для этого эффекта, а это нарушит принцип минимальной геймдаты, но эффект не настолько крутой, чтобы ради него этот принцип нарушать. К тому же мы уже сейчас потихоньку облегчаем нашу геймдату, поэтому вряд ли туда будет добавлено что-то новое.

Впрочем, есть у меня пара идей как это можно реализовать так, чтобы было и гибко и совместимо.

**Comment by Xottab-DUTY** [comment]
Closing this for now. 

May be reconsidered after implementing #492.

Пока закрываю. Возможно, в будущем всё-таки реализуем, но только после #492
