### ISSUE TITLE
Async screenshot is broken

### ISSUE THREAD

**Issue by vTurbine** [OpenXRay/xray-16#472]
I have a bunch of access violations while taking screenshot in LAN game. Reproduced on "Mixed" configuration, will update "Release" soon. 

To check it you need:
1. Create new LAN game as server with any map
2. Execute console command `dbg_make_screenshot`

Brief debug showed that JPEG encoding wasn't successful due to `jpeg_compress_struct` sizes mismatch (different build targets?). Of course no retcode checked and this seems break further sreenshot processing pipeline which eventualy crashes in PPMd compressor.

Could you confirm it?

**Comment by Xottab-DUTY** [comment]
Probably it's broken only on x64, but should work on x86. *(not sure)*

**Comment by nitrocaster** [comment]
Were you running x64 or x86 build? I fixed some bug related to `dbg_make_screenshot` a few years ago and it was working fine after the fix.

**Comment by vTurbine** [comment]
UPD: Re-checked with 4313bee
I used x64 in "Mixed" and "Release" configurations both. Unfortunately, unable to run x86

**Comment by Xottab-DUTY** [comment]
Was removed somewhere in 2023-2024.
