### ISSUE TITLE
Make gamedata fully optional and move it into separate project

### ISSUE THREAD

**Issue by Xottab-DUTY** [OpenXRay/xray-16#474]
To be fully compatible with the original engine, we should make all our gamedata improvements optional.

Then, we can create a new project on behalf of OpenXRay which delivers improvements and fixes to the original game, but is not limited to that only. In this new project we can implement new features that are not suitable for `xray-16` (because it is a platform for modmakers, but not mod itself)

**Comment by Xottab-DUTY** [comment]
First step on this is to solve #473 and make [all other shaders](https://github.com/OpenXRay/xray-16/tree/xd_dev/res/gamedata/shaders) optional.

Scripts and configs are already optional.

**Comment by 007exe** [comment]
However, for Linux, OpenGL shaders that are not available in the vanilla version remain mandatory. Perhaps you should add and download shaders from /usr/share/openxray/shaders for Linux along the standard paths?

**Comment by Xottab-DUTY** [comment]
@007exe, if we implement #258, then OpenGL shaders won't be a mandatory =)

> Perhaps you should add and download shaders from /usr/share/openxray/shaders for Linux along the standard paths?

No, that's unnecessary and may be confusing. Standard `gamedata/shaders/gl` is enough.

**Comment by Xottab-DUTY** [comment]
#473 is done. Next step is #492.

**Comment by Xottab-DUTY** [comment]
All gamedata (except GLSL shaders) was removed. Next step is to restore it in the OpenXRay Plus project.
https://github.com/OpenXRay/plus

*P.S. #492 is still to be implemented.*

**Comment by Xottab-DUTY** [comment]
To close this issue we need to implement #258, while #492 is optional.
