### ISSUE TITLE
Clear Sky location transition crash

### ISSUE THREAD

**Issue by Gimbatul** [OpenXRay/xray-16#495]
I got to Cordon & returned to Swamps. When moving back to Cordon for the second time game crashes every time. I've tried different builds including latest ones. I've tried to add a script for Clear Sky guys to take you to Cordon (that they don't do in vanilla). It worked but game crashed so there's no difference if I move by feet or teleport.

[OpenXRay_error_report_191015-212641.zip](https://github.com/OpenXRay/xray-16/files/3730901/OpenXRay_error_report_191015-212641.zip)

**Comment by Xottab-DUTY** [comment]
@Gimbatul, thank you for the report! Please, check if crash is fixed.

**Comment by Xottab-DUTY** [comment]
> Please, check if crash is fixed.

Of course, as soon as [the latest build](https://ci.appveyor.com/project/OpenXRay/xray-16/builds/28143064) will be built.

**Comment by Gimbatul** [comment]
I've tried it on my latest save and it worked. Then I moved to my old save where I found it for the first time.

**Comment by Gimbatul** [comment]
I've tried it on my latest save and it worked. Then I moved to my old save where I found it for the first time. Strangely enough, I've got a couple of same crashes along the way while testing, but it's fine now. It works. Actually, I recall some strange bugs with first 2 locations happening in the original engine. They happened at the start and resolved after, probably some state issues. Anyway, thank you for your fast response and all the work you are doing. Extremely appreciate)

**Comment by Xottab-DUTY** [comment]
> Actually, I recall some strange bugs with first 2 locations happening in the original engine.

Uh, if the reasons of these bugs are the same as the reason of this issue, this is a positive thing because it's probably confirms my theory about memory problems that was hidden (unintentionally) in the original engine.

Thank you too!

**Comment by Xottab-DUTY** [comment]
This didn't helped me
![trollsad](https://user-images.githubusercontent.com/2989212/67148686-b02c2500-f2bb-11e9-9c0a-007ea479e132.png)

I'm getting the crash even after the fix.

Maybe I should start a new game and this will fully fix the problem?
I doubt it.

**Comment by Gimbatul** [comment]
Here's a save from when I tried to go to Clear Sky to modify my armor. It worked for me after a couple of crashes. Could you try it?
[8.zip](https://github.com/OpenXRay/xray-16/files/3747062/8.zip)

**Comment by d10sfan** [comment]
I'm seeing a crash similar to this when I transition between the cordon to the garbage. To replicate, you can go to the garbage, then attempt to go back to the cordon directly after, and then the game will crash.

[an27.zip](https://github.com/OpenXRay/xray-16/files/5827042/an27.zip)

There's no symbols but the log looks like:

```
FATAL ERROR
 
[error] Expression    : <no expression>
[error] Function      : handler_base
[error] File          : /__w/packages/packages/engines/openxray/source/src/xrCore/xrDebug.cpp
[error] Line          : 870
[error] Description   : segmentation fault
 

stack trace:

xrDebug::GatherInfo(char*, unsigned long, ErrorLocation const&, char const*, char const*, char const*, char const*)
xrDebug::Fail(bool&, ErrorLocation const&, char const*, char const*, char const*, char const*)
lib/xrCore.so(+0x48ad7) [0x7fce0d17ead7]
/usr/lib/libc.so.6(+0x3d6a0) [0x7fce0ca9c6a0]
lib/xrRender_GL.so(+0xfc050) [0x7fce051b1050]
lib/xrRender_GL.so(+0x106d81) [0x7fce051bbd81]
lib/xrRender_GL.so(+0x17ca1d) [0x7fce05231a1d]
/usr/lib/libc.so.6(__cxa_finalize+0xce) [0x7fce0ca9f3ae]
lib/xrRender_GL.so(+0x2aff3) [0x7fce050dfff3]

```

Also, not sure if this is related, but an earlier save ([an24.zip](https://github.com/OpenXRay/xray-16/files/5827055/an24.zip)) shows this LUA error that will spam in the console. It still seems to run ok, but wondering if that might be causing some failures when attempting to get back to the area. I don't have a file with that name in my gamedata, so I'm assuming it may be an issue with the original LUA files.

```
! [LUA]  CharacterCommunity available only for InventoryOwner
stack traceback:
	...mmon\STALKER Clear Sky\gamedata\scripts\xr_danger.script:87: in function <...mmon\STALKER Clear Sky\gamedata\scripts\xr_danger.script:32>
! [LUA]  CharacterCommunity available only for InventoryOwner
stack traceback:
	...mmon\STALKER Clear Sky\gamedata\scripts\xr_danger.script:87: in function <...mmon\STALKER Clear Sky\gamedata\scripts\xr_danger.script:32>
! [LUA]  CharacterCommunity available only for InventoryOwner
stack traceback:
	...mmon\STALKER Clear Sky\gamedata\scripts\xr_danger.script:87: in function <...mmon\STALKER Clear Sky\gamedata\scripts\xr_danger.script:32>
! [LUA]  CharacterCommunity available only for InventoryOwner
stack traceback:
	...mmon\STALKER Clear Sky\gamedata\scripts\xr_danger.script:87: in function <...mmon\STALKER Clear Sky\gamedata\scripts\xr_danger.script:32>
! [LUA]  CharacterCommunity available only for InventoryOwner
stack traceback:
	...mmon\STALKER Clear Sky\gamedata\scripts\xr_danger.script:87: in function <...mmon\STALKER Clear Sky\gamedata\scripts\xr_danger.script:32>
```

**Comment by makpif** [comment]
При переходе на кордон с шансом 90% это происходит, способ перехода (пешком или через проводника) и локация с которой идет переход не имеет значения. Также, недавно, после вызволения наемников из "пузыря", тоже самое с агропромом

OS: Linux
