### ISSUE TITLE
Clear Sky inventory crash

### ISSUE THREAD

**Issue by Gimbatul** [OpenXRay/xray-16#497]
Every time I'm trying to see a description of any food or vodka, I get an instant crash. It doesn't happen if I just double click to use it.
[OpenXRay_error_report_191019-041952.zip](https://github.com/OpenXRay/xray-16/files/3746079/OpenXRay_error_report_191019-041952.zip)

**Comment by Xottab-DUTY** [comment]
Scar was just getting shocked when he saw from what that baton and kolbasa are made of.
![trollface](https://user-images.githubusercontent.com/2989212/67141991-9b7c6c80-f27c-11e9-820e-77027482e112.png)
