### ISSUE TITLE
Compile with Debug configuration

### ISSUE THREAD

**Issue by ghost** [OpenXRay/xray-16#5]
I managed to compile VS2008 source in debug, after i fixed a vsprintf error. 
I made this in zutil.h:
http://pastebin.com/9hYWbVLQ

The compile process is going fine with this fix, but i can't start the game with the new debug binaries:
http://pastebin.com/DTW8uUtm

Did someone managed to compile stuff properly in debug, or did i make a mistake with my fix, which causes this ugly error?

**Comment by nitrocaster** [comment]
Check this out: https://github.com/nitrocaster/xray/commit/5b15635537d48365b5d640c18a768f4dd9dacf7c

I have no idea how did it work before. Do you compile with stlport?

**Comment by ghost** [comment]
Thanks!
I use the MSVC9 STL, i didn't modify anything else just zutil.h yet.

After i implemented 
https://github.com/nitrocaster/xray/commit/5b15635537d48365b5d640c18a768f4dd9dacf7c
and all of these fixes too:
https://github.com/nitrocaster/xray/commit/7de0301fe9adcb432f64b94744a2a909d26513f3
I get this when compiling xrCore.dll:

xrDebugNew.obj : error LNK2019: unresolved external symbol "unsigned int __cdecl mem_usage_impl(void *,unsigned int *,unsigned int *)" (?mem_usage_impl@@YAIPAXPAI1@Z) referenced in function "int __cdecl out_of_memory_handler(unsigned int)" (?out_of_memory_handler@@YAHI@Z)
......\binaries\xrCore.dll : fatal error LNK1120: 1 unresolved externals

BTW @nitrocaster, is your VS2013 COP repo already out there? I assume you already did fix these errors in VS2013.

**Comment by nitrocaster** [comment]
> I get this when compiling xrCore.dll:

Just read logs. mem_usage_impl is declared, but not defined (since you removed its definition). Go to out_of_memory_handler and replace mem_usage_impl with Memory.mem_usage.

> is your VS2013 COP repo already out there?

Yes it is.

**Comment by ghost** [comment]
Thanks again, well, i guess i have a lot to learn.

Awesome, I'll try out your VS2013 stuff, instead of messing with VS2008.

**Comment by ghost** [comment]
Nitro, your CS memory handler fixes worked like charm in COP too.
I managed to compile VS2008 source with debug config, which actually works on all renderers. It's awesome. :)
Thread closed.
