### ISSUE TITLE
Implement physically based rendering (PBR)

### ISSUE THREAD

**Issue by SadBoyOff** [OpenXRay/xray-16#504]
**Describe the problem**
S.T.A.L.K.E.R uses incomplete PBR functionality

**To Reproduce**
I propose to pay attention to https://github.com/google/filament

**Expected behavior**
If you use this project as a reference visualization PBR, you can achieve good results in terms of visual component

*Rendering

-Clustered forward renderer
-Cook-Torrance microfacet specular BRDF
-Lambertian diffuse BRDF
-HDR/linear lighting
-Metallic workflow
-Clear coat
-Anisotropic lighting
-Approximated translucent (subsurface) materials
-Cloth shading
-Normal mapping & ambient occlusion mapping
-Image-based lighting
-Physically-based camera (shutter speed, sensitivity and aperture)
-Physical light units
-Point light, spot light and directional light
-SSAO
-ACES-like tone-mapping
-Temporal dithering
-FXAA, MSAA and specular anti-aliasing

**Screenshots**
https://github.com/google/filament/raw/master/docs/images/samples/model_helmet.jpg
https://github.com/google/filament/raw/master/docs/images/samples/model_damaged_helmet.jpg

**Comment by LVutner** [comment]
Hey,

First of all. OXR aims for minimalizing amount of new files in gamedata (in order to keep compability wih mods.)

If you really want to see PBR, maybe try to ask on OXYGEN server?


Cook-Torrance lightning model was included in Float32 mod for ShoC. You should check it.

**Comment by SadBoyOff** [comment]
> Hey,
> 
> First of all. OXR aims for minimalizing amount of new files in gamedata (in order to keep compability wih mods.)
> 
> If you really want to see PBR, maybe try to ask on OXYGEN server?
> 
> Cook-Torrance lightning model was included in Float32 mod for ShoC. You should check it.

**Comment by ForserX** [comment]
> If you really want to see PBR, maybe try to ask on OXYGEN server?

https://github.com/xrOxygen/xray-oxygen
