### ISSUE TITLE
Error when compiling script_engine.cpp

### ISSUE THREAD

**Issue by vpelcak** [OpenXRay/xray-16#508]
**Describe the bug**

/xray-16/src/xrScriptEngine/script_engine.cpp: In static member function ‘static void luajit::allow_escape_sequences(bool)’:
/home/vita/!files/programy/xray-16/src/xrScriptEngine/script_engine.cpp:912:9: error: ‘lj_allow_escape_sequences’ was not declared in this scope
         lj_allow_escape_sequences(allowed ? 1 : 0);
         ^~~~~~~~~~~~~~~~~~~~~~~~~
/xray-16/src/xrScriptEngine/script_engine.cpp:912:9: note: suggested alternative: ‘allow_escape_sequences’
         lj_allow_escape_sequences(allowed ? 1 : 0);
         ^~~~~~~~~~~~~~~~~~~~~~~~~
         allow_escape_sequences
make[2]: *** [src/xrScriptEngine/CMakeFiles/xrScriptEngine.dir/build.make:176: src/xrScriptEngine/CMakeFiles/xrScriptEngine.dir/script_engine.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2641: src/xrScriptEngine/CMakeFiles/xrScriptEngine.dir/all] Error 2
make: *** [Makefile:152: all] Error 2

**Additional context**
Gentoo, I used latest Git version of X-Ray.

**Comment by Xottab-DUTY** [comment]
Your LuaJIT submodule is outdated

**Comment by vpelcak** [comment]
You're right.
Sorry.
