### ISSUE TITLE
SSAO HDAO is broken on OpenGL on AMD Vega11

### ISSUE THREAD

**Issue by 375gnu** [OpenXRay/xray-16#510]
**Describe the bug**
With SSAO set to HDAO (the default settings) on my AMD Vega11 I see a dark environment with a bright spot left to the actor.

**To Reproduce**
1. Just start a new game without user.ltx or set SSAO to HDAO with low quality (I haven't tested other quality settings)

**Expected behavior**
Normal lighting without the bright spot. 

**Screenshots**
I would like to provide screenshots but screenshot creation s broken as well.
UPD: found in discord: https://media.discordapp.net/attachments/410173937238933515/641391856755933204/unknown.png

**Desktop (please complete the following information):**
 - OS: Devuan (Debian fork) Unstable
 - OpenXRay build version 558

**Additional context**
HBAO works well, but shadows are too sharp.

**Comment by Xottab-DUTY** [comment]
@375gnu was it fixed?

**Comment by 375gnu** [comment]
i can't test anymore due to hardware absence.

**Comment by Xottab-DUTY** [comment]
Anyway, there are number of SSAO issues fixed by @SkyLoaderr. Maybe this issue was fixed too, if not we can just reopen this.
