### ISSUE TITLE
Render: Broken index buffer after `vid_restart`

### ISSUE THREAD

**Issue by vTurbine** [OpenXRay/xray-16#514]
Reset logic in the render is broken by now. Even after 3964a31 I still get invalid index buffer handle when the render is destructing.

The steps to reproduce are simple:
* In the main menu open console and execute `vid_restart`
* Exit from the game

In case of running in debug session, an exception occurs while trying to ref counter in stats.
Since it was introduced with my recent PR #490 I'll take care of the issue. Just give me some time.
In case of an urgent fix, there is no need to revert all the changes -- just return quadIB creating logic.

**Comment by Xottab-DUTY** [comment]
~~This affects all renderers?~~

Crash only on DX10/DX11, but all renderers are affected.

**Comment by Xottab-DUTY** [comment]
Done :)

**Comment by vTurbine** [comment]
Perfect!
