### ISSUE TITLE
Persistent segmentation faults

### ISSUE THREAD

**Issue by uw5fl** [OpenXRay/xray-16#525]
Hello, dear developers.
I'm experiencing constant segfaults upon exiting the game or when I'm trying to apply a mod such as SGM 2.2 previously ported to a windows version of OpenXRay. I am on Manjaro myself, so I'm using the native linux version of OpenXRay. NV proprietary, v418. 16GB RAM, GT 730M. Other specs on request, sorry can't remember the exact processor model, but one of the i7-3xxx family. The code was borrowed from AUR and compiled on december 13 this year.
Thanks in advance.
PS
BTW, I would like to offer you my help as a programmer in case you are interested.
Below goes the log for the on-game-quitting segfault.
`
### FATAL ERROR
 
[error] Expression    : <no expression>
[error] Function      : handler_base
[error] File          : /home/uw5fl/.cache/pacaur/openxray-git/src/xray-16/src/xrCore/xrDebug.cpp
[error] Line          : 839
[error] Description   : segmentation fault
 

### stack trace:

/usr/lib/xrCore.so(_ZN7xrDebug10GatherInfoEPcmRK13ErrorLocationPKcS5_S5_S5_+0x1db) [0x7fb3398a79db]
/usr/lib/xrCore.so(_ZN7xrDebug4FailERbRK13ErrorLocationPKcS5_S5_S5_+0x94) [0x7fb3398a7ba4]
/usr/lib/xrCore.so(+0x41098) [0x7fb3398a8098]
/usr/lib/libc.so.6(+0x3bfb0) [0x7fb339380fb0]
/usr/lib/libpthread.so.0(__pthread_mutex_lock+0x4) [0x7fb338a0edc4]
/usr/lib/xrCore.so(_ZN4Lock5EnterEv+0x17) [0x7fb3398d8867]
/usr/lib/xrCDB.so(_ZN11ISpatial_DB6removeEP8ISpatial+0x13) [0x7fb338bb5793]
/usr/lib/xrCDB.so(_ZN11SpatialBase18spatial_unregisterEv+0x1f) [0x7fb338bb583f]
/usr/lib/xrRender_GL.so(+0x14ac8f) [0x7fb333a07c8f]
/usr/lib/xrRender_GL.so(+0x14b479) [0x7fb333a08479]
/usr/lib/xrRender_GL.so(+0xf16a8) [0x7fb3339ae6a8]
/usr/lib/xrRender_GL.so(+0xa57e5) [0x7fb3339627e5]
/usr/lib/libc.so.6(__cxa_finalize+0xce) [0x7fb339383cae]
/usr/lib/xrRender_GL.so(+0x2a548) [0x7fb3338e7548]
`

**Comment by 007exe** [comment]
Good afternoon. A bug with the completion of the process is well known. OpenXRay is compatible with the mods for the vanilla version of the game Stalker Call of Pripyat and Clear Sky, but Linux has problems at least at the file system level, i.e. all file and directory names must be lowercase, you may have to make some changes to the mode and the presence of shaders for openGL. The OpenXRay team will be of any help, you can join the discord channel https://discord.gg/sjRMQwv

**Comment by Xottab-DUTY** [comment]
1. Crash upon exit is fixed. I think, this issue can be closed now.
	Please, tell us if the crash is not fixed.
2. SGM has some issues in it itself, so it's not an issue when it crashes.
	Explanation: OpenXRay is strict on errors, while vanilla is very permissive and won't crash even if it should. (eg. it doesn't crash even when null pointer is being dereferenced!)
	However, we are working on lowering the level of strictness.
3. Pull requests are always welcome =)
