### ISSUE TITLE
[Windows][Rx64] OpenAL cannot create a sound device

### ISSUE THREAD

**Issue by badthrumbo** [OpenXRay/xray-16#528]
**Describe the bug**
Rx64 does not start the Call of Pripyat because OpenAl cannot create a sound device. The log appears in _appdata_, no crashreports get generated.

**To Reproduce**
1. Use Rx64 558 to start Call of Pripyat
2. Run Stalker-COP
3. See the CoP splash screen and the OpenAL error.

**Expected behavior**
Game shows the CoP splash screen and then goes to intro videos of GSC/ATI/etc.

**Screenshots**
![openal_error](https://user-images.githubusercontent.com/17273982/71084750-0546c300-21a7-11ea-995c-038e45e53edd.png)

**BugTrap error report**
No crashreports get generated

**Desktop (please complete the following information):**
 - OS: Windows 10
 - OpenXRay build version 558 Rx64

**Additional context**
When comparing the logs of Rx64 and Rx86, it looks like OpenAL cannot see the system default device when Rx64 is used.

Rx86 successful initialization:
```
CleanDeviceSpecifierList
CleanDeviceSpecifierList Generic Hardware
devices Generic Hardware
SOUND: OpenAL: system  default SndDevice name is Generic Hardware
SOUND: OpenAL: default SndDevice name set to Generic Software
SOUND: OpenAL: All available devices:
1. Generic Software, Spec Version 1.1 (default) eax[0] efx[no] xram[no]
2. Generic Software, Spec Version 1.1 (default) eax[0] efx[no] xram[no]
SOUND: Selected device is Generic Software
* sound: EAX 2.0 extension: absent
* sound: EAX 2.0 deferred: absent
* sound : cache: 65537 kb, 4856 lines, 13820 bpl
```

Rx64 unsuccessful initialization:

```
CleanDeviceSpecifierList
CleanDeviceSpecifierList 
devices 
SOUND: OpenAL: system  default SndDevice name is 

```

[FAILED.Rx64.558.openxray_boletus.log](https://github.com/OpenXRay/xray-16/files/3978294/FAILED.Rx64.558.openxray_boletus.log)
[SUCCESSFUL.Rx86.558.openxray_boletus.log](https://github.com/OpenXRay/xray-16/files/3978295/SUCCESSFUL.Rx86.558.openxray_boletus.log)

**Comment by Xottab-DUTY** [comment]
Quote from [installation instruction](https://github.com/OpenXRay/xray-16/wiki/%5BEN%5D-How-to-install-and-play):
> If you have problems with OpenAL install it using `oalinst.exe`

**Comment by badthrumbo** [comment]
I am blind, sorry. This fixes the issue.

**Comment by Xottab-DUTY** [comment]
No problem 😃
