### ISSUE TITLE
C.O.P. Open X-Ray attempt to index a nil value

### ISSUE THREAD

**Issue by msanchezcordi** [OpenXRay/xray-16#529]
**Describe the bug**
SCRIPT RUNTIME ERROR
stack traceback:
	... Call of Pripyat\gamedata\scripts\fallout_manager.script:353: in function 'get_nearest_cover'
	... Call of Pripyat\gamedata\scripts\fallout_manager.script:227: in function 'update'
	....R. Call of Pripyat\gamedata\scripts\bind_stalker.script:383: in function <....R. Call of Pripyat\gamedata\scripts\bind_stalker.script:250>
 
FATAL ERROR
 
[error] Expression    : !m_error_code
[error] Function      : raii_guard::~raii_guard
[error] File          : C:\projects\xray-16\src\xrScriptEngine\script_engine.cpp
[error] Line          : 569
[error] Description   : ... Call of Pripyat\gamedata\scripts\fallout_manager.script:353: attempt to index a nil value

**To Reproduce**
Random
**Expected behavior**
Cannot tell

**Desktop (please complete the following information):**
 - OS: Windows 10
 - OpenXRay Rx64 build 7568, Oct 26 2019
AppVeyor build 558 from commit[443b674ac99c705c8bce2e9ce439f6fe7fed3dd4] branch[HEAD] (built by OpenXRay)

[OpenXRay_error_report_191218-123145.zip](https://github.com/OpenXRay/xray-16/files/3979692/OpenXRay_error_report_191218-123145.zip)

**Comment by msanchezcordi** [comment]
Hi, game version 1.6.02. Installed Remake v3: https://www.moddb.com/mods/remake. Only that.

**Comment by Xottab-DUTY** [comment]
I can't say if it's our problem or a mod problem.
@msanchezcordi it's better to ask the mod author if he can something about it.

**Comment by eagleivg** [comment]
Dublicate of #686

**Comment by Xottab-DUTY** [comment]
@eagleivg totally not a duplicate.

**Comment by Xottab-DUTY** [comment]
There were few fixes related to crashes in mods and stability improvements overall, so I'm closing this issue as outdated. (it was submitted in 2019!)

We can reopen it in case issue is not fixed and still reproducible in the latest engine versions.
