### ISSUE TITLE
Call of Pripyat - attempt to index local 'job_data' (a nil value)

### ISSUE THREAD

**Issue by msanchezcordi** [OpenXRay/xray-16#530]
SCRIPT RUNTIME ERROR
stack traceback:
	...R. Call of Pripyat\gamedata\scripts\smart_terrain.script:586: in function 'select_npc_job'
	...R. Call of Pripyat\gamedata\scripts\smart_terrain.script:535: in function 'update_jobs'
	...R. Call of Pripyat\gamedata\scripts\smart_terrain.script:1058: in function <...R. Call of Pripyat\gamedata\scripts\smart_terrain.script:1005>
 
FATAL ERROR
 
[error] Expression    : !m_error_code
[error] Function      : raii_guard::~raii_guard
[error] File          : C:\projects\xray-16\src\xrScriptEngine\script_engine.cpp
[error] Line          : 569
[error] Description   : ...R. Call of Pripyat\gamedata\scripts\smart_terrain.script:586: attempt to index local 'job_data' (a nil value)

**To Reproduce**
Random

**BugTrap error report**
[OpenXRay_error_report_191218-141528.zip](https://github.com/OpenXRay/xray-16/files/3979743/OpenXRay_error_report_191218-141528.zip)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - OpenXRay Rx64 build 7568, Oct 26 2019
AppVeyor build 558 from commit[443b674ac99c705c8bce2e9ce439f6fe7fed3dd4] branch[HEAD] (built by OpenXRay)

**Comment by Xottab-DUTY** [comment]
Any more info?
Game version? Any mods? How did you installed OpenXRay?)

**Comment by msanchezcordi** [comment]
Hi, game version 1.6.02. Installed Remake v3: https://www.moddb.com/mods/remake. Only that.

**Comment by Xottab-DUTY** [comment]
I can't say if it's our problem or a mod problem.
@msanchezcordi it's better to ask the mod author if he can something about it.

**Comment by Xottab-DUTY** [comment]
There were few fixes related to crashes in mods and stability improvements overall, so I'm closing this issue as outdated. (it was submitted in 2019!)

We can reopen it in case issue is not fixed and still reproducible in the latest engine versions.
