### ISSUE TITLE
xrParticles-related crash in Yanov

### ISSUE THREAD

**Issue by donizettilorenzo** [OpenXRay/xray-16#543]
xrParticles-related crash in Yanov

Reports attached.
[OpenXRay_error_report_200129-010127.zip](https://github.com/OpenXRay/xray-16/files/4128010/OpenXRay_error_report_200129-010127.zip)
[OpenXRay_error_report_200129-010130.zip](https://github.com/OpenXRay/xray-16/files/4128011/OpenXRay_error_report_200129-010130.zip)

**Comment by donizettilorenzo** [comment]
Always near anomalies

**Comment by jjdredd** [comment]
Was anyone able to reproduce this?
@donizettilorenzo  Can you provide a save to reproduce this easier?

**Comment by donizettilorenzo** [comment]
No more encountered since months!

**Comment by jjdredd** [comment]
So can we close this?

**Comment by donizettilorenzo** [comment]
Close!
