### ISSUE TITLE
ui/styles testing

### ISSUE THREAD

**Issue by Chocohex** [OpenXRay/xray-16#549]
Функция ui/styles (помещение альтернативных ХУДов в папку для легкой смены через настройки) не дает ожидаемых результатов на широкоформатном мониторе.

Общие проблемы: 
-Интерфейс "растягивается", возможно движок не читает .ltx файлы предназначенные для широких мониторов.

Пример №1: Перенос интерфейса ЧН напрямую из оригинальной игры (лёгкий перенос основных элементов, без адаптации. Перенос всех ui файлов ЧН дает мгновенный вылет что вполне натурально.)
![explorer_997TO31xUB](https://user-images.githubusercontent.com/42782960/75284584-16cdcc00-57e3-11ea-85ba-4256cb21f646.png)
![explorer_AL9J3lNAlD](https://user-images.githubusercontent.com/42782960/75284596-1b928000-57e3-11ea-8689-cd4d9c688c3a.png)
![ss_chocohex_02-25-20_15-09-43_(dick)](https://user-images.githubusercontent.com/42782960/75284945-affce280-57e3-11ea-9268-bf32269e060f.jpg)

-Миникарта и индикаторы видимости/звука остаются от оригинального интерфейса ЗП. То есть, круглые.
-Шкала радиации не совпадает с картинкой.
-Значки аномальных угроз справа светятся дефолтным радиоактивным знаком из-за их неиспользования
-"Стрелка" шкалы радиации не шевелится когда игрок находится в источнике, в отличие от оригинала ЧН

Пример №2: Сравнение одинакового ХУДа в корневой папке ui и ui/styles

Вставление своего ХУДа в ui
![ss_chocohex_02-25-20_15-17-06_(dick)](https://user-images.githubusercontent.com/42782960/75286522-ad4fbc80-57e6-11ea-8d7e-81f71d29fd42.jpg)
![ss_chocohex_02-25-20_15-17-02_(dick)](https://user-images.githubusercontent.com/42782960/75286403-7ed1e180-57e6-11ea-9de8-01ef2265153a.jpg)
-Все работает как надо

Теперь переносим в ui/styles. Просто копируем всю папку.
![ss_chocohex_02-25-20_15-16-02_(dick)](https://user-images.githubusercontent.com/42782960/75286629-cc4e4e80-57e6-11ea-9433-b36a0b200061.jpg)
![ss_chocohex_02-25-20_15-16-01_(dick)](https://user-images.githubusercontent.com/42782960/75286627-cbb5b800-57e6-11ea-997c-432bda76bbce.jpg)
-Интерфейс заметно растянулся
-Миникарта сменила координаты под настройки 4:3

**Comment by Xottab-DUTY** [comment]
Проблемы из примера №2 исправил.

Проблемы из первого примера такие:
1. Ты недоперенёс некоторые файлы.
2. Значки аномальных угроз, скорее всего, не работают из-за того, что для них нет текстур и/или не хватает textures_descr.
3. Круглая миникарта зашита в движке и я пока не придумал умного метода определения какую именно миникарту надо рисовать. (круглую или квадратную)

**Comment by xrModder** [comment]
Кстати о UI, добавить возможность выравнивать текст по ширине (как justify в html), восстановить альфа-канал для видео роликов.

**Comment by Xottab-DUTY** [comment]
@xrModder создай, пожалуйста, отдельный issue на этот счёт, потому что эта тема только про систему стилей. 😃

**Comment by xrModder** [comment]
> 3. Круглая миникарта зашита в движке и я пока не придумал умного метода определения какую именно миникарту надо рисовать. (круглую или квадратную)

Возможное решение: добавить новый xml-ключ к zonemap типа type="round" и type="square"

**Comment by xrModder** [comment]
> @xrModder создай, пожалуйста, отдельный issue на этот счёт, потому что эта тема только про систему стилей.

Как скажешь.

**Comment by Chocohex** [comment]
Спасибо за добавление функции рестарта ui, крайне удобная вещь. Инвентарь теперь работает как по маслу, не плющится. Но несколько проблем ещё есть, сделал видео с интерфейсами в папке styles.

https://cdn.discordapp.com/attachments/395914970782760971/683530049718452293/ui_styles.webm

Пример №1 - Обычный HUD
Пример №2 - Обычный HUD но в папке styles, при использовании растягивается
Пример №3 - Прямой порт UI ЧН. В отличии от прошлого раза теперь motion icon из ТЧ включая шкалу выносливости
Пример №4  - Пользовательский худ со своей текстурой и пути к ней. Движок не признает текстуру и использует дефолтную

Тестировалось на конфигурации Release.

**Comment by Xottab-DUTY** [comment]
1. Да
2. 16:9 не видит и включает 4:3. Странно. Попробую разобраться, почему так происходит.
3. С motion icon из ТЧ такая же проблема, как и с круглой миникартой. Это зашито в движке и здесь я тоже ещё не придумал умного метода, который будет показывать motion icon только тогда, когда надо. Так как эти две проблемы не просто похожи, но ещё и связаны, то, пока что, возможно стоит попробовать круглую миникарту от ЗП, только с текстурой под стиль ЧН. :)
4. Да, не весь UI полностью перезагружается. Это будет дорабатываться.

P.S. Чтобы не вводить постоянно `ui_restart` вручную, ты можешь в ui_mm_opt.xml заменить у опции стиля `depend="restart"` на `depend="ui"`. Сейчас там стоит обычный `restart` потому что ui_restart ещё немного недоработан.

**Comment by xrModder** [comment]
@**Xottab-DUTY**, не подскажешь как перенести круглую миникарту на ТЧ?

**Comment by Xottab-DUTY** [comment]
@xrModder, просто скопировать класс CUIMiniMap из ЗП. Потом, там надо будет сделать, чтобы метки тоже по кругу рисовались, а не по квадрату. Но, я пока ещё не нашёл где это управляется.

**Comment by Xottab-DUTY** [comment]
> 16:9 не видит и включает 4:3. Странно. Попробую разобраться, почему так происходит.

Не смог воспроизвести. Так не должно происходить. Попробуй проверить ещё раз.

> С motion icon из ТЧ такая же проблема, как и с круглой миникартой. Это зашито в движке и здесь я тоже ещё не придумал умного метода, который будет показывать motion icon только тогда, когда надо. Так как эти две проблемы не просто похожи, но ещё и связаны, то, пока что, возможно стоит попробовать круглую миникарту от ЗП, только с текстурой под стиль ЧН. :)

Motion icon всё ещё захардкоден, но миникарту я исправил. Теперь движок сам определяет, когда нужно рисовать квадратную, а когда круглую.

> Да, не весь UI полностью перезагружается. Это будет дорабатываться.

Теперь всё самое нужное должно перезагружаться. Разве что, по мелочи некоторые элементы всё ещё не перезагружаются. Тоже будет доделываться.

**Comment by Xottab-DUTY** [comment]
@Chocohex, привет. Можешь потестить со свежей версией движка и сказать, чего не хватает, где багует или всё работает хорошо?



> Спасибо за добавление функции рестарта ui, крайне удобная вещь. Инвентарь теперь работает как по маслу, не плющится. Но несколько проблем ещё есть, сделал видео с интерфейсами в папке styles.
> 
> [cdn.discordapp.com/attachments/395914970782760971/683530049718452293/ui_styles.webm](https://cdn.discordapp.com/attachments/395914970782760971/683530049718452293/ui_styles.webm)
> 
> Пример №1 - Обычный HUD Пример №2 - Обычный HUD но в папке styles, при использовании растягивается Пример №3 - Прямой порт UI ЧН. В отличии от прошлого раза теперь motion icon из ТЧ включая шкалу выносливости Пример №4 - Пользовательский худ со своей текстурой и пути к ней. Движок не признает текстуру и использует дефолтную
> 
> Тестировалось на конфигурации Release.

Я, вот, не помню, поправил ли я все моменты здесь или нет.

**Comment by Xottab-DUTY** [comment]
Большинство багов по стилям уже починены и с системой стилей теперь можно взаимодействовать из Lua.
Даже если остались какие-то баги, которые упомянуты тут, но не исправлены – всё равно закрою эту ишью, для уменьшения количества старых ишью :)
А баги, рано или поздно, починятся)
