### ISSUE TITLE
No actor shadow on R2/R3/R4

### ISSUE THREAD

**Issue by nitrocaster** [OpenXRay/xray-16#57]
Works on R1.

**Comment by SkyLoaderr** [comment]
You can copy code from OGSE or Lost Alpha,

**Comment by ghost** [comment]
Hey skyLoaderr, I had indeed copied some code from xray-dev by K.D. for actor shadows a long while back and submitted it but apparently it didn't meet the coding conventions. I'll clean it up and resubmit it as this repo seems to be abandoned at this point, and if it is I would like to take a larger role in it and help with it as I technically co-founded it.

**Comment by CrossVR** [comment]
@Swartz27 The project is not abandoned yet, I'm currently working on completing the OpenGL renderer.

**Comment by ghost** [comment]
@Armada651 Glad to hear it :) Are you currently able to add code directly? If not I'll see if I can give you access rights to do so.

**Comment by Xottab-DUTY** [comment]
Added with 044d38318cc60c9707af66100e6ccc11878f967e
