### ISSUE TITLE
gentoo: Error while loading shared libraries

### ISSUE THREAD

**Issue by jeroglifo** [OpenXRay/xray-16#589]
Hi, 
after compile the project in gentoo linux, I copied the root game files from wine location   ~/.wine/drive_c/Program Files/GSC Game World/S.T.A.L.K.E.R. - Call of Pripyat/   to   ~/.local/share/GSC/SCOP/

but, if I try to start the engine, I get the next output:

```
$ /usr/games/xr_3da 
/usr/games/xr_3da: error while loading shared libraries: xrEngine.so: cannot open shared object file: No such file or director
```

There is no additional description over what could be and I have not idea what happens, 
please, somebody so kind to help me?

**Comment by shifu-ukraine** [comment]
Дело в том, что эти либы собрались и положились в /usr/lib, а должны были в /usr/lib64! Запустить можно так: LD_LIBRARY_PATH=/usr/lib /usr/games/xr_3da. Но это не правильно. В арче может так и работает, но в генте - нет.

**Comment by jeroglifo** [comment]
Thank you very much mihalych127. Did work but with text problems, I'm Spanish.
The next problem is, that I can't read the text in my language. Each single text is covered of a yellow rectangle.

[EDIT]
There is text problems but only at max resolution 1680x1050, at lower resolutions work fine
[/EDIT]
Which tools or IDE are you using to program and compile on linux?

Thanks in advance

**Comment by Xottab-DUTY** [comment]
> The next problem is, that I can't read the text in my language. Each single text is covered of a yellow rectangle.
> 
> [EDIT]
> There is text problems but only at max resolution 1680x1050, at lower resolutions work fine
> [/EDIT]
> Which tools or IDE are you using to program and compile on linux?
> 
> Thanks in advance

@jeroglifo, can you create another issue with bug-report of the problem with screenshots?

**Comment by shifu-ukraine** [comment]
> @Xottab-DUTY linked a pull request that will close this issue 1 hour ago
> Cmake fix #591 

И как заставить это работать? Я этот коммит видел, синхронизировал свой локальный репозиторий, пересобрал и оно не работает. Пришлось использовать старый свой [ебилд](https://drive.google.com/open?id=12Msr0e5fDS1NxbFJ9rKxxv7qf3SFzb2U) для сборки, иначе переопределить то как?

**Comment by Xottab-DUTY** [comment]
Откуда ты синхронизировал, с каким репозиторием?

**Comment by shifu-ukraine** [comment]
> Откуда ты синхронизировал, с каким репозиторием?
```
git pull https://github.com/OpenXRay/xray-16.git --recurse-submodules
```
С вашим же. Правда было три часа ночи...

**Comment by Xottab-DUTY** [comment]
Это не коммит, а пул-реквест. Коммита в репозитории ещё нет.

**Comment by shifu-ukraine** [comment]
А когда будет? Да! Еще было бы не плохо иметь возможность переопределять папку BINDIR, т.к. в генту игры по умолчанию ставятся в папку /usr/games/bin.

**Comment by Xottab-DUTY** [comment]
Когда пул-реквест примут)

**Comment by shifu-ukraine** [comment]
> Когда пул-реквест примут)
Понял, ждём...

**Comment by 007exe** [comment]
Ну остаётся только Прапора победить и можно будит нормально конфигурить проект 
cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_INSTALL_BINDIR=/usr/games ...

**Comment by 007exe** [comment]
mihalych127 Скинь с гены выхлоп $PATH

**Comment by shifu-ukraine** [comment]
> mihalych127 Скинь с гены выхлоп $PATH

Вот:
```
~ $ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:/usr/lib/llvm/9/bin:/usr/games/bin
```

**Comment by 007exe** [comment]
Гыы gentoo /usr/games/bin
Ubuntu /usr/games
Arch -

**Comment by shifu-ukraine** [comment]
> Гыы gentoo /usr/games/bin

Да оно вроде как и логично. Типа можно /usr/games в отдельный раздел, т.к. туда и файлы самой игры ложить можно.

**Comment by Nightscreamer** [comment]
> Гыы gentoo /usr/games/bin
> Ubuntu /usr/games
> Arch -

Для разнообразия ALT:
$ rpm -E %_libdir
/usr/lib64
$ rpm -E %_bindir
/usr/bin
$ rpm -E %_prefix
/usr
$ rpm -E %_gamesbindir
/usr/games
$ rpm -E %_gamesdatadir
/usr/share/games

$ lsb_release -a
LSB Version:    n/a
Distributor ID: ALT
Description:    ALT Workstation K 9.0  (Centaurea Pineticola)
Release:        9.0
Codename:       CentaureaPineticola

**Comment by Nightscreamer** [comment]
> > Гыы gentoo /usr/games/bin
> 
> Да оно вроде как и логично. Типа можно /usr/games в отдельный раздел, т.к. туда и файлы самой игры ложить можно.

В Альт Линукс:
бинари игр в  /usr/games
а данные игр в /usr/share/games
если вами интересно )
