### ISSUE TITLE
Cannot create OpenGL context: Could not create GL context: GLXBadFBConfig

### ISSUE THREAD

**Issue by shifu-ukraine** [OpenXRay/xray-16#594]
Immediately at start, it crashes with an error.

**BugTrap error report**

console:

```~ $ xr_3da
! Couldn't create surface from image: Couldn't open logo.bmp
OpenXRay Rx64 build 7763, May  9 2020
Custom build from commit[31ce0e5cb1882c1029fee3f5bdf2b822af0e27a1] branch[HEAD]
 
command line 

* CPU features: RDTSC, MMX, SSE, SSE2, SSE3, SSE4.1, SSE4.2
* CPU cores/threads: 4/4
* CPU current freq: 1440 MHz

Initializing File System...
using fs-ltx fsgame.ltx
FS: 28301 files cached 29 archives, 8Kb memory used.
Init FileSystem 0.310711 sec
-----loading \home\misha\.local\share\GSC\SCOP\gamedata\configs\system.ltx
-----loading \home\misha\.local\share\GSC\SCOP\gamedata\configs\system.ltx
Starting INPUT device...
No joysticks available
Loading module: xrRender_GL
~ Cannot create OpenGL context: Could not create GL context: GLXBadFBConfig
Available render modes[1]:
Executing config-script "user.ltx"...
! Cannot open script file [user.ltx]
 
FATAL ERROR
 
[error] Expression    : setupSelectedRenderer
[error] Function      : InitializeRenderers
[error] File          : /var/calculate/tmp/portage/games-fps/openxray-9999/work/openxray-9999/src/xrEngine/EngineAPI.cpp
[error] Line          : 128
[error] Description   : Can't setup renderer
 

stack trace:

xrDebug::GatherInfo(char*, unsigned long, ErrorLocation const&, char const*, char const*, char const*, char const*)
xrDebug::Fail(bool&, ErrorLocation const&, char const*, char const*, char const*, char const*)
CEngineAPI::InitializeRenderers()
CEngineAPI::Initialize()
RunApplication()
xr_3da(+0x1769) [0x561169907769]
xr_3da(+0x14be) [0x5611699074be]
/lib64/libc.so.6(__libc_start_main+0xeb) [0x7fa15cd93e0b]
xr_3da(_start+0x2a) [0x5611699075aa]
Ловушка трассировки/останова
```

Crash report:
[openxray.log](https://drive.google.com/open?id=1cZS1QjCueCCXyN5j5MuyuODtdWOBRZfM)

**Desktop (please complete the following information):**
 - OS: [Calculate Linux Desktop]
 - OpenXRay build version [Custom build from commit[31ce0e5cb1882c1029fee3f5bdf2b822af0e27a1] branch[HEAD] ]

**Additional context**
ebuild file:
[openxray-9999.ebuild](https://drive.google.com/open?id=12Msr0e5fDS1NxbFJ9rKxxv7qf3SFzb2U)

**Comment by Xottab-DUTY** [comment]
Minimal OpenGL version supported by OpenXRay is 4.1. Does your configuration support it?

**Comment by shifu-ukraine** [comment]
> Minimal OpenGL version supported by OpenXRay is 4.1. Does your configuration support it?
```
~ $ glxinfo | grep "OpenGL version string"
OpenGL version string: 2.1 Mesa 19.3.5
```
No, does not support. No luck... Sorry, but I didn’t see anything about it in the readme file.

**Comment by shifu-ukraine** [comment]
> Minimal OpenGL version supported by OpenXRay is 4.1

@Xottab-DUTY эту информацию желательно бы добавить таки в README.md. А то не только я могу так на детские грабли наступить... Компилировать такой проект на двухьядерном ноутбучном процессоре настоящая боль)

**Comment by Xottab-DUTY** [comment]
> No, does not support. No luck... Sorry, but I didn’t see anything about it in the readme file.

Sorry, ~~I'll mention it somewhere~~ I specified the required minimum version in our wiki.

**Comment by Xottab-DUTY** [comment]
@mihalych127, могу сейчас только пожелать продолжать следить за проектом. Возможно, в скором времени версия OpenGL будет понижена, работы ведутся. =)
