### ISSUE TITLE
Impossible to compile on Alpine Linux(musl libc)

### ISSUE THREAD

**Issue by illiliti** [OpenXRay/xray-16#622]
-DMEMORY_ALLOCATOR=standard should be specified by default for musl libc because it doesn't support custom memory allocators

Non-portable functions should be removed or replaced with alternatives(e.g libexecinfo)
* src/xrCore/FS_internal.h src/xrCore/LocatorAPI.cpp
  - sys_errlist glibcism
* src/xrCore/xrDebug.cpp
  - execinfo.h glibcism
* src/xrCore/_math.cpp
  - fpu_control.h glibcism

Cmake generates invalid `<build directory>/src/xrGame/cotire/xrGame_C_prefix.c` with missing includes
```
#include <string.h>
#include <stddef.h>
#include <stdlib.h>
```

Cmake should search include path for `directfb` in `/usr/include/directfb` too, not just `/usr/include`

**Comment by illiliti** [comment]
> Cmake generates invalid `<build directory>/src/xrGame/cotire/xrGame_C_prefix.c` with missing includes
> 
> ```
> #include <string.h>
> #include <stddef.h>
> #include <stdlib.h>
> ```
> 
> Cmake should search include path for `directfb` in `/usr/include/directfb` too, not just `/usr/include`

i solved these issues by removing `directfb` and `fortify-headers` packages

i also found missing include `#include <signal.h>` in src/xrCore/xrDebug.cpp

**Comment by Xottab-DUTY** [comment]
@illiliti, can you test if the game is playable with musl libc?

**Comment by Xottab-DUTY** [comment]
Also, just a small comment:
> Cmake should search include path for directfb in /usr/include/directfb too, not just /usr/include

It's SDL2 that tries to include directfb header... I fixed compilation errors by just removing some SDL2 headers from compilation.

I'm not sure if this is our issue and, maybe, it should be submitted to SDL2 repository.

**Comment by illiliti** [comment]
Thanks for working on this!

> can you test if the game is playable with musl libc?

Good question! I don't use alpine anymore(but i still use musl!) since I moved on to a more minimal system a long time ago. Building some xray-16 dependencies might be quite challenging there... I'll try to look into it, but can't promise anything
