### ISSUE TITLE
ebuild

### ISSUE THREAD

**Issue by A-So-Nya** [OpenXRay/xray-16#623]
i've written ebuild that actually seems to work if anyone is interested https://github.com/nightloli/NightLoliRepo/blob/master/games-fps/openxrayx16/openxrayx16-9999.ebuild
didn't find it anywhere on the Internet
It pools the last dev version from github, builds and installs
So now you can install it with portage on your system without bypassing it
I don't think it's written in the right way since i didn't get how to make it work with cmake.eclass buit i managed to build it and launch on my gentoo
(doen's build with lto on gcc 9.3 for me btw, it can be some other flags breaking things though, don't think you are interested in supporting flags i use, since they are known to break things)
Sorry if that's not the right place to write about that, i just thought someone might need it

**Comment by RarogCmex** [comment]
@nightloli Thanks, I've thought about writing ebuild.
[Rus] Спасибо, тоже думал о том, чтобы написать ебилд.

**Comment by Xottab-DUTY** [comment]
Let's track this in #1403 and I'll close this to reduce the number of issues.
