### ISSUE TITLE
RPM package for openSUSE

### ISSUE THREAD

**Issue by mnhauke** [OpenXRay/xray-16#628]
I just want to make you aware that I have created a package for openSUSE.
https://build.opensuse.org/package/show/games/openxray
https://build.opensuse.org/package/view_file/games/openxray/openxray.spec?expand=1

openSUSE users now can get the package from: 
https://software.opensuse.org/package/openxray?search_term=openxray

openSUSE users now can install OpenXray either via adding the games repository...
```
sudo zypper ar obs://games games
sudo zypper ref
sudo zypper in openxray
```

... or by searching the software search and then using the 1-click installer...
https://software.opensuse.org/package/openxray?search_term=openxray

**Comment by Xottab-DUTY** [comment]
@mnhauke, thank you!
Can you update the description of the package?
To this:
```
OpenXRay is an improved version of the X-Ray Engine, the game engine used in the world-famous S.T.A.L.K.E.R. game series by GSC Game World.
 
Currently the following games are supported:
* S.T.A.L.K.E.R.: Call of Pripyat
* S.T.A.L.K.E.R.: Clear Sky
 
To play one of the S.T.A.L.K.E.R. games with OpenXRay you need the
original game files.
See: %{_docdir}/openxray/README.SUSE for details.
```

What I've changed:
1. OpenXray -> OpenX**R**ay (O, X and R letters should be capital)
2. Removed Shadow of Chernobyl because it's not supported.
3. `S.T.A.L.K.E.R. -` changed to `S.T.A.L.K.E.R.:` (colon merged with the dot instead of a hyphen)
4. S.T.A.L.K.E.R -> S.T.A.L.K.E.R. (forgotten last dot)

**Comment by mnhauke** [comment]
@Xottab-DUTY done...
https://build.opensuse.org/request/show/820433

**Comment by Xottab-DUTY** [comment]
@mnhauke you forgot one R here:
![image](https://user-images.githubusercontent.com/2989212/87231843-e8d4d700-c3d3-11ea-9b33-a34ad23bfa9d.png)

**Comment by mnhauke** [comment]
@Xottab-DUTY should be fixed now
