### ISSUE TITLE
Close sleep dialog with ESC key

### ISSUE THREAD

**Issue by nitrocaster** [OpenXRay/xray-16#63]

**Comment by xobah** [comment]
Hello, talk dialog or window dialog?

**Comment by nitrocaster** [comment]
That refers to sleep dialog, but may also appear somewhere else.

**Comment by xobah** [comment]
This is no engine-change, you need to add a callback to ui_sleep dialog.script

**Comment by xobah** [comment]
[Google translate]
Changing class CUIScriptWnd may affect the original scripts of the game, for example, ui_freeplay_dialog.script:
when you click Yes - the game add info_portion pri_a28_actor_in_zone_leave,
if you click No -  the game add info_portion pri_a28_actor_in_zone_stay.
If you add the closing of the window by the ESC key - in this case we do not receive any info_portion.
About various modifications silent.

**Comment by nitrocaster** [comment]
Agree.

**Comment by xobah** [comment]
[Google Translate] Add a callback to ui_sleep dialog.script? Or change CUIScriptWnd?

**Comment by nitrocaster** [comment]
Script callback would be sufficient, I think.

**Comment by xobah** [comment]
132-141 lines:
https://gist.github.com/xobah/6c0ac935534a374702e9

**Comment by nitrocaster** [comment]
Could you please submit a pull request? That would be your own contribution.

**Comment by xobah** [comment]
Like I did. All right?

**Comment by nitrocaster** [comment]
Seems to be right, I'm going to check it now.
upd: [`7dce40d`](https://github.com/OpenXRay/xray-16/commit/7dce40d25a2cfb55ce7a4ac01d0675e7d111fe93)
