### ISSUE TITLE
Clear Sky: 3D models rendered opaque pitch black

### ISSUE THREAD

**Issue by PeterBadzhakov** [OpenXRay/xray-16#633]
**Describe the bug**
All rendering except skybox and lighting is pitch black on Clear Sky.

**To Reproduce**
1. Download Clear Sky from Steam (Russian Language).
2. Play normally with DX10 maximal settings.
3. Install latest Rx64 and stable Clear Sky gamedata as per official instructions.
4. Select 1920x1080, maximal settings, DX10.
5. Set Object Quality to maximum, Rendering and Lighting distance to 1/2, Grass to minimum.
6. Restart game.
7. Start new game.
8. Everything is black but gameplay functions (sound and controls).

Note: skipping steps 4 and 5 makes a normally playable Clear Sky but at lower graphical settings than were originally set at step 2.
Note: Game is certainly running on the dedicated Nvidia GPU.

**Expected behavior**
Playable Clear Sky at DX10, 1920x1080, maximum settings tweaked from Advanced options.

**Screenshots**
https://mega.nz/file/woshiDAQ#uGC367loLgvwrzmfRJvgwm9Uy7i11-2nO-O_YyXIuCY
https://mega.nz/file/tplxGD6C#WJItgM21RNEkae0ISoXa7TEmi6yZxEys6L-L8J8pJGE

**BugTrap error report**
No crash report. Uploading entire folder.
https://mega.nz/file/F5sFyZSQ#TFhhtwuv2EcIOA3T7KAAJk54WHxPDh4jgrMq8kt490c

**Desktop (please complete the following information):**
OS: Windows 10 Education
ASUS TUF FX505DT
Ryzen 3750H
GTX 1650 (not max-q)
2x 8GB 2400MHz RAM
120Hz Display

**Additional context**
Render r4 also makes everything black but does not work even with default settings.

**Comment by Xottab-DUTY** [comment]
I believe this should be fixed in the latest December release. Please, tell us if it's not!

**Comment by CryoManne** [comment]
> I believe this should be fixed in the latest December release. Please, tell us if it's not!

December 2021 RC1 - До сих пор не исправлено. Баг проявлется при включении антиалиасинга на DX10
