### ISSUE TITLE
1280x1024 resolution detection completely issued

### ISSUE THREAD

**Issue by vmech** [OpenXRay/xray-16#642]
src/xrEngine/x_ray.cpp строка 62:
    else if (h <= 1024)

ЗЫ. Большой шрифт слишком большой для этого разрешения. Верните владельцам 5:4 нормальные условия существования, пожалуйста. А то 12 лет кривых костылей из одного движка в другой - реально задолбало уже...

**Comment by Xottab-DUTY** [comment]
@vmech можешь прислать скриншот этого безобразия?)

**Comment by vmech** [comment]
@Xottab-DUTY, пожалуйста.
![](https://i.imgur.com/WZp3jGJ.jpg)
![](https://i.imgur.com/3Rq9AcJ.jpg)
![](https://i.imgur.com/39EdPl3.jpg)
![](https://i.imgur.com/TLuUno7.jpg)
![](https://i.imgur.com/2EuohXc.jpg)

**Comment by vmech** [comment]
@Xottab-DUTY, то же самое, но со средними шрифтами (все ссылки **texture1600** в **fonts.ltx** заменены на ui_font_xxx_**1024**, вместо ui_font_xxx_**1600**)
![](https://i.imgur.com/t7Tvfuf.jpg)
![](https://i.imgur.com/LqVD47o.jpg)
![](https://i.imgur.com/vPlfWi4.jpg)
![](https://i.imgur.com/gzG1eY8.jpg)
![](https://i.imgur.com/oDEI82u.jpg)

**Comment by Xottab-DUTY** [comment]
@vmech, готово! :D

**Comment by klaxons1** [comment]
Быстро фиксите,однако
