### ISSUE TITLE
Green screen instead of game intro

### ISSUE THREAD

**Issue by Nemial** [OpenXRay/xray-16#647]
Когда начинаешь новую игру, вместо игровой заставки просто зелёный экран.

И такая же проблема в настройках. 
![Снимок экрана_2020-07-12_17-50-52](https://user-images.githubusercontent.com/18151125/87250883-55011a80-c468-11ea-8f2c-2c4ff7564b28.png)

**OS**
Slackware Current(x86_64)

**OpenXRay Version:**
730-july-preview

**OpenXRay Log:**
[openxray_nemial.log](https://github.com/OpenXRay/xray-16/files/4908882/openxray_nemial.log)

GOG сборка игры.

**Comment by TheRadioGuy** [comment]
Translated version:

**Green rectangle instead of game's intro**
Also this happens in settings.

GOG version of game

**Comment by Eanmos** [comment]
I've manage to reproduce the bug. When the green screen appears the following message is seen in log:

```
intro_start intro_game
Invalid video stream: 0x500
```

This leads to file `xrRenderGL/glSH_Texture.cpp`:

```cpp
            GLenum err = glGetError();
            if (err != GL_NO_ERROR)
            {
                Msg("Invalid video stream: 0x%x", err);
                xr_delete(pTheora);
                pSurface = 0;
            }
```

The actual GL error appears a few line above:

```cpp
            glGenBuffers(1, &pBuffer);
            glBindBuffer(GL_PIXEL_UNPACK_BUFFER, pBuffer);
```

Calling the `glBindBuffer` function sets error to `0x500` which means `GL_INVALID_ENUM`. I don't know what is wrong with the enum. Does anyone know?

And what is interesting the game intro is successfully played if we ignore this error:

```cpp
            glGenBuffers(1, &pBuffer);
            glBindBuffer(GL_PIXEL_UNPACK_BUFFER, pBuffer);
            // Just pop the error from the queue so it
	    // can be ingored later in code.
            (void) glGetError();
```

So we just need to figure out what wrong with this `glBindBuffer` to properly fix the bug. Does anyone have some ideas?
