### ISSUE TITLE
Не работают быстрые сохранения в Зов Припяти

### ISSUE THREAD

**Issue by Nemial** [OpenXRay/xray-16#648]
**Описание**
Некоторые быстрые сохранения не работают, когда их загружаешь. У меня такое происходит, когда я быстро сохраняюсь при сообщении о начале выброса или во время самого выброса. Эти сохранения не работают, если с них потом загружаться, так как при их загрузке игра просто вылетает. И пару раз происходило такое совсем в разных местах, когда даже не было выброса.

**Log OpenXRay:**
[openxray_nemial.log](https://github.com/OpenXRay/xray-16/files/4908897/openxray_nemial.log)

**OS**
Slackware Current(x86_64)

**OpenXRay Version:**
730-july-preview

**Comment by TheRadioGuy** [comment]
**Description**
Some quick saves don't work when you load them. It often happens when I'm saving when get message about emission or during the emission. When I load these saves, the game just crashes. It also has happenned without emission.

**Comment by eagleivg** [comment]
Исправлено в https://github.com/OpenXRay/xray-16/commit/edbaac6c3639077e89f4e568145489630c2ce41c
