### ISSUE TITLE
New Bug

### ISSUE THREAD

**Issue by twiggs666** [OpenXRay/xray-16#649]
[OpenXRay_error_report_200712-183210.zip](https://github.com/OpenXRay/xray-16/files/4909912/OpenXRay_error_report_200712-183210.zip)
**Describe the bug**

**To Reproduce**
1. Go to '.'
2. Go to '..'
3. Go to '...'

**Expected behavior**

**Screenshots**

**BugTrap error report**
Please, add a crashreport if you have it. It should be located in `_appdata_/reports` folder

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 or Ubuntu 18.10]
 - OpenXRay build version [e.g. 421]

**Additional context**

**Comment by Xottab-DUTY** [comment]
Please, make normal description and then reopen.
