### ISSUE TITLE
libODE.so Unresolved dependencies

### ISSUE THREAD

**Issue by antiuser** [OpenXRay/xray-16#650]
Im install latest version OpenXRay make a Fedora package and when i try to install this package i get an error
```
error: Failed dependencies:
	libODE.so()(64bit) is needed by OpenXRay-1.6.02-1.x86_64

```

**Comment by 007exe** [comment]
How do you create a package?

**Comment by Xottab-DUTY** [comment]
@antiuser any updates?

**Comment by Xottab-DUTY** [comment]
@antiuser bump
