### ISSUE TITLE
Падение FPS из-за ящика

### ISSUE THREAD

**Issue by Masterkatze** [OpenXRay/xray-16#651]
Чистое небо, болота, механизаторский двор, самое большое здание, в его западной части в углу есть разбиваемый кейс с лутом, лежит слева от большого ящика за доской. Упал на него, верхняя половинка кейса осталась на земле а нижняя вместе с содержимым провалилась под землю и фпс стал околонулевой. Проблема сохраняется после сохранения (в аттаче), повторить баг повторно не удалось.

Arch Linux, Custom build from commit[ce9ccfc0caa9f0274dadb74d009634c8674464a1] branch[xd_dev]

[Savegame](https://github.com/OpenXRay/xray-16/files/4927558/17.zip)
[openxray.log](https://github.com/OpenXRay/xray-16/files/4927580/openxray_orange.log)

**Comment by Xottab-DUTY** [comment]
Скорее всего, сохранение уже устарело, так что я закрою проблему.
Но она, скорее всего, связана с #731. Возможно, даже, проблема как раз и кроется `box_collider::_stab`.
