### ISSUE TITLE
Broken compatibility for chopper mission in CoP

### ISSUE THREAD

**Issue by Dum4G** [OpenXRay/xray-16#654]
After the final cutscene where Strelok and Kovalsky crouch next to the cover the game can't perform it's xrDestroy thing and crashes. Also, there's a point where Strelok route gets broken so he just runs into weird place and ignores any enemy trying to attack him, then goes back to squad after few dialogues. If he crossed the psyzone and you saveload the script gets broken then, Strelok just gets wiped out from the map in a few seconds. Basically three bugs in the same area, sorry.

1. Grab my savefile and start mission like usual
2. On the wide street with a few zombies something wrong will happen to Strelok, he will run without waiting for squad through the archway to the kindergarten (?) territory. Follow him and kill the jerboas. 
3. Cross the psyzone and kill the sniper. Don't save at this point.
4. Kill the rest of fanatics in cinemapark
5. Strelok will stand next to the fence behind the cinemapark and dream of meaning of existance till our squad tells us "we have to go!"
6. Protect Strelok from newly spawned sniper and approaching fanatics, get back to squad
7. Proceed to hellicopters like usual
8. No matter how many fanatics will be killed and how many people will stay alive the game will crash the same. If you literally wipe the area there's a chance to see 
`! [LUA] Cannot add animation [cr_idle_2_2]: global selector is set for object [sim_default_monolith_334822], in_smart_cover returned [true]!`
before the stacktrace. Renderer switch doesn't change much

**Expected behavior**
Whatever happens next in original game. This is my first CoP playthrough.

**BugTrap error report**
https://yadi.sk/d/RdFMPJcIwBqL9g
**Savefiles**
[savedgames.zip](https://github.com/OpenXRay/xray-16/files/5000545/savedgames.zip)
[user.ltx](https://github.com/OpenXRay/xray-16/files/5000569/user.txt)

What matters is
`C:\WINDOWS\System32\ucrtbase.dll at 00007FFA9D184E9C strnlen() + 60 byte(s)
C:\WINDOWS\System32\ucrtbase.dll at 00007FFA9D17648B Gettnames() + 91 byte(s)
C:\WINDOWS\System32\ucrtbase.dll at 00007FFA9D1744EC _stdio_common_vsprintf_s() + 2076 byte(s)
C:\WINDOWS\System32\ucrtbase.dll at 00007FFA9D17419C _stdio_common_vsprintf_s() + 1228 byte(s)
C:\WINDOWS\System32\ucrtbase.dll at 00007FFA9D173F8D _stdio_common_vsprintf_s() + 701 byte(s)
C:\Gaemz\S.T.A.L.K.E.R. Call of Pripyat\bin\xrCore.dll at 00007FFA65F0FF23 Msg() + 99 byte(s)
C:\Gaemz\S.T.A.L.K.E.R. Call of Pripyat\bin\xrGame.dll at 00007FFA60346D34 xrFactory_Destroy() + 653796 byte(s)
C:\WINDOWS\SYSTEM32\VCRUNTIME140.dll at 00007FFA8D071030
C:\WINDOWS\SYSTEM32\VCRUNTIME140.dll at 00007FFA8D0743A8 is_exception_typeof() + 8456 byte(s)
C:\WINDOWS\SYSTEM32\ntdll.dll at 00007FFA9FC20666 RtlCaptureContext() + 1382 byte(s)
C:\Gaemz\S.T.A.L.K.E.R. Call of Pripyat\bin\xrGame.dll at 00007FFA6008D3A7 CxImage::`copy constructor closure'() + 2779751 byte(s)
C:\Gaemz\S.T.A.L.K.E.R. Call of Pripyat\bin\xrGame.dll at 00007FFA600B39EA CxImage::`copy constructor closure'() + 2937002 byte(s)
C:\Gaemz\S.T.A.L.K.E.R. Call of Pripyat\bin\xrGame.dll at 00007FFA6008D058 CxImage::`copy constructor closure'() + 2778904 byte(s)
C:\Gaemz\S.T.A.L.K.E.R. Call of Pripyat\bin\xrGame.dll at 00007FFA6008D3A7 CxImage::`copy constructor closure'() + 2779751 byte(s)
C:\Gaemz\S.T.A.L.K.E.R. Call of Pripyat\bin\xrGame.dll at 00007FFA5FA197CF
C:\Gaemz\S.T.A.L.K.E.R. Call of Pripyat\bin\xrGame.dll at 00007FFA5FA195A2
C:\Gaemz\S.T.A.L.K.E.R. Call of Pripyat\bin\xrGame.dll at 00007FFA5F89C95F
C:\Gaemz\S.T.A.L.K.E.R. Call of Pripyat\bin\xrEngine.dll at 00007FFA864FC20B CObjectList::SingleUpdate() + 139 byte(s)
C:\Gaemz\S.T.A.L.K.E.R. Call of Pripyat\bin\xrEngine.dll at 00007FFA864FC5FB CObjectList::Update() + 523 byte(s)
C:\Gaemz\S.T.A.L.K.E.R. Call of Pripyat\bin\xrEngine.dll at 00007FFA864A2E53 IGame_Level::OnFrame() + 35 byte(s)
C:\Gaemz\S.T.A.L.K.E.R. Call of Pripyat\bin\xrGame.dll at 00007FFA5FC145F4
C:\Gaemz\S.T.A.L.K.E.R. Call of Pripyat\bin\xrEngine.dll at 00007FFA86423C9E CRenderDevice::CSecondVPParams::IsSVPFrame() + 1070 byte(s)
C:\Gaemz\S.T.A.L.K.E.R. Call of Pripyat\bin\xrEngine.dll at 00007FFA864231B1 CRenderDevice::FrameMove() + 337 byte(s)
C:\Gaemz\S.T.A.L.K.E.R. Call of Pripyat\bin\xrEngine.dll at 00007FFA864229D0 CRenderDevice::ProcessFrame() + 80 byte(s)
C:\Gaemz\S.T.A.L.K.E.R. Call of Pripyat\bin\xrEngine.dll at 00007FFA86422167 CRenderDevice::PrimaryThreadProc() + 391 byte(s)
C:\WINDOWS\System32\ucrtbase.dll at 00007FFA9D1CFAFF crt_at_quick_exit() + 175 byte(s)
C:\WINDOWS\System32\KERNEL32.DLL at 00007FFA9E437BD4 BaseThreadInitThunk() + 20 byte(s)
C:\WINDOWS\SYSTEM32\ntdll.dll at 00007FFA9FBECED1 RtlUserThreadStart() + 33 byte(s)`

 - OS: Windows 10 1909
 - OpenXRay build version 443

Report applies to Remake 2.1 adoption and it's creator haven't come up with a solution. The mod itself doesn't change mission scripts at all, it's aimed to make graphics better. I'm planning to recompile exact build 443 with appropiate fix, so if it has already been fixed before point me at the relevant commit, please.

**Comment by Dum4G** [comment]
We have tried to set
allow_nil_conversion to true and game_mode to unlock, neither helps

**Comment by Xottab-DUTY** [comment]
I pushed a fix, please test it.
