### ISSUE TITLE
Игра падает при загрузке сохранения в рыжем лесу

### ISSUE THREAD

**Issue by Masterkatze** [OpenXRay/xray-16#656]
Чистое небо, перешёл в рыжий лес, погнался за Стрелком, пришёл на помощь к ведьминому кругу, перебил там псевдособак, сохранился перед атакой кровососа. Если загрузить этот сейв в релизной сборке - игра падает. Если загрузиться в дебаггере и продолжить несколько раз - сейв загрузится, но при повторной попытке сохраниться упадёт снова.

Arch Linux, custom build from commit[0e36e414547870ee80fbf79234112b76dafb2057] branch[xd_dev]

[openxray.log](https://github.com/OpenXRay/xray-16/files/5011188/openxray_orange.log)
[Savegame](https://github.com/OpenXRay/xray-16/files/5011189/87.zip)

**Comment by eagleivg** [comment]
Попробуй обновиться, возможно, это исправлено https://github.com/OpenXRay/xray-16/commit/edbaac6c3639077e89f4e568145489630c2ce41c

**Comment by Xottab-DUTY** [comment]
> Попробуй обновиться, возможно, это исправлено [edbaac6](https://github.com/OpenXRay/xray-16/commit/edbaac6c3639077e89f4e568145489630c2ce41c)

@Masterkatze

**Comment by Masterkatze** [comment]
edbaac6 проблему не решает. 

Вообще, это какой-то странный сейв, его не с первой попытки загрузишь, есть два варианта ошибок, связанных с луа:
1) ERROR: xr_logic: pstor_load_all: not registered type N 249 encountered
С этим вариантом не загружается
2) ERROR: INCORRECT LOAD [_objectred_pursuit_bounty_hunter9898].[0][14]
С этим загружается

Какой вариант попадётся - рандом. Если удалось загрузиться - то падает как при сейве, так и при переходе на другую локацию, либо вообще рандомно вылетает.

Приложил пару логов крашей, когда удалось загрузиться:
[log_random_crash.log](https://github.com/OpenXRay/xray-16/files/5761990/log_random_crash.log)
[log_save_game_crash.log](https://github.com/OpenXRay/xray-16/files/5761991/log_save_game_crash.log)

**Comment by Xottab-DUTY** [comment]
@Masterkatze, вылет всё ещё происходит?

**Comment by Xottab-DUTY** [comment]
Закрою, на всякий случай, по устарелости бага. Много чего починено с того времени было.
