### ISSUE TITLE
lj_vm.sx.o missing when building with clang on linux

### ISSUE THREAD

**Issue by makemefeelgr8** [OpenXRay/xray-16#658]
This is what I get when I try to build using cmake:

```
FAILED: x64/Release/xrLuajit.so 
clang++: error: no such file or directory: 'Externals/CMakeFiles/xrLuajit.dir/lj_vm.sx.o'
```

Previous command ends with the following parameters:
```
-MT Externals/CMakeFiles/xrLuajit.dir/lj_vm.sx.o 
-MF Externals/CMakeFiles/xrLuajit.dir/lj_vm.sx.o.d 
-o Externals/CMakeFiles/xrLuajit.dir/lj_vm.sx.o 
-c Externals/lj_vm.sx
```
As you can see, `lj_vm.sx.o` was generated and converted to `lj_vm.sx`. 
There definitely should be a way to preserve this file.

**Comment by c64skin** [comment]
until it gets fixed properly what is the manual workaround to get around this issue? thanks.

**Comment by Xottab-DUTY** [comment]
First of all, Clang is not supported.

You can try to revert commit ffedc485e2f3fb093df568d5eab33b03141b7651. The revert should help with this issue, but there's no guarantee that other issues with Clang won't appear.

**Comment by c64skin** [comment]
yeah it finally crapped out at xrCore/_types.h , oh well.

**Comment by TarasHots** [comment]
@frakswe what kind of issue do you have with `xrCore/_types.h`?

**Comment by c64skin** [comment]
type define collisions:

In file included from /home/frakswe/source/xray-16/Externals/cximage/../../src/xrCore/xrMemory.h:3:
/home/frakswe/source/xray-16/Externals/cximage/../../src/xrCore/_types.h:7:12: error: no type named 'int8_t' in namespace 'std'; did you mean simply 'int8_t'?
using s8 = std::int8_t;
           ^~~~~~~~~~~
           int8_t
/usr/include/sys/types.h:75:19: note: 'int8_t' declared here
typedef __int8_t                int8_t;

etc.

maybe i could've sorted it but i'm sure there will be more problems ahead and i had to do some coaxing to get this far.

**Comment by makemefeelgr8** [comment]
> First of all, Clang is not supported.
> 
> You can try to revert commit [ffedc48](https://github.com/OpenXRay/xray-16/commit/ffedc485e2f3fb093df568d5eab33b03141b7651). The revert should help with this issue, but there's no guarantee that other issues with Clang won't appear.

Reverting the commit you've mentioned did fix the issue. Thanks! Even after handling clang related bugs LuaJIT still wont compile for android. It used to support cross-compilation some time ago but the manual on theirs website is extremely outdated.
Anyway, feel free to continue where I left off https://github.com/makemefeelgr8/xray-16
