### ISSUE TITLE
Cannot launch Misery (with The Armed Zone)?

### ISSUE THREAD

**Issue by ThatZenoGuy** [OpenXRay/xray-16#662]
[OpenXRay_error_report_200910-171027.zip](https://github.com/OpenXRay/xray-16/files/5200496/OpenXRay_error_report_200910-171027.zip)

This crash/error appears.

**Comment by Xottab-DUTY** [comment]
Misery is currently unsupported due to critical error in the script.
We could make a patch that fixes this in future, probably.
