### ISSUE TITLE
Build fails on Linux.

### ISSUE THREAD

**Issue by PeterBadzhakov** [OpenXRay/xray-16#667]
**Describe the bug**
Building the engine following the instructions fails.

**To Reproduce**
Follow the Linux instructions exactly. cmake .. then sudo make -j8.

**Expected behavior**
A full build of the engine ready to use.

**Build log**
https://pastebin.com/N7HQREms

**Desktop (please complete the following information):**
OS: Manjaro 20.1 Mikah
CPU: AMD Ryzen 7 3750H with Radeon Vega Mobile Gfx @ 8x 2.3GHz
GPU: AMD RAVEN (DRM 3.38.0, 5.8.10-lqx1-1-lqx, LLVM 10.0.1)
RAM: 2990MiB / 13992MiB

**Additional context**
Build ran with no CXXFLAGS or CFLAGS set. I have all the dependencies installed.

**Comment by Xottab-DUTY** [comment]
Please, try to insert  this code into `src/Common/PlatformLinux.inl` file:
```cpp
#define _sys_errlist sys_errlist
```
Does it help?

**Comment by PeterBadzhakov** [comment]
I'm afraid it didn't work.

https://pastebin.com/cdEfd0yi

**Comment by Xottab-DUTY** [comment]
*Just googled about it: some systems deprecated sys_errlist and some of them just don't have it.*

Instead of the previous solution, temporary insert this code into PlatformLinux.inl:
```cpp
#define _sys_errlist "unknown sys_errlist error"
```

**Comment by PeterBadzhakov** [comment]
It's gone but I'm going down a rabbit hole.

https://pastebin.com/m0ssrJz3

**Comment by Xottab-DUTY** [comment]
Oh... A huge sorry! I was a bit inattentive and suggested wrong code.
This should work:
```cpp
inline const char* xr_sys_errlist[100] = {};
#define _sys_errlist xr_sys_errlist
```

**Comment by PeterBadzhakov** [comment]
Thanks! Still fails, though.

https://pastebin.com/1fqFjQMq

**Comment by Xottab-DUTY** [comment]
And again sorry! 😃 Let's say that it's too late for me... (3 AM)

Just add the `inline` keyword before `const char* .......`

**Comment by PeterBadzhakov** [comment]
Very well! It worked! Thank you.

Now I must figure out how to take a linux compilation, and run the engine in Windows, haha. Instead of using visual studio.

**Comment by Xottab-DUTY** [comment]
> Now I must figure out how to take a linux compilation, and run the engine in Windows, haha. Instead of using visual studio.

Whaaaat? 😄

**Comment by PeterBadzhakov** [comment]
I don't know how to take what I just compiled and run it on Windows. I don't know how to compile at "-march=native -O3" in visual studio so I'm using Linux transitively, haha.

**Comment by Xottab-DUTY** [comment]
Build you could just compile it using Visual Studio and its MSVC compiler natively, by opening `engine.sln` file in the `src` dir. (CMake-based builds doesn't support Windows)
We have an instruction on how to build on Windows :)

**Comment by PeterBadzhakov** [comment]
Thanks, I'll see how optimisations work in visual studio.
