### ISSUE TITLE
Debug renderer performance

### ISSUE THREAD

**Issue by nitrocaster** [OpenXRay/xray-16#67]
Debug render works _extremely_ slow, have to be optimized.

**Comment by tamlin-mike** [comment]
See my comment in "Stuttering issue: I think I know the cause #131".

Once crossing a border, I got pretty much release-build framerates, in a debug-build, while previously they had been what felt like 2-4 FPS.

As noted in the referred pos, I have the savegame for it, and I plan to profile the hell out of it, but f you want a copy just holler.

**Comment by nitrocaster** [comment]
That's unrelated. Debug renderer is responsible for debug drawing, such as bullet trajectories, bones, pathfinding, covers, etc.

**Comment by Xottab-DUTY** [comment]
Superseded by #1687.
