### ISSUE TITLE
Падение игры при выходе из лаборатории X8

### ISSUE THREAD

**Issue by holllor** [OpenXRay/xray-16#685]
[openxray_oleg.log](https://github.com/OpenXRay/xray-16/files/5580234/openxray_oleg.log)

**Comment by jjdredd** [comment]
Можно сейв залить  чтобы легче было репродюсить?

**Comment by holllor** [comment]
Конечно

[error_x8.scop.zip](https://github.com/OpenXRay/xray-16/files/5719029/error_x8.scop.zip)

**Comment by jjdredd** [comment]
Странно, умвр.
Может кто-то другой может повторить?

**Comment by lmaomarine** [comment]
у меня все норм, игра не падает

**Comment by holllor** [comment]
Linux  5.4.0-58-generic #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by holllor** [comment]
FATAL ERROR
 
[error] Expression    : !m_error_code
[error] Function      : ~raii_guard
[error] File          : /opt/xray-16/src/xrScriptEngine/script_engine.cpp
[error] Line          : 569
[error] Description   : ..._Linux\scop\gamedata\scripts\release_body_manager.script:20: attempt to index local 'actor' (a nil value)

**Comment by eagleivg** [comment]
Исправлено в https://github.com/OpenXRay/xray-16/commit/edbaac6c3639077e89f4e568145489630c2ce41c
