### ISSUE TITLE
Manjaro: quicksave is not loading

### ISSUE THREAD

**Issue by TarasHots** [OpenXRay/xray-16#686]
**Describe the bug**
Quicksave load is leading to game crash

**To Reproduce**
1. Open the game
2. In Main menu go to load saved games
3. Try to load 
[test - quicksave.zip](https://github.com/OpenXRay/xray-16/files/5585564/test.-.quicksave.zip)
4. See that in the middle of the loading game will crash

**Expected behavior**
Quicksave should be loaded and I can finally bring basic tools to Cardan! :dancers: 

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - OpenXRay build version 7961, Nov 23 2020

**Additional context**
[openxray.log](https://github.com/OpenXRay/xray-16/files/5585592/openxray.log)

**Comment by TarasHots** [comment]
# Test cases with xr_map

### xr_map - faulty quicksave - Skadovsk
![ss_skadovsk_10_fps_11-25-20_21-24-25_(zaton)](https://user-images.githubusercontent.com/2003618/100278241-d6170500-2f64-11eb-9212-22bfedc8a291.jpg)
FPS - 10
saved game - [skadowsk-10-fps - quicksave.zip](https://github.com/OpenXRay/xray-16/files/5598665/skadowsk-10-fps.-.quicksave.zip)

### xr_map - new game - start location
![ss_starting_11-25-20_19-48-45_(zaton)](https://user-images.githubusercontent.com/2003618/100269836-749c6980-2f57-11eb-8650-41846eaeff0a.jpg)
FPS - 17
saved game - [start loc- quicksave.zip](https://github.com/OpenXRay/xray-16/files/5599218/start.loc-.quicksave.zip)

### xr_map - new game - Skadovsk
![ss_skadovsk_17_fps_11-25-20_21-28-39_(zaton)](https://user-images.githubusercontent.com/2003618/100278646-85ec7280-2f65-11eb-8fa3-a78747107a5e.jpg)
FPS - 17, totally playable
saved game is the same from previous test

### xr_map - faulty quicksave - with Shoker's script
I put [release_body_manager_noconsole.zip](https://github.com/OpenXRay/xray-16/files/5599183/release_body_manager_noconsole.zip) 
to `.local/share/GSC Game World/S.T.A.L.K.E.R. - Call of Pripyat/gamedata`
When viewing something else, FPS is 20+
![ss_shoker_10_fps_11-25-20_21-43-41_(zaton)](https://user-images.githubusercontent.com/2003618/100279880-a0275000-2f67-11eb-8761-75c3edd3e4f5.jpg)

When viewing Skadovsk, FPS is 10
![ss_shoker_20+_11-25-20_21-43-49_(zaton)](https://user-images.githubusercontent.com/2003618/100279980-c1883c00-2f67-11eb-904b-41aea0a5d2cb.jpg)


# Test cases with xr_unordered_map

### xr_unordered_map - faulty quicksave
Fails with `attempt to index local 'actor' (a nil value)` which is expected

### xr_unordered_map - faulty quicksave - with Shoker's script
![unordered_shoker](https://user-images.githubusercontent.com/2003618/100282626-41180a00-2f6c-11eb-8701-dfc09dd735f4.jpg)
FPS - 17, playable

I also tried late evening and morning. Morning has a little bit lower FPS, since there are many stalkers out there
![shoker_morning_1](https://user-images.githubusercontent.com/2003618/100283031-fd71d000-2f6c-11eb-8d3a-bc15e89eb6dd.jpg)
![shoker_morning_2](https://user-images.githubusercontent.com/2003618/100283039-01055700-2f6d-11eb-84e6-2c213ce20f7b.jpg)

### xr_unordered_map - new game - with Shoker's script
![new_game_unordered](https://user-images.githubusercontent.com/2003618/100283282-81c45300-2f6d-11eb-8de8-ce7174001415.jpg)
Both at starting point and Skadovsk, all good and playable with 17+ FPS

# Summary
New game is good both with `xr_map` or `xr_unordered_map` with 17 FPS
Faulty quicksave has issues on Skadovsk only and looks like data structure used does not matter there

**Comment by eagleivg** [comment]
Исправлено в https://github.com/OpenXRay/xray-16/commit/edbaac6c3639077e89f4e568145489630c2ce41c
