### ISSUE TITLE
Running Shadow of Chernobyl with OpenXray-16.

### ISSUE THREAD

**Issue by john302** [OpenXRay/xray-16#687]
I am trying to run SoC with the latest build. I have the database files in the ~/.local/share/GSC Game World/S.T.A.L.K.E.R. - Shadow of Chernobyl folder, but when I run it with the xr_3da -soc command line it gets stuck on this part and it can never find the database files.

`$ xr_3da -soc
! Couldn't create surface from image: Couldn't open logo.bmp
OpenXRay Rx64 build 7956, Nov 18 2020
Custom build from commit[6c75c8668c920b1c80cfb343fadc68b17c0ed57e] branch[xd_dev]
 
command line -soc 

* CPU features: RDTSC, MMX, SSE, SSE2, SSE3, SSE4.1, SSE4.2, AVX, AVX2
* CPU cores/threads: 4/4
* CPU current freq: 2455 MHz

Initializing File System...`

Where do I put the SoC database files so that it will actually run? This is not really explained. On Windows you have a bin_x64 folder and the executable goes in here, and then the database files are in the parent folder. This is much easier.

**Comment by Xottab-DUTY** [comment]
SOC is not supported yet. (This is stated in the readme)
That is, it won't launch.

**Comment by Xottab-DUTY** [comment]
You could see something in the commits or in the wiki related to SOC, but those are preparations before we can officially support it.

**Comment by Xottab-DUTY** [comment]
If you have more questions, ask please! :)

(I will close the issue, since the main question is answered)
