### ISSUE TITLE
PBR Shaders for r4

### ISSUE THREAD

**Issue by rugamemaker** [OpenXRay/xray-16#688]
Add shader that supports following maps: diffuse, normal(with channels not swapped), metallic, AO, specular, gloss and emission. Just to have one shader for most materials.

**Comment by Xottab-DUTY** [comment]
`xray-16` is about the engine, while shaders are game resources. We don't modify the game resources in this repository. This issue could be more correct for [OpenXRay Plus repository](https://github.com/OpenXRay/plus), but... I'm not sure if only shader changes would be enough, so it may be worth to reopen #504, but I'm also not sure who can take this task and also the renderer is not ready for PBR. (if we add this now, it will probably will become a mess of code)

Maybe @SkyLoaderr and @vTurbine have something to comment. :)

**Comment by rugamemaker** [comment]
It seems like a reason to learn about render pipelines and shaders. Thanks for instant reply.
