### ISSUE TITLE
libretro port? :)

### ISSUE THREAD

**Issue by DartPower** [OpenXRay/xray-16#690]
Hi there, i have a idea, you want to port to libretro?
This is will be cool, really :)

Check this also please :)
https://www.libretro.com/index.php/mission/
https://docs.libretro.com/development/cores/developing-cores/
https://www.libretro.com/index.php/powered-by-libretro/
https://docs.libretro.com/development/cores/opengl-cores/

**Comment by Xottab-DUTY** [comment]
Pool requests are welcome!

**Comment by Xottab-DUTY** [comment]
Interesting :)

**Comment by Xottab-DUTY** [comment]
Still interesting, but I just want to reduce a number of open issues to make other issues better to track, as this is low priority.
