### ISSUE TITLE
Freeze start in linux

### ISSUE THREAD

**Issue by kotleni** [OpenXRay/xray-16#696]
After starting game, console logs freeze; game not showing.

OS: Linux

Console log:
```
! Couldn't create surface from image: Couldn't open logo.bmp
OpenXRay Rx64 build 7973, Dec  5 2020
Custom build from commit[690dba93e158be5c8df2ed4d5e50e61b09974fa3] branch[xd_dev]
 
command line -fsltx ../fsgame.ltx -psp 

* CPU features: RDTSC, MMX, SSE, SSE2, SSE3, SSE4.1, SSE4.2, AVX, AVX2
* CPU cores/threads: 8/8
* CPU current freq: 1465 MHz

Initializing File System...
$fs_root$ = /home/kotleni/stalker/game
using fs-ltx ../fsgame.ltx
```

**Comment by eagleivg** [comment]
Try remove this key: -psp

**Comment by kotleni** [comment]
not working.

**Comment by kotleni** [comment]
:<

**Comment by eagleivg** [comment]
Try run via strace, maybe will be shown reason

**Comment by jjdredd** [comment]
@kotleni  Where is your `logo.bmp` and what is your sdl version?

**Comment by kotleni** [comment]
sdl version, how to find?

**Comment by Xottab-DUTY** [comment]
@kotleni, any additional info? How did you installed the game?
Can you try to run the game with `strace` and `gdb` and show us the logs?

**Comment by Xottab-DUTY** [comment]
Also, what is your OS?

**Comment by kotleni** [comment]
Kernel: Linux fx 5.0.0-32-generic

**Comment by kotleni** [comment]
After reinstalling OS, i see this error: (linux mint)

```
CMake Error at CMakeLists.txt:93 (message):
  Building with a gcc version less than 8.0 is not supported.
```

**Comment by Xottab-DUTY** [comment]
Right, minimal GCC version supported is 8.0.
OpenXRay can be compiled with GCC 7.0, but it will have random crashes in the game. (you will need to manually remove the error trigger in the CMakeLists.txt)
Lower gcc versions probably won't even compile the engine.
Also, be aware that Clang is not supported completely.

**Comment by kotleni** [comment]
Supplement the Wiki for the assembly, it is not complete - in particular, complete the installation of an adequate version of the gcc

**Comment by Xottab-DUTY** [comment]
Sorry. It will be updated, but while it is not, consider to read Russian version of the "How to build on Linux" instructions, because it is more frequently updated and has the latest info.

**Comment by kotleni** [comment]
Стоп, вы говорите по русски?

**Comment by Xottab-DUTY** [comment]
Более чем 😉

**Comment by kotleni** [comment]
Вы говорите что в русском переводе информаци актуальнее, хотя в самом переводе написано обратное. Как так?

**Comment by kotleni** [comment]
При сборке по инструкции с русского перевода, получаю ошибку:

```
[ 21%] Building CXX object src/xrCDB/CMakeFiles/xrCDB.dir/xr_area_query.cpp.o
CMakeFiles/xrScriptEngine.dir/ScriptEngineScript.cpp.o:ScriptEngineScript.cpp:function luabind::detail::check_link_compatibility(): error: undefined reference to 'luabind::detail::no_error_checking_not_defined_conflict()'
CMakeFiles/xrScriptEngine.dir/ScriptEngineScript.cpp.o:ScriptEngineScript.cpp:function luabind::detail::function_object_impl<void (*)(lua_State*, profile_timer_script&), luabind::meta::type_list<void, lua_State*, profile_timer_script&>, luabind::meta::type_list<> >::invoke_defer(lua_State*, luabind::detail::function_object_impl<void (*)(lua_State*, profile_timer_script&), luabind::meta::type_list<void, lua_State*, profile_timer_script&>, luabind::meta::type_list<> >*, luabind::detail::invoke_context&, int&): error: undefined reference to 'luabind::detail::handle_exception_aux(lua_State*)'
CMakeFiles/xrScriptEngine.dir/ScriptEngineScript.cpp.o:ScriptEngineScript.cpp:function luabind::detail::function_object_impl<void (*)(lua_State*, profile_timer_script const&, profile_timer_script), luabind::meta::type_list<void, lua_State*, profile_timer_script const&, profile_timer_script>, luabind::meta::type_list<> >::invoke_defer(lua_State*, luabind::detail::function_object_impl<void (*)(lua_State*, profile_timer_script const&, profile_timer_script), luabind::meta::type_list<void, lua_State*, profile_timer_script const&, profile_timer_script>, luabind::meta::type_list<> >*, luabind::detail::invoke_context&, int&): error: undefined reference to 'luabind::detail::handle_exception_aux(lua_State*)'
CMakeFiles/xrScriptEngine.dir/ScriptEngineScript.cpp.o:ScriptEngineScript.cpp:function luabind::detail::function_object_impl<float (profile_timer_script::*)() const, luabind::meta::type_list<float, profile_timer_script const&>, luabind::meta::type_list<> >::invoke_defer(lua_State*, luabind::detail::function_object_impl<float (profile_timer_script::*)() const, luabind::meta::type_list<float, profile_timer_script const&>, luabind::meta::type_list<> >*, luabind::detail::invoke_context&, int&): error: undefined reference to 'luabind::detail::handle_exception_aux(lua_State*)'
CMakeFiles/xrScriptEngine.dir/ScriptEngineScript.cpp.o:ScriptEngineScript.cpp:function luabind::detail::function_object_impl<void (profile_timer_script::*)(), luabind::meta::type_list<void, profile_timer_script&>, luabind::meta::type_list<> >::invoke_defer(lua_State*, luabind::detail::function_object_impl<void (profile_timer_script::*)(), luabind::meta::type_list<void, profile_timer_script&>, luabind::meta::type_list<> >*, luabind::detail::invoke_context&, int&): error: undefined reference to 'luabind::detail::handle_exception_aux(lua_State*)'
CMakeFiles/xrScriptEngine.dir/script_engine.cpp.o:script_engine.cpp:function luabind::detail::call_error(lua_State*): error: undefined reference to 'luabind::error::error(lua_State*)'
CMakeFiles/xrScriptEngine.dir/script_engine.cpp.o:script_engine.cpp:function luabind::detail::call_error(lua_State*): error: undefined reference to 'typeinfo for luabind::error'
CMakeFiles/xrScriptEngine.dir/script_engine.cpp.o:script_engine.cpp:function luabind::error::~error(): error: undefined reference to 'vtable for luabind::error'
/usr/bin/ld.gold: the vtable symbol may be undefined because the class is missing its key function
collect2: error: ld returned 1 exit status
src/xrScriptEngine/CMakeFiles/xrScriptEngine.dir/build.make:476: recipe for target 'x64/Release/xrScriptEngine.so' failed
make[2]: *** [x64/Release/xrScriptEngine.so] Error 1
CMakeFiles/Makefile2:2747: recipe for target 'src/xrScriptEngine/CMakeFiles/xrScriptEngine.dir/all' failed
make[1]: *** [src/xrScriptEngine/CMakeFiles/xrScriptEngine.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 21%] Building CXX object src/xrCDB/CMakeFiles/xrCDB.dir/xr_area_raypick.cpp.o
[ 21%] Linking CXX shared library ../../x64/Release/xrCDB.so
[ 21%] Built target xrCDB
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by Xottab-DUTY** [comment]
> Вы говорите что в русском переводе информаци актуальнее, хотя в самом переводе написано обратное. Как так?

Ту строчку про неактуальность не я писал, но оставил, т.к. всё равно хотел обновить всю вики.. Но пока так и не добрался 😬

По ошибке: старый luabind, нужно обновить подмодули.

P.S. если вам будет удобнее, то можно на ты обращаться 🙂

**Comment by kotleni** [comment]
Обновил, но ...

`[ 21%] Generating CXX prefix header src/xrSound/cotire/xrSound_CXX_prefix.hxx
CMakeFiles/xrScriptEngine.dir/ScriptEngineScript.cpp.o:ScriptEngineScript.cpp:function luabind::detail::check_link_compatibility(): error: undefined reference to 'luabind::detail::no_error_checking_not_defined_conflict()'
CMakeFiles/xrScriptEngine.dir/ScriptEngineScript.cpp.o:ScriptEngineScript.cpp:function luabind::detail::function_object_impl<void (*)(lua_State*, profile_timer_script&), luabind::meta::type_list<void, lua_State*, profile_timer_script&>, luabind::meta::type_list<> >::invoke_defer(lua_State*, luabind::detail::function_object_impl<void (*)(lua_State*, profile_timer_script&), luabind::meta::type_list<void, lua_State*, profile_timer_script&>, luabind::meta::type_list<> >*, luabind::detail::invoke_context&, int&): error: undefined reference to 'luabind::detail::handle_exception_aux(lua_State*)'
CMakeFiles/xrScriptEngine.dir/ScriptEngineScript.cpp.o:ScriptEngineScript.cpp:function luabind::detail::function_object_impl<void (*)(lua_State*, profile_timer_script const&, profile_timer_script), luabind::meta::type_list<void, lua_State*, profile_timer_script const&, profile_timer_script>, luabind::meta::type_list<> >::invoke_defer(lua_State*, luabind::detail::function_object_impl<void (*)(lua_State*, profile_timer_script const&, profile_timer_script), luabind::meta::type_list<void, lua_State*, profile_timer_script const&, profile_timer_script>, luabind::meta::type_list<> >*, luabind::detail::invoke_context&, int&): error: undefined reference to 'luabind::detail::handle_exception_aux(lua_State*)'
CMakeFiles/xrScriptEngine.dir/ScriptEngineScript.cpp.o:ScriptEngineScript.cpp:function luabind::detail::function_object_impl<float (profile_timer_script::*)() const, luabind::meta::type_list<float, profile_timer_script const&>, luabind::meta::type_list<> >::invoke_defer(lua_State*, luabind::detail::function_object_impl<float (profile_timer_script::*)() const, luabind::meta::type_list<float, profile_timer_script const&>, luabind::meta::type_list<> >*, luabind::detail::invoke_context&, int&): error: undefined reference to 'luabind::detail::handle_exception_aux(lua_State*)'
CMakeFiles/xrScriptEngine.dir/ScriptEngineScript.cpp.o:ScriptEngineScript.cpp:function luabind::detail::function_object_impl<void (profile_timer_script::*)(), luabind::meta::type_list<void, profile_timer_script&>, luabind::meta::type_list<> >::invoke_defer(lua_State*, luabind::detail::function_object_impl<void (profile_timer_script::*)(), luabind::meta::type_list<void, profile_timer_script&>, luabind::meta::type_list<> >*, luabind::detail::invoke_context&, int&): error: undefined reference to 'luabind::detail::handle_exception_aux(lua_State*)'
CMakeFiles/xrScriptEngine.dir/script_engine.cpp.o:script_engine.cpp:function luabind::detail::call_error(lua_State*): error: undefined reference to 'luabind::error::error(lua_State*)'
CMakeFiles/xrScriptEngine.dir/script_engine.cpp.o:script_engine.cpp:function luabind::detail::call_error(lua_State*): error: undefined reference to 'typeinfo for luabind::error'
CMakeFiles/xrScriptEngine.dir/script_engine.cpp.o:script_engine.cpp:function luabind::error::~error(): error: undefined reference to 'vtable for luabind::error'
/usr/bin/ld.gold: the vtable symbol may be undefined because the class is missing its key function
collect2: error: ld returned 1 exit status
src/xrScriptEngine/CMakeFiles/xrScriptEngine.dir/build.make:476: recipe for target 'x64/Release/xrScriptEngine.so' failed
make[2]: *** [x64/Release/xrScriptEngine.so] Error 1
CMakeFiles/Makefile2:2747: recipe for target 'src/xrScriptEngine/CMakeFiles/xrScriptEngine.dir/all' failed
make[1]: *** [src/xrScriptEngine/CMakeFiles/xrScriptEngine.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....`

...

`[ 22%] Built target xrSound
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by Xottab-DUTY** [comment]
Скорее всего, кэш cotire устарел (точнее, не обновился), имеет смысл сделать clean или вручную в папке с луабиндом удалить папку cotire

**Comment by kotleni** [comment]
Выполнил `make clean`, и:
```

[ 21%] Linking CXX shared library ../../x64/Release/xrScriptEngine.so
CMakeFiles/xrScriptEngine.dir/ScriptEngineScript.cpp.o:ScriptEngineScript.cpp:function luabind::detail::check_link_compatibility(): error: undefined reference to 'luabind::detail::no_error_checking_not_defined_conflict()'
CMakeFiles/xrScriptEngine.dir/ScriptEngineScript.cpp.o:ScriptEngineScript.cpp:function luabind::detail::function_object_impl<void (*)(lua_State*, profile_timer_script&), luabind::meta::type_list<void, lua_State*, profile_timer_script&>, luabind::meta::type_list<> >::invoke_defer(lua_State*, luabind::detail::function_object_impl<void (*)(lua_State*, profile_timer_script&), luabind::meta::type_list<void, lua_State*, profile_timer_script&>, luabind::meta::type_list<> >*, luabind::detail::invoke_context&, int&): error: undefined reference to 'luabind::detail::handle_exception_aux(lua_State*)'
CMakeFiles/xrScriptEngine.dir/ScriptEngineScript.cpp.o:ScriptEngineScript.cpp:function luabind::detail::function_object_impl<void (*)(lua_State*, profile_timer_script const&, profile_timer_script), luabind::meta::type_list<void, lua_State*, profile_timer_script const&, profile_timer_script>, luabind::meta::type_list<> >::invoke_defer(lua_State*, luabind::detail::function_object_impl<void (*)(lua_State*, profile_timer_script const&, profile_timer_script), luabind::meta::type_list<void, lua_State*, profile_timer_script const&, profile_timer_script>, luabind::meta::type_list<> >*, luabind::detail::invoke_context&, int&): error: undefined reference to 'luabind::detail::handle_exception_aux(lua_State*)'
CMakeFiles/xrScriptEngine.dir/ScriptEngineScript.cpp.o:ScriptEngineScript.cpp:function luabind::detail::function_object_impl<float (profile_timer_script::*)() const, luabind::meta::type_list<float, profile_timer_script const&>, luabind::meta::type_list<> >::invoke_defer(lua_State*, luabind::detail::function_object_impl<float (profile_timer_script::*)() const, luabind::meta::type_list<float, profile_timer_script const&>, luabind::meta::type_list<> >*, luabind::detail::invoke_context&, int&): error: undefined reference to 'luabind::detail::handle_exception_aux(lua_State*)'
CMakeFiles/xrScriptEngine.dir/ScriptEngineScript.cpp.o:ScriptEngineScript.cpp:function luabind::detail::function_object_impl<void (profile_timer_script::*)(), luabind::meta::type_list<void, profile_timer_script&>, luabind::meta::type_list<> >::invoke_defer(lua_State*, luabind::detail::function_object_impl<void (profile_timer_script::*)(), luabind::meta::type_list<void, profile_timer_script&>, luabind::meta::type_list<> >*, luabind::detail::invoke_context&, int&): error: undefined reference to 'luabind::detail::handle_exception_aux(lua_State*)'
CMakeFiles/xrScriptEngine.dir/script_engine.cpp.o:script_engine.cpp:function luabind::detail::call_error(lua_State*): error: undefined reference to 'luabind::error::error(lua_State*)'
CMakeFiles/xrScriptEngine.dir/script_engine.cpp.o:script_engine.cpp:function luabind::detail::call_error(lua_State*): error: undefined reference to 'typeinfo for luabind::error'
CMakeFiles/xrScriptEngine.dir/script_engine.cpp.o:script_engine.cpp:function luabind::error::~error(): error: undefined reference to 'vtable for luabind::error'
/usr/bin/ld.gold: the vtable symbol may be undefined because the class is missing its key function
collect2: error: ld returned 1 exit status
src/xrScriptEngine/CMakeFiles/xrScriptEngine.dir/build.make:476: recipe for target 'x64/Release/xrScriptEngine.so' failed
make[2]: *** [x64/Release/xrScriptEngine.so] Error 1
CMakeFiles/Makefile2:2747: recipe for target 'src/xrScriptEngine/CMakeFiles/xrScriptEngine.dir/all' failed
make[1]: *** [src/xrScriptEngine/CMakeFiles/xrScriptEngine.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 21%] Linking CXX shared library ../../x64/Release/xrCDB.so
[ 21%] Built target xrCDB
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by Xottab-DUTY** [comment]
Что насчёт второго способа?
И с какой ветки движок собирается?
Нужно собирать с xd_dev. (можно и с обычной dev или master, но это нечастообновляющиеся ветки)

**Comment by kotleni** [comment]
Где эта папка с 'луабиндом' находится?
Ветка: xd_dev

**Comment by Xottab-DUTY** [comment]
Externals/luabind

**Comment by kotleni** [comment]
Как установить gcc 8.0+ ?
Linux Mint

**Comment by Xottab-DUTY** [comment]
На убунту довольно просто устанавливается, точно также через apt (apt-get) устанавливаешь пакет gcc-8.
Потом, для удобства его ещё по-умолчанию можно поставить, но я не помню как.
Для Linux Mint не подскажу, не сидел на нём, возможно точно так же)

**Comment by kotleni** [comment]
Ага, разобрался.
Как указать для cmake указать компилятор?

**Comment by 007exe** [comment]
cmake -DCMAKE_C_COMPILER=gcc-8 -DCMAKE_CXX_COMPILER=g++-8 ...

**Comment by kotleni** [comment]
```
[ 21%] Linking CXX shared library ../../x64/Release/xrScriptEngine.so
CMakeFiles/xrScriptEngine.dir/ScriptEngineScript.cpp.o:ScriptEngineScript.cpp:function luabind::detail::check_link_compatibility(): error: undefined reference to 'luabind::detail::no_error_checking_not_defined_conflict()'
CMakeFiles/xrScriptEngine.dir/ScriptEngineScript.cpp.o:ScriptEngineScript.cpp:function luabind::detail::function_object_impl<void (*)(lua_State*, profile_timer_script&), luabind::meta::type_list<void, lua_State*, profile_timer_script&>, luabind::meta::type_list<> >::invoke_defer(lua_State*, luabind::detail::function_object_impl<void (*)(lua_State*, profile_timer_script&), luabind::meta::type_list<void, lua_State*, profile_timer_script&>, luabind::meta::type_list<> >*, luabind::detail::invoke_context&, int&): error: undefined reference to 'luabind::detail::handle_exception_aux(lua_State*)'
CMakeFiles/xrScriptEngine.dir/ScriptEngineScript.cpp.o:ScriptEngineScript.cpp:function luabind::detail::function_object_impl<void (*)(lua_State*, profile_timer_script const&, profile_timer_script), luabind::meta::type_list<void, lua_State*, profile_timer_script const&, profile_timer_script>, luabind::meta::type_list<> >::invoke_defer(lua_State*, luabind::detail::function_object_impl<void (*)(lua_State*, profile_timer_script const&, profile_timer_script), luabind::meta::type_list<void, lua_State*, profile_timer_script const&, profile_timer_script>, luabind::meta::type_list<> >*, luabind::detail::invoke_context&, int&): error: undefined reference to 'luabind::detail::handle_exception_aux(lua_State*)'
CMakeFiles/xrScriptEngine.dir/ScriptEngineScript.cpp.o:ScriptEngineScript.cpp:function luabind::detail::function_object_impl<float (profile_timer_script::*)() const, luabind::meta::type_list<float, profile_timer_script const&>, luabind::meta::type_list<> >::invoke_defer(lua_State*, luabind::detail::function_object_impl<float (profile_timer_script::*)() const, luabind::meta::type_list<float, profile_timer_script const&>, luabind::meta::type_list<> >*, luabind::detail::invoke_context&, int&): error: undefined reference to 'luabind::detail::handle_exception_aux(lua_State*)'
CMakeFiles/xrScriptEngine.dir/ScriptEngineScript.cpp.o:ScriptEngineScript.cpp:function luabind::detail::function_object_impl<void (profile_timer_script::*)(), luabind::meta::type_list<void, profile_timer_script&>, luabind::meta::type_list<> >::invoke_defer(lua_State*, luabind::detail::function_object_impl<void (profile_timer_script::*)(), luabind::meta::type_list<void, profile_timer_script&>, luabind::meta::type_list<> >*, luabind::detail::invoke_context&, int&): error: undefined reference to 'luabind::detail::handle_exception_aux(lua_State*)'
CMakeFiles/xrScriptEngine.dir/script_engine.cpp.o:script_engine.cpp:function luabind::detail::call_error(lua_State*): error: undefined reference to 'luabind::error::error(lua_State*)'
CMakeFiles/xrScriptEngine.dir/script_engine.cpp.o:script_engine.cpp:function luabind::detail::call_error(lua_State*): error: undefined reference to 'typeinfo for luabind::error'
CMakeFiles/xrScriptEngine.dir/script_engine.cpp.o:script_engine.cpp:function luabind::error::~error(): error: undefined reference to 'vtable for luabind::error'
/usr/bin/ld.gold: the vtable symbol may be undefined because the class is missing its key function
collect2: error: ld returned 1 exit status
src/xrScriptEngine/CMakeFiles/xrScriptEngine.dir/build.make:476: recipe for target 'x64/Release/xrScriptEngine.so' failed
make[2]: *** [x64/Release/xrScriptEngine.so] Error 1
CMakeFiles/Makefile2:2864: recipe for target 'src/xrScriptEngine/CMakeFiles/xrScriptEngine.dir/all' failed
make[1]: *** [src/xrScriptEngine/CMakeFiles/xrScriptEngine.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Scanning dependencies of target xrCDB
[ 21%] Building CXX object src/xrCDB/CMakeFiles/xrCDB.dir/Frustum.cpp.o
[ 21%] Building CXX object src/xrCDB/CMakeFiles/xrCDB.dir/ISpatial_q_box.cpp.o
[ 21%] Building CXX object src/xrCDB/CMakeFiles/xrCDB.dir/ISpatial.cpp.o
[ 21%] Building CXX object src/xrCDB/CMakeFiles/xrCDB.dir/ISpatial_q_frustum.cpp.o
[ 21%] Building CXX object src/xrCDB/CMakeFiles/xrCDB.dir/ISpatial_verify.cpp.o
[ 21%] Building CXX object src/xrCDB/CMakeFiles/xrCDB.dir/ISpatial_q_ray.cpp.o
[ 21%] Building CXX object src/xrCDB/CMakeFiles/xrCDB.dir/xrCDB.cpp.o
[ 21%] Building CXX object src/xrCDB/CMakeFiles/xrCDB.dir/StdAfx.cpp.o
[ 21%] Building CXX object src/xrCDB/CMakeFiles/xrCDB.dir/xrCDB_Collector.cpp.o
[ 21%] Building CXX object src/xrCDB/CMakeFiles/xrCDB.dir/xrCDB_box.cpp.o
[ 21%] Building CXX object src/xrCDB/CMakeFiles/xrCDB.dir/xrCDB_frustum.cpp.o
[ 22%] Building CXX object src/xrCDB/CMakeFiles/xrCDB.dir/xrCDB_ray.cpp.o
[ 22%] Building CXX object src/xrCDB/CMakeFiles/xrCDB.dir/xrXRC.cpp.o
[ 22%] Building CXX object src/xrCDB/CMakeFiles/xrCDB.dir/xr_area.cpp.o
[ 22%] Building CXX object src/xrCDB/CMakeFiles/xrCDB.dir/xr_area_query.cpp.o
[ 22%] Building CXX object src/xrCDB/CMakeFiles/xrCDB.dir/xr_area_raypick.cpp.o
[ 22%] Linking CXX shared library ../../x64/Release/xrCDB.so
[ 22%] Built target xrCDB
Makefile:105: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by Xottab-DUTY** [comment]
Что показывает `git status`?

**Comment by kotleni** [comment]
```
On branch xd_dev
Your branch is up to date with 'origin/xd_dev'.

nothing to commit, working tree clean

```

**Comment by johndoe71rus** [comment]
ты очищаешь папку build перед новой сборкой?

**Comment by kotleni** [comment]
**я с нуля скачал репо**

**Comment by johndoe71rus** [comment]
не знаю, имеет значение 
cmake -DCMAKE_C_COMPILER=gcc-8 -DCMAKE_CXX_COMPILER=g++-8 .. 
в конце 2 точки а не 3 как 007exe написал

**Comment by kotleni** [comment]
> не знаю, имеет значение
> cmake -DCMAKE_C_COMPILER=gcc-8 -DCMAKE_CXX_COMPILER=g++-8 ..
> в конце 2 точки а не 3 как 007exe написал

я это правильно написал.

**Comment by johndoe71rus** [comment]
у меня алгоритм такой.
установить зависимости для сборки.
клонировать репо
cd ./xray-16
git submodule sync
git submodule update --init --recursive
cd ./build
cmake -DCMAKE_C_COMPILER=gcc-8 -DCMAKE_CXX_COMPILER=g++-8 -w ..
make -j4 >out.log 2>warn.log
все.
для повторной сборки удаляю все из папки build

**Comment by 007exe** [comment]
Должно быть примерно так 
1) `sudo apt install git cmake make libglew-dev libfreeimage-dev liblockfile-dev libopenal-dev libtbb-dev libcrypto++-dev libpugixml-dev libogg-dev libtheora-dev libvorbis-dev libsdl2-dev liblzo2-dev libjpeg-dev libncurses5-dev libreadline-dev gcc g++ libfreeimageplus-dev libfreeimageplus3 dpkg-dev`
2) `git clone https://github.com/OpenXRay/xray-16.git --recurse-submodules`
3) `cd xray-16 && mkdir bin && cd bin`
4) `cmake .. -DCMAKE_C_COMPILER=gcc-8 -DCMAKE_CXX_COMPILER=g++-8 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_BINDIR=/usr/games`
"В принципе ключи-DCMAKE_BUILD_TYPE=Release и -DCMAKE_INSTALL_BINDIR=/usr/games не обязательны"
5) `make -j(количество ядер без скобок)`
А дальше либо `sudo make install` либо `make package` для сборки deb пакета и соответственно его установка `sudo dpkg -i openxray_1.6.02_amd64.deb` или ручками всё скопировать из `xray-16/bin/x64/Release/`

**Comment by kotleni** [comment]
> у меня алгоритм такой.
> установить зависимости для сборки.
> клонировать репо
> cd ./xray-16
> git submodule sync
> git submodule update --init --recursive
> cd ./build
> cmake -DCMAKE_C_COMPILER=gcc-8 -DCMAKE_CXX_COMPILER=g++-8 -w ..
> make -j4 >out.log 2>warn.log
> все.
> для повторной сборки удаляю все из папки build

Сейчас попробую собрать вот так.

**Comment by kotleni** [comment]
> у меня алгоритм такой.
> установить зависимости для сборки.
> клонировать репо
> cd ./xray-16
> git submodule sync
> git submodule update --init --recursive
> cd ./build
> cmake -DCMAKE_C_COMPILER=gcc-8 -DCMAKE_CXX_COMPILER=g++-8 -w ..
> make -j4 >out.log 2>warn.log
> все.
> для повторной сборки удаляю все из папки build

Это стало моим решением!

**Comment by kotleni** [comment]
![image](https://user-images.githubusercontent.com/38311102/102126326-994b7900-3e53-11eb-8115-f226cda3849e.png)

**Comment by kotleni** [comment]
Тень чернобыля не поддерживается openXRay?
У меня нет папки `./gamedata/configs/` есть только `./gamedata/config/`

**Comment by 007exe** [comment]
Пока только ЗП и ЧН, ТЧ в разработке

**Comment by kotleni** [comment]
Спасибо за помощь, я рад что 'возле' Open Source проектов - существуют такие люди.
