### ISSUE TITLE
Rescan CDB cache folder after saving cache on disk

### ISSUE THREAD

**Issue by Xottab-DUTY** [OpenXRay/xray-16#709]
After testing CDB cache (that was added in #698), we (me and testers) had found a small but sensible bug:
If we go, e.g., from the Zaton to the Yanov and back to the Zaton, the game won't find cached files until game restart.

This happens because `FS.exist(*cdb_cache_file*)` always return `false` in the current game session even if the file exist, because the filesystem doesn't know that they exist. Of course, after game restart (full application restart), the filesystem scans all the files and finds CDB cache and starts to work correctly.

Filesystem supports folders rescanning. Just need to use it.

**Comment by Xottab-DUTY** [comment]
This issue should be easy to solve.
So, @jjdredd, you may be interested. 🙂

**Comment by jjdredd** [comment]
Ok, I'll look into it, but I'll need more info. Feel free to assign me.

**Comment by Xottab-DUTY** [comment]
Fixed by ad881d6071c5f8b7e48e11db3086d6cad799af92
