### ISSUE TITLE
NPCs don't react to enemies shooting around until see them or get shot

### ISSUE THREAD

**Issue by nitrocaster** [OpenXRay/xray-16#71]

**Comment by revolucas** [comment]
I don't think this is an engine problem. If you remove the distance (90m) check in xr_combat_ignore.script and increase danger ignore distances in xr_danger.script they will react to enemy sounds at much greater distances.

**Comment by CrossVR** [comment]
I also don't think we should be making these kinds of gameplay changes in the engine. If you change the behaviour of the AI system you may get a very different game. Our focus should be to improve the engine, but leave the gameplay untouched.

**Comment by tamlin-mike** [comment]
This issue should be closed.

**Comment by nitrocaster** [comment]
Indeed.
