### ISSUE TITLE
[Clear Sky] Crash after changing resolution

### ISSUE THREAD

**Issue by 1024mb** [OpenXRay/xray-16#715]
**Describe the bug**
Game crashed after picking 1920x1080 as the resolution and applying.

**To Reproduce**
1. Go to config
2. Change resolution
3. Apply

**BugTrap error report**

[OpenXRay_error_report_210111-233839.zip](https://github.com/OpenXRay/xray-16/files/5799872/OpenXRay_error_report_210111-233839.zip)

**Desktop (please complete the following information):**
 - OS: Windows 10 2004
 - OpenXRay build version latest artifact from appveyor

**Additional context**
The game has no mods installed, the only change I have is an edit in system.ltx about the weight.  
This is the first time using OpenXRay.

**Comment by Xottab-DUTY** [comment]
Hint for programmers:
This is related to UI restart: some invalid pointers are not getting cleared from the array.

**Comment by Xottab-DUTY** [comment]
@collectioner, I don't think that this issue is easy.

**Comment by GribanovIvan** [comment]
edit user.ltx, works for me

**Comment by SaloEater** [comment]
@Xottab-DUTY как такое вообще возможно?
Из всех методов на одном уровне ошибку кидает только IsShown, хотя класс он вот он, лежит в памяти.
И почему вызов метода стучится в 0х0...
![image](https://user-images.githubusercontent.com/6031470/108868161-fbb8b680-7606-11eb-9331-f216acd1c625.png)

**Comment by Xottab-DUTY** [comment]
В массиве лежит указатель на удалённый объект. Обращение по этому указателю приводит к вылету.

**Comment by Xottab-DUTY** [comment]
Хотя, могу быть неправ, но, очевидно, что он стучится в 0x0 он потому что pDialog там имеет значение 0x0.

**Comment by GribanovIvan** [comment]
Всё просто - пишем отдельную программу для изменения user.ltx

**Comment by Xottab-DUTY** [comment]
@1024mb, just fixed the issue, the new build with the fix should be available on AppVeyor within several hours, or, in ~30 minutes on GitHub Actions.
