### ISSUE TITLE
Compile errors on Windows due to SDL dependency

### ISSUE THREAD

**Issue by diharaw** [OpenXRay/xray-16#716]
I tried building on Windows with Visual Studio 2019 and got a bunch of errors regarding missing SDL headers.
I took a look at the root CMakeList and it seems like SDL is only required if the platform isn't WIN32:
https://github.com/OpenXRay/xray-16/blob/dev/CMakeLists.txt#L189

However the SDL calls are used throughout the codebase without any IFDEF:
https://github.com/OpenXRay/xray-16/blob/dev/src/xr_3da/entry_point.cpp#L28

Is windows abandoned? If not, I'd be happy to help out with getting it to build :)

**Comment by Xottab-DUTY** [comment]
For Windows you should Visual Studio solution `src/engine.sln`, not CMake.

**Comment by diharaw** [comment]
Thanks! I feel dumb for not seeing that!

**Comment by Xottab-DUTY** [comment]
My bad too, it ~~is not~~ was not stated in the readme, nor in the build instructions on wiki :)

UPD: added a note to the [instructions page](https://github.com/OpenXRay/xray-16/wiki/%5BEN%5D-How-to-build-and-setup-on-Windows).
