### ISSUE TITLE
[EN] How to build and setup on Linux missing quite a bit of information compared to [RU] version

### ISSUE THREAD

**Issue by digitall** [OpenXRay/xray-16#718]
Have updated the [EN] Linux build information using the [RU] version as a base. This probably needs a bit more work, but is a major improvement to users / developers who don't speak Russian to get started with this codebase.

Since Github does not allow fork / pull requests easily of the Wiki pages despite being held in git repositories, I have forked this manually and updated. The improved page can be found here:
https://github.com/digitall/xray-16/wiki/[EN]-How-to-build-and-setup-on-Linux

If this could get updated in the project wiki, that would be optimal. @Xottab-DUTY ?

**Comment by Xottab-DUTY** [comment]
I wanted to handle this myself and update both RU and EN versions to make sure that they are written in one unified style... But I didn't managed to do that.

So, thanks to @OPNA2608 for taking care about the issue!

**Comment by digitall** [comment]
@Xottab-DUTY , @OPNA2608 : Thanks for sorting the EN version to be more verbose :)
