### ISSUE TITLE
FindReadline.cmake typo preventing cmake config

### ISSUE THREAD

**Issue by iq2luc** [OpenXRay/xray-16#719]
**Description**
CMake configuration: shared library libreadline.so not found due to a typo in FindReadline.cmake.
Also see: https://github.com/OpenXRay/xray-16/pull/707#pullrequestreview-573280036

**Steps to reproduce**
1. Configure via CMake on Linux (Archlinux distro)
2. FindReadline.cmake cannot find libreadline.so

**Suggested patch**
[FixCMakeFindReadline.patch.txt](https://github.com/OpenXRay/xray-16/files/5849373/FixCMakeFindReadline.patch.txt)

**Comment by Xottab-DUTY** [comment]
Can you open a pull request?

**Comment by iq2luc** [comment]
Never did that before (the pull request thingy on github) but if that's the only way for this small issue to be fixed I will try to do it.

**Comment by iq2luc** [comment]
OK, done, there's always 'a first'.
Also taking the opportunity to express my appreciation for the extraordinary people working on everything STALKER related. Thank you for the Linux port.

**Comment by Xottab-DUTY** [comment]
Thank you too!
