### ISSUE TITLE
[Call of Pripyat] Crash after changes in AtmosFear 3 settings

### ISSUE THREAD

**Issue by ParzivalFly** [OpenXRay/xray-16#722]
**Describe the bug**
Game crashed after loading a save with changes to the weather settings (psi-storm, fallout) atmosfear 3. Also, the game crashes at the end of a psi-storm, while fallout works without problems.

**To Reproduce**
1. Launch save without changes (`#1`)
2. Open main menu, atmosfear 3 settings
3. Disable psi-storm/fallout
4. Create save (`#2`) with new settings
5. Load save `#2` 
6. See error

**BugTrap error report**
[OpenXRay_error_report_210123-152810.zip](https://github.com/OpenXRay/xray-16/files/5859770/OpenXRay_error_report_210123-152810.zip)

**Desktop**
 - OS: Windows 10 20H2
 - OpenXRay build version [822]

**Additional context**
Mods: AtmosFear 3; Absolute Nature 4.04; Two-K (without addons); Animated detectors (Ferr-um); PHARM
This is the first time using OpenXRay.

**Comment by Xottab-DUTY** [comment]
According to the attached error report, it crashes because of missing upgrade `up_thirdd_stalker_outfit` for stalker outfit. Doesn't seem to be related to AtmosFear in any way, hmm..

**Comment by ParzivalFly** [comment]
I tried to simulate this error on the steam vanilla.
Steps:
1) Install vanilla
2) Install OpenXRay replacing vanilla files
3) Install AtmosFear 3 over OpenXRay
4) Move the "bin" folder from the OpenXRay archive over the installed AtmosFear 3
5) Start a new game, open the AtmosFear 3 settings, disable psi-storm and fallout, create a save.
6) Load this save
7) See error
Attached a bug report
[OpenXRay_error_report_210124-123846.zip](https://github.com/OpenXRay/xray-16/files/5861488/OpenXRay_error_report_210124-123846.zip)
