### ISSUE TITLE
Closing the game via Alt+F4 don't work properly.

### ISSUE THREAD

**Issue by Xottab-DUTY** [OpenXRay/xray-16#725]

**Comment by vitaly-gaiduk** [comment]
@Xottab-DUTY is issue still actual? Alt+F4 works for me in both CS and CoP with latest build. I have Windows 10 21H1.

**Comment by Xottab-DUTY** [comment]
@vitaly-gaiduk, yes, it is not shutting down correctly, it just crashing silently.

**Comment by dino8890** [comment]
Segmentation fault happens when `SDL_GL_DeleteContext` is called when deleting `m_helper_context` in `CHW::DestroyDevice`. I briefly looked around, but have no idea what might be the issue exactly.

```cpp
void CHW::DestroyDevice()
{
    SDL_GL_MakeCurrent(nullptr, nullptr);

    SDL_GL_DeleteContext(m_context);
    m_context = nullptr;

    SDL_GL_DeleteContext(m_helper_context);
    m_helper_context = nullptr;
}
```

**Comment by Xottab-DUTY** [comment]
Alt+F4 doesn't follow normal shutdown procedure. (destructing structures before exit, etc.)

It started working wrong after we had ported engine to SDL2.
(nothing wrong with SDL2)

I'll try to provide details later.
