### ISSUE TITLE
Sliding type doors (from SOC/CS) are not handled by COP engine

### ISSUE THREAD

**Issue by ghost** [OpenXRay/xray-16#73]
If someone wants to use sliding type doors from SOC/CS, it will crash with:

`FATAL ERROR`
` `
`[error]Expression    : assertion failed`
`[error]Function      : doors::door::door`
`[error]File          : doors_door.cpp`
`[error]Line          : 36`
`[error]Description   : m_object.get_door_vectors( m_closed_vector, m_open_vector )`

Can be tested with these meshes from SOC:
tumba_village_50x120_ph_door.ogf, door_garbage_01.ogf

**Comment by nitrocaster** [comment]
Could you provide a small level with these objects? Would be much easier to proceed with this issue.

**Comment by Xottab-DUTY** [comment]
Here's the test level, if someone wants to test the doors:
https://cdn.discordapp.com/attachments/410170556139438081/564124339570475008/doors.rar

**Comment by Xottab-DUTY** [comment]
The support for sliding and another types of doors may be removed for a reason. These doors are working, but we need to test them more.

**Comment by TarasHots** [comment]
> 
> 
> Here's the test level, if someone wants to test the doors:
> https://cdn.discordapp.com/attachments/410170556139438081/564124339570475008/doors.rar

How to test it? Replace directories and load game only?

**Comment by LVLVbNH** [comment]
> > Here's the test level, if someone wants to test the doors:
> > https://cdn.discordapp.com/attachments/410170556139438081/564124339570475008/doors.rar
> 
> How to test it? Replace directories and load game only?

Unpack "gamedata" folder contents in "gamedata" (I didn't notice the any overwrite)-> Launch game->New game (ignore missing textures in log)->You will spawned in little test area with slide door (aka door_garbage_01).
