### ISSUE TITLE
Engine errors while using OpenXray with Clear Sky

### ISSUE THREAD

**Issue by globekat** [OpenXRay/xray-16#745]
First of all, thanks for the work in making this backwards compatible with Clear Sky, I look forwards to one day going through Clear Sky with all of the benefits of the Call or Pripyat Engine. That said, the current label of 'Release Candidate' seems a touch premature, given I have currently consistently encounted the following engine crashes while starting OpenXray, and creating a new game/loading a save created using it.

**Describe the bug**
FATAL ERROR
 
[error] Expression    : pData->m_StringTable.find(string_name) == pData->m_StringTable.end()
[error] Function      : CStringTable::Load
[error] File          : C:\projects\xray-16\src\xrGame\string_table.cpp
[error] Line          : 163
[error] Description   : duplicate string table id
[error] Arguments     : st_client_connecting_to

FATAL ERROR
 
[error] Expression    : cnt != 0
[error] Function      : CActor::Load
[error] File          : C:\projects\xray-16\src\xrGame\Actor.cpp
[error] Line          : 396
[error] Description   : assertion failed

I'm not sure if these are actual engine issues, or something outdated in Clear Sky's configs/scripts that needs to be updated to work with OpenXray

**To Reproduce**
1. Downloaded OpenXRay December 2020 Preview (Mixed) build from 'How to install and play' wiki article. IF you use Release Clear Sky crashes and you need to log out/restart computer to get control back.
2. Downloaded most recent CS gamedata from [here](https://github.com/OpenXRay/xray-16/issues/382#issuecomment-616444896)
3. Installed OpenXray for Clear Sky as per instructions on the 'How to install and play' wiki page
4. Started Clear Sky, and created a new game

**Expected behavior**
For the release build, Clear Sky doesn't crash and lock up the computer while creating/loading a game.
For the mixed build, Clear Sky doesn't produce the following popup errors during startup and while creating/loading a game.

**Desktop (please complete the following information):**
 - OS: Windows 10 1909
 - OpenXRay build version [December 2020 Preview, Mixed]
 - Clear Sky gamedata from [here](https://github.com/OpenXRay/xray-16/issues/382#issuecomment-616444896)

**Comment by Xottab-DUTY** [comment]
What game version and edition do you have? Like, 1.5.10 and Steam/GOG/Retail CD?
Also, the log file is needed, it is located in the `game folder/_appdata_/logs`.

**Comment by globekat** [comment]
1.5.10 Steam. I also have Retail that I can install and double check on.

Also removed the 3rd error, I'd previously had a mod installed and tweaked a few files. The Steam library was installed to the default location (Program Files), so my modified files were saved to the Virtual Store as Notepad++ didn't have write permission to the Steam Library folder, and thus escaped the backing up of the original gamedata folder. I've subsequentially removed the virtual store files, and moved the install location to a non admin protected folder, so that should no longer be an issue.

Attached log files for both creating a new game, and loading a saved game. Github won't let me upload the .bkp files, if you need them I can upload them elsewhere.

Also, is there a github project for contributing to the CS Gamedata compatibilty patch? I do know from my previous experience moddding there were a few changes between the CS and CoP engines that resulted in some slightly different Gamedata configurations, so some further changes would need to be made to Clear Sky in order to better leverage the OpenXRay engine.

[openxray_alex_newgame.log](https://github.com/OpenXRay/xray-16/files/6135823/openxray_alex_newgame.log)
[openxray_alex_loadgame.log](https://github.com/OpenXRay/xray-16/files/6135824/openxray_alex_loadgame.log)

**Comment by Xottab-DUTY** [comment]
If the third error is fixed, then this issue is fixed :)

Those first two are normal, you will get them even in vanilla Clear Sky. (if you will use Mixed version of the vanilla engine)
So, we won't fix them.

> Also, is there a github project for contributing to the CS Gamedata compatibilty patch? I do know from my previous experience moddding there were a few changes between the CS and CoP engines that resulted in some slightly different Gamedata configurations, so some further changes would need to be made to Clear Sky in order to better leverage the OpenXRay engine.

No GitHub project, I'm just manually packing that archives myself.
We can discuss it in #382.
