### ISSUE TITLE
Падает на любом виде освещения кроме "статичного".

### ISSUE THREAD

**Issue by Therises** [OpenXRay/xray-16#747]
Собственно сабж - игра вылетает (без баг репорта) после загрузки, как я предполагаю вместо появления надписи "Нажмите любую кнопку". 
Используемые моды: AtmosFear3, AbsoluteNature4, FWR CoP Edition 0.9 RC
Еле-еле добился того чтобы оно хотя бы просто в игру заходило.

**Comment by Xottab-DUTY** [comment]
Дай, пожалуйста, лог и отчёт вылета BugTrap. Они находятся в папке с игрой/_appdata_ в папках reports и logs.

Так же, если я не ошибаюсь, у FWR своя версия движка, поэтому мод может быть несовместим с OpenXRay. (даже несмотря на то, что там указан OpenXRay как движок)

**Comment by Therises** [comment]
Да, точно, у них там своя какая-то, не совместимая с новой версией. Логи не смогу скинуть, так как удалил всё и установил заново, но без atmosfear и оставил движок от FWR - оно хотя бы работает так ;)
Спасибо за быстрый ответ и за всю проделанную работу :)
