### ISSUE TITLE
The game always modesets to 60hz when using "real" fullscreen (SDL_WINDOW_FULLSCREEN)

### ISSUE THREAD

**Issue by ritalat** [OpenXRay/xray-16#777]
**Describe the bug**
When running the game on true fullscreen mode on a high refresh rate display (144hz in my case) it always changes the display refresh rate to 60hz, even when "Frequency 60Hz" setting is disabled.

**To Reproduce**
Steps to reproduce the behavior: (on a high refresh rate monitor)
1. Delete old configs
2. Start the game
3. Disable the "Frequency 60Hz" setting, change to native resolution and keep fullscreen enabled
4. Restart the game
5. The game still modesets your display to 60hz

**Expected behavior**
The game should use your display's native refresh rate when "Frequency 60Hz" is disabled.

**Desktop (please complete the following information):**
 - OS: Arch Linux (KDE 5.21.4, Mesa 21.0.2)
 - OpenXRay build version 8109

**Additional context**
Manually updating vid_refresh to 144 in user.ltx or using windowed mode at full screen resolution circumvents this issue.

**Comment by Xottab-DUTY** [comment]
Thank you for the feedback!

Will try to look at it when I figure out other tasks.

**Comment by LethalManBoob** [comment]
vid_refresh 144 doesnt work for you?

**Comment by Xottab-DUTY** [comment]
@ritalat, hi, just fixed the issue. Please, check it with the latest nightly builds, if you can 🙂

**Comment by ritalat** [comment]
@Xottab-DUTY, unfortunately fullscreen mode still only uses 60hz until I manually update vid_refresh

**Comment by Xottab-DUTY** [comment]
@ritalat, the game preserves vid_refresh value if it exists in user.ltx, but it selects maximal possible refresh rate when you disable "Refresh 60hz" option. (which is on by default)
Can you try to enable and disable this option?

**Comment by ritalat** [comment]
Enabling or disabling "Refresh 60hz" doesn't seem to do anything.

**Comment by Xottab-DUTY** [comment]
@ritalat, hmm... Strange.. Even if you type `rs_refresh_60hz off` (even if it's already disabled) and then type `vid_restart`?

**Comment by ritalat** [comment]
@Xottab-DUTY, no change. vid_refresh stays at 60.

**Comment by Xottab-DUTY** [comment]
TODO for myself:
- [x] Set desktop resolution on the first launch instead of maximal available.
- [x] Select desktop refresh rate on the first launch instead of default predefined 60hz.
- [x] When disabling `rs_refresh_60hz`, select desktop refresh rate instead of maximal.

Update: done in d7a55b074bc1b88ac2ca6f30d8307103c95eac1e.

**Comment by Xottab-DUTY** [comment]
@ritalat, please, check it now. It's recommended to remove user.ltx or, at least, remove `vid_refresh` and `rs_refresh_60hz` lines from user.ltx.

**Comment by ritalat** [comment]
It seems to be working now.
Thank you! :slightly_smiling_face:
