### ISSUE TITLE
Doesn't compile to Linux Mint 20.1

### ISSUE THREAD

**Issue by sidreshot** [OpenXRay/xray-16#778]
Doesn't compile to ubuntu.
Unable to compile. The error is strange and it is not clear what the reason is.

OS:
Distributor ID:	Linuxmint
Description:	Linux Mint 20.1
Release:	20.1
Codename:	ulyssa

Build commands:
git clone https://github.com/OpenXRay/xray-16.git --recursive
cd xray-16 && mkdir bin && cd bin
cmake ..
sudo make -j4

stack trace:
[ 17%] Building CXX object src/xrCore/CMakeFiles/xrCore.dir/XML/tinyxmlerror.cpp.o
[ 17%] Building CXX object src/xrCore/CMakeFiles/xrCore.dir/XML/tinyxmlparser.cpp.o
[ 17%] Building CXX object src/xrCore/CMakeFiles/xrCore.dir/XML/XMLDocument.cpp.o
[ 17%] Linking CXX shared library ../../x64/RelWithDebInfo/xrCore.so
/home/crapbug/xray-16/Externals/cryptopp/filters.h:1392: error: undefined reference to 'CryptoPP::StringStore::TransferTo2(CryptoPP::BufferedTransformation&, unsigned long&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)'
CMakeFiles/xrCore.dir/Crypto/xr_dsa.cpp.o:xr_dsa.cpp:vtable for CryptoPP::SourceTemplate<CryptoPP::StringStore>: error: undefined reference to 'CryptoPP::BufferedTransformation::Skip(unsigned long)'
CMakeFiles/xrCore.dir/Crypto/xr_dsa.cpp.o:xr_dsa.cpp:vtable for CryptoPP::SourceTemplate<CryptoPP::StringStore>: error: undefined reference to 'CryptoPP::Filter::TransferTo2(CryptoPP::BufferedTransformation&, unsigned long&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)'
CMakeFiles/xrCore.dir/Crypto/xr_dsa.cpp.o:xr_dsa.cpp:vtable for CryptoPP::SourceTemplate<CryptoPP::StringStore>: error: undefined reference to 'CryptoPP::Filter::CopyRangeTo2(CryptoPP::BufferedTransformation&, unsigned long&, unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) const'
CMakeFiles/xrCore.dir/Crypto/xr_dsa.cpp.o:xr_dsa.cpp:vtable for CryptoPP::StringSource: error: undefined reference to 'CryptoPP::BufferedTransformation::Skip(unsigned long)'
CMakeFiles/xrCore.dir/Crypto/xr_dsa.cpp.o:xr_dsa.cpp:vtable for CryptoPP::StringSource: error: undefined reference to 'CryptoPP::Filter::TransferTo2(CryptoPP::BufferedTransformation&, unsigned long&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)'
CMakeFiles/xrCore.dir/Crypto/xr_dsa.cpp.o:xr_dsa.cpp:vtable for CryptoPP::StringSource: error: undefined reference to 'CryptoPP::Filter::CopyRangeTo2(CryptoPP::BufferedTransformation&, unsigned long&, unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) const'
CMakeFiles/xrCore.dir/Crypto/xr_dsa.cpp.o:xr_dsa.cpp:vtable for CryptoPP::AutoSeededRandomPool: error: undefined reference to 'CryptoPP::RandomPool::GenerateIntoBufferedTransformation(CryptoPP::BufferedTransformation&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long)'
collect2: error: ld returned 1 exit status
make[2]: *** [src/xrCore/CMakeFiles/xrCore.dir/build.make:1282: x64/RelWithDebInfo/xrCore.so] Ошибка 1
make[1]: *** [CMakeFiles/Makefile2:1330: src/xrCore/CMakeFiles/xrCore.dir/all] Ошибка 2
make: *** [Makefile:152: all] Ошибка 2

**Comment by johndoe71rus** [comment]
run 
git submodule deinit Externals/cryptopp
after update repo.
for linux used system lib

**Comment by sidreshot** [comment]
> run
> git submodule deinit Externals/cryptopp
> after update repo.
> for linux used system lib
Make complete. Thanks
