### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by sidreshot** [OpenXRay/xray-16#779]
Error:
xr_3da -fsltx /home/crapbug/Games/STALKER_COP/fsgame.ltx
xr_3da: symbol lookup error: /usr/lib/x86_64-linux-gnu/libfreeimage.so.3: undefined symbol: jpeg_read_icc_profile, version LIBJPEG_8.0

Everything was installed according to the instructions. I tried to reinstall packages.

**Comment by Masterkatze** [comment]
What is your distro and its version?

**Comment by sidreshot** [comment]
Linux Mint 20.1

**Comment by sidreshot** [comment]
> What is your distro and its version?

Linux Mint 20.1

**Comment by vitaly-gaiduk** [comment]
@sidreshot is _libjpeg-turbo8_ installed in your system? Check please.

**Comment by Xottab-DUTY** [comment]
Fixed with 79ab007c1953096fe8661d50f4a493b86a0c9b89
