### ISSUE TITLE
Resource linking ignores installation prefix

### ISSUE THREAD

**Issue by OPNA2608** [OpenXRay/xray-16#786]
**Describe the bug**
https://github.com/OpenXRay/xray-16/blob/705d957fbbbb01cc5b86e83708917a5d17c4428e/src/xrCore/xrCore.cpp#L265-L287

This code ignores the user-configurable prefix for the build to which these file & directories actually get installed to.

https://github.com/OpenXRay/xray-16/blob/705d957fbbbb01cc5b86e83708917a5d17c4428e/CMakeLists.txt#L15-L16

https://github.com/OpenXRay/xray-16/blob/705d957fbbbb01cc5b86e83708917a5d17c4428e/res/CMakeLists.txt#L3-L7

We currently need to patch this in Nixpkgs to point to our build's prefix instead.

https://github.com/NixOS/nixpkgs/blob/ce93c98ce2243a8228419fcfbe97fd87f3c5f99e/pkgs/games/openxray/default.nix#L57-L60

**To Reproduce**
1. Pass `-DCMAKE_INSTALL_PREFIX=/some/path/that/isnt/the/default` to CMake
2. Build & install OpenXRay
3. Launch OpenXRay in a way that would enter the mentioned block of code

The created symlinks should point to invalid (or at least for this particular build incorrect) paths.

**Expected behavior**
The code should use the prefix the user passed to CMake (e.g. `/nix/store/v9s3qr21cf15lx3lgp1x4d4k8pdcc2an-openxray-822-december-preview`) instead of hardcoding `/usr`.

**Screenshots**
n/a

**BugTrap error report**
n/a

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.5 (with Nixpkgs) & NixOS 20.09
 - OpenXRay build version: 822

**Additional context**
I think `CMAKE_INSTALL_FULL_DATAROOTDIR` is the CMake variable the fixed code should somehow get access to. `CMAKE_INSTALL_DATAROOTDIR` works for moving files but it may be a relative path, while `CMAKE_INSTALL_FULL_DATAROOTDIR` is guaranteed to be an absolute one.

**Comment by Xottab-DUTY** [comment]
@eagleivg and @007exe, what do you think?

**Comment by OPNA2608** [comment]
Invalid links can still occur on Nixpkgs even with this fixed: When the originally version is replaced with a new version under a different prefix (e.g. a version update from `/nix/store/qv655q99xg332j0rynbwvw5q0vg4c5nz-OpenXRay-730-july-preview` to `/nix/store/abpcj5d5zaxzn56i46bj7gyp5ypjnbbl-openxray-822-december-preview`, or same version but reinstalled from `/usr` to `/opt`) and the original version is removed from the drive, the original link to a now-deleted path persists. Maybe the existing links should be checked if they still point to valid files/directories and relinked on startup if they don't?

```
…
Starting RENDER device...
* GPU vendor: [X.Org] device: [AMD Radeon RX 5700 XT (NAVI10, DRM 3.40.0, 5.11.13, LLVM 9.0.1)]
* GPU OpenGL version: 4.6 (Core Profile) Mesa 20.1.10
* GPU OpenGL shading language version: 4.60
* GPU OpenGL VTF units: [32] CTI units: [192]
* DVB created: 4096K
* DIB created: 512K
! Renderer doesn't support blender 'effects\shadow_world'
 
FATAL ERROR
 
[error] Expression    : skinh
[error] Function      : CompatibilityCheck
[error] File          : /build/source/src/Layers/xrRender/ResourceManager.cpp
[error] Line          : 279
[error] Description   : Can't open shader
[error] Arguments     : skin.h
 

stack trace:

xrDebug::GatherInfo(char*, unsigned long, ErrorLocation const&, char const*, char const*, char const*, char const*)
xrDebug::Fail(bool&, ErrorLocation const&, char const*, char const*, char const*, char const*)
/nix/store/abpcj5d5zaxzn56i46bj7gyp5ypjnbbl-openxray-822-december-preview/lib/xrRender_GL.so(+0xee141) [0x7f0c2012a141]
/nix/store/abpcj5d5zaxzn56i46bj7gyp5ypjnbbl-openxray-822-december-preview/lib/xrRender_GL.so(+0xa5033) [0x7f0c200e1033]
/nix/store/abpcj5d5zaxzn56i46bj7gyp5ypjnbbl-openxray-822-december-preview/lib/xrEngine.so(+0x41007) [0x7f0c4aed3007]
Startup()
RunApplication()
/home/bt1cn/.nix-profile/bin/xr_3da() [0x401c90]
/home/bt1cn/.nix-profile/bin/xr_3da() [0x4019ee]
/nix/store/v8q6nxyppy1myi3rxni2080bv8s9jxiy-glibc-2.32-40/lib/libc.so.6(__libc_start_main+0xed) [0x7f0c49c7fded]
/home/bt1cn/.nix-profile/bin/xr_3da(_start+0x2a) [0x401ada]
fish: 'xr_3da' terminated by signal SIGTRAP (Verfolgungs- oder Haltepunkt erreicht)

↪ ll ~/.local/share/GSC\ Game\ World/S.T.A.L.K.E.R.\ -\ Call\ of\ Pripyat/gamedata/shaders/
insgesamt 0
drwxr-xr-x 2 bt1cn users  16  6. Apr 21:04 .
drwxr-xr-x 4 bt1cn users  37  6. Apr 21:04 ..
lrwxrwxrwx 1 bt1cn users 104 15. Mär 21:39 gl -> /nix/store/qv655q99xg332j0rynbwvw5q0vg4c5nz-OpenXRay-730-july-preview/share/openxray/gamedata/shaders/gl

↪ ll /nix/store/qv655q99xg332j0rynbwvw5q0vg4c5nz-OpenXRay-730-july-preview
ls: Zugriff auf '/nix/store/qv655q99xg332j0rynbwvw5q0vg4c5nz-OpenXRay-730-july-preview' nicht möglich: No such file or directory

# Removing ~/.local/share/GSC\ Game\ World/S.T.A.L.K.E.R.\ -\ Call\ of\ Pripyat/gamedata/shaders/gl and launching xr_3da again makes a link to the new location, game now runs fine
```
