### ISSUE TITLE
DX11 renderer doesn't work

### ISSUE THREAD

**Issue by nitrocaster** [OpenXRay/xray-16#8]
The problem is that IID_ID3D11ShaderReflection guid from Windows SDK is not accepted by d3dcompiler from DirectX SDK.
In future it would be reasonable to get rid of old DirectX SDK and use Windows SDK only.

**Comment by ghost** [comment]
The game really starts in DX11, but i can't start a new game (latest repo files+full rebuild with release config+vanilla gamedata+system.ltx fix):

stack trace:

0023:06A20C69 xrGame.dll, CEntity::shedule_Update(), d:\src\xrgame\entity.cpp, 328
0023:06A2371D xrGame.dll, CEntityAlive::shedule_Update(), d:\src\xrgame\entity_alive.cpp, 210
0023:068A5EFA xrGame.dll, CActor::shedule_Update(), d:\src\xrgame\actor.cpp, 1222
0023:00457965 xrEngine.exe, CSheduler::Update(), d:\src\xrengine\xrsheduler.cpp, 454
0023:06A3A700 xrGame.dll, CGamePersistent::OnFrame(), d:\src\xrgame\gamepersistent.cpp, 662
0023:0040C111 xrEngine.exe, CRegistrator<pureFrame>::Process(), d:\src\xrengine\pure.h, 86
0023:00435AAA xrEngine.exe, CRenderDevice::FrameMove(), d:\src\xrengine\device.cpp, 486
0023:00435D09 xrEngine.exe, CRenderDevice::on_idle(), d:\src\xrengine\device.cpp, 263
0023:00435C3A xrEngine.exe, CRenderDevice::message_loop(), d:\src\xrengine\device.cpp, 380
0023:00435B8E xrEngine.exe, CRenderDevice::Run(), d:\src\xrengine\device.cpp, 424
0023:0046A92D xrEngine.exe, Startup(), d:\src\xrengine\x_ray.cpp, 383
0023:00469685 xrEngine.exe, WinMain_impl(), d:\src\xrengine\x_ray.cpp, 873
0023:004691D6 xrEngine.exe, WinMain(), d:\src\xrengine\x_ray.cpp, 942
0023:00432BF3 xrEngine.exe, __tmainCRTStartup(), f:\dd\vctools\crt\crtw32\dllstuff\crtexe.c, 618
0023:7577338A kernel32.dll
0023:77D29F72 ntdll.dll
0023:77D29F45 ntdll.dll

[error][      87]    : The parameter is incorrect.

**Comment by nitrocaster** [comment]
That seems to be some other unrelated problem.
I've tested both single- and multiplayer on DX11.

**Comment by ghost** [comment]
Weird, i can't start a new game now, and i didn't modify the repo stuff at all.
