### ISSUE TITLE
__attribute__((destructor)) is a bad place for cleanup, so xr_3da fails assert on termination

### ISSUE THREAD

**Issue by kosumosu** [OpenXRay/xray-16#804]
I faced several failed assertions in mimalloc when I was trying to close the game.

I started investigating this and found out that the problem was not in the allocator itself, but in the fact that the allocator was destroyed BEFORE the failed assertion. Further investigation has shown that even though `SDL_UnloadObject()` is called before returning from `main()`, the `__attribute__((destructor)) unload()` is called AFTER return from `main()`. So global variables inside `xrGame.so` turn into a garbage by the time the control reaches `unload()`.
This causes xray to crash every time it terminates on e2k. It also leads to hanging fullscreen, causing big trouble to a user.

> Although a dlclose() operation is not required to remove structures from an address space, neither is an implementation prohibited from doing so.
https://pubs.opengroup.org/onlinepubs/007904975/functions/dlclose.html

So resources from shared libraries must be cleaned up explicitly instead.

**Comment by kosumosu** [comment]
This is mainly Linux-related. And in theory, not only on Elbrus.

**Comment by Xottab-DUTY** [comment]
@kosumosu, I just pushed 810692a400ad17bc1d0123dd0ebc33e6cc9c899c to fix this problem. Please, test it. :)

Also, can you test it with disabled workaround for GCC in `FACTORY_PTR_INSTANCIATE` in `src/Include/xrRender/FactoryPtr.h`?

**Comment by kosumosu** [comment]
I confirm, the game doesn't crash anymore 👍

**Comment by Xottab-DUTY** [comment]
@kosumosu doesn't crash even with removed FACTORY_PTR_INSTANCIATE workaround?

**Comment by kosumosu** [comment]
I'm trying this right now...

**Comment by kosumosu** [comment]
@Xottab-DUTY Without it I got SIGSEGV when tried to "exit to windows" from menu right away.

```
1 CUIStatsIcon::TEX_INFO::~TEX_INFO()   0x4555b0442c58 
2 __cxa_vec_dtor                        0x455558421338 
3 __run_exit_handlers                   0x455558957d68 
4 exit                                  0x4555589587f0 
5 __libc_start_main                     0x4555588f5048 
6 _start                                0x1c1e0        

```

**Comment by Xottab-DUTY** [comment]
@kosumosu, hi! Could you please try to remove FACTORY_PTR_INSTANCIATE workaround in `src/Include/xrRender/FactoryPtr.h` again and test it?
In a914f65531becd5e0b42fa5979fcd5ef78ecdd57 I've changed how `CUIStatsIcon::TEX_INFO` works, so it might help with that.

**Comment by kosumosu** [comment]
That have been a long time. I'm not sure I still have access to e2k and have proper setup...

**Comment by Xottab-DUTY** [comment]
@kosumosu, this should be reproducible on any Linux machine I think.
