### ISSUE TITLE
Build failed with submodules

### ISSUE THREAD

**Issue by ChugunovRoman** [OpenXRay/xray-16#812]
After I cloned my fork of main repo via `git clone git@github.com:ChugunovRoman/xray-16.git --recurse-submodules`\
Build steps:
1. mkdir bin && cd bin
2. cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=lib
3. make -j8

And I got error:
<details>
<summary>Output</summary>
<pre>
In file included from /home/ruut/Projects/otherProjects/xray-16/src/Common/Config.hpp:22,
                 from /home/ruut/Projects/otherProjects/xray-16/src/Common/Common.hpp:3,
                 from /home/ruut/Projects/otherProjects/xray-16/src/utils/xrMiscMath/pch.hpp:3,
                 from /home/ruut/Projects/otherProjects/xray-16/bin/src/utils/xrMiscMath/CMakeFiles/xrMiscMath.dir/cmake_pch.hxx:5,
                 from <command-line>:
/home/ruut/Projects/otherProjects/xray-16/Externals/submodule_check.hpp:4:2: error: #error "You probably have downloaded OpenXRay sources as ZIP archive, you can't do that. Use git to clone the repository.    Read the build instructions: https://github.com/OpenXRay/xray-16/wiki"
    4 | #error "You probably have downloaded OpenXRay sources as ZIP archive, you can't do that. Use git to clone the repository.\
      |  ^~~~~
In file included from /home/ruut/Projects/otherProjects/xray-16/src/Common/Config.hpp:22,
                 from /home/ruut/Projects/otherProjects/xray-16/src/Common/Common.hpp:3,
                 from /home/ruut/Projects/otherProjects/xray-16/Externals/cximage/ximacfg.h:7,
                 from /home/ruut/Projects/otherProjects/xray-16/Externals/cximage/ximacfg.cpp:1:
/home/ruut/Projects/otherProjects/xray-16/Externals/submodule_check.hpp:4:2: error: #error "You probably have downloaded OpenXRay sources as ZIP archive, you can't do that. Use git to clone the repository.    Read the build instructions: https://github.com/OpenXRay/xray-16/wiki"
    4 | #error "You probably have downloaded OpenXRay sources as ZIP archive, you can't do that. Use git to clone the repository.\
      |  ^~~~~
-- The C compiler identification is GNU 11.1.0
</pre>
</details>

<details>
<summary>ls -la Externals/luabind/luabind</summary>
<pre>
total 260
drwxr-xr-x 3 ruut ruut  4096 Jun  1 10:41 ./
drwxr-xr-x 7 ruut ruut  4096 Jun  1 10:41 ../
-rw-r--r-- 1 ruut ruut  3777 Jun  1 10:41 adopt_policy.hpp
-rw-r--r-- 1 ruut ruut  1500 Jun  1 10:41 back_reference_fwd.hpp
-rw-r--r-- 1 ruut ruut  3091 Jun  1 10:41 back_reference.hpp
-rw-r--r-- 1 ruut ruut 19346 Jun  1 10:41 class.hpp
-rw-r--r-- 1 ruut ruut  1676 Jun  1 10:41 class_info.hpp
-rw-r--r-- 1 ruut ruut  4770 Jun  1 10:41 config.hpp
-rw-r--r-- 1 ruut ruut  3696 Jun  1 10:41 container_policy.hpp
-rw-r--r-- 1 ruut ruut  1095 Jun  1 10:41 copy_policy.hpp
-rw-r--r-- 1 ruut ruut  3452 Jun  1 10:41 dependency_policy.hpp
drwxr-xr-x 3 ruut ruut  4096 Jun  1 10:41 detail/
-rw-r--r-- 1 ruut ruut  2046 Jun  1 10:41 discard_result_policy.hpp
-rw-r--r-- 1 ruut ruut  1765 Jun  1 10:41 error_callback_fun.hpp
-rw-r--r-- 1 ruut ruut  3242 Jun  1 10:41 error.hpp
-rw-r--r-- 1 ruut ruut  1639 Jun  1 10:41 exception_handler.hpp
-rw-r--r-- 1 ruut ruut  1499 Jun  1 10:41 from_stack.hpp
-rw-r--r-- 1 ruut ruut  1428 Jun  1 10:41 function.hpp
-rw-r--r-- 1 ruut ruut  1920 Jun  1 10:41 function_introspection.hpp
-rw-r--r-- 1 ruut ruut   523 Jun  1 10:41 get_main_thread.hpp
-rw-r--r-- 1 ruut ruut  3784 Jun  1 10:41 handle.hpp
-rw-r--r-- 1 ruut ruut  4720 Jun  1 10:41 iterator_policy.hpp
-rw-r--r-- 1 ruut ruut  1293 Jun  1 10:41 lua_argument_proxy.hpp
-rw-r--r-- 1 ruut ruut  1427 Jun  1 10:41 luabind.hpp
-rw-r--r-- 1 ruut ruut  1530 Jun  1 10:41 lua_extensions.hpp
-rw-r--r-- 1 ruut ruut  1335 Jun  1 10:41 lua_include.hpp
-rw-r--r-- 1 ruut ruut  3196 Jun  1 10:41 lua_index_proxy.hpp
-rw-r--r-- 1 ruut ruut  5481 Jun  1 10:41 lua_iterator_proxy.hpp
-rw-r--r-- 1 ruut ruut  1754 Jun  1 10:41 lua_proxy.hpp
-rw-r--r-- 1 ruut ruut  9180 Jun  1 10:41 lua_proxy_interface.hpp
-rw-r--r-- 1 ruut ruut  1359 Jun  1 10:41 lua_state_fwd.hpp
-rw-r--r-- 1 ruut ruut  3634 Jun  1 10:41 make_function.hpp
-rw-r--r-- 1 ruut ruut  4311 Jun  1 10:41 memory_allocator.hpp
-rw-r--r-- 1 ruut ruut  2358 Jun  1 10:41 memory.hpp
-rw-r--r-- 1 ruut ruut  1321 Jun  1 10:41 nil.hpp
-rw-r--r-- 1 ruut ruut   686 Jun  1 10:41 no_dependency.hpp
-rw-r--r-- 1 ruut ruut  1291 Jun  1 10:41 object.hpp
-rw-r--r-- 1 ruut ruut  1369 Jun  1 10:41 open.hpp
-rw-r--r-- 1 ruut ruut  7986 Jun  1 10:41 operator.hpp
-rw-r--r-- 1 ruut ruut  8041 Jun  1 10:41 out_value_policy.hpp
-rw-r--r-- 1 ruut ruut  3532 Jun  1 10:41 pointer_traits.hpp
-rw-r--r-- 1 ruut ruut  1266 Jun  1 10:41 prefix.hpp
-rw-r--r-- 1 ruut ruut  1919 Jun  1 10:41 raw_policy.hpp
-rw-r--r-- 1 ruut ruut  2391 Jun  1 10:41 return_reference_to_policy.hpp
-rw-r--r-- 1 ruut ruut  2578 Jun  1 10:41 scope.hpp
-rw-r--r-- 1 ruut ruut  1927 Jun  1 10:41 set_package_preload.hpp
-rw-r--r-- 1 ruut ruut  2082 Jun  1 10:41 shared_ptr_converter.hpp
-rw-r--r-- 1 ruut ruut   980 Jun  1 10:41 typeid.hpp
-rw-r--r-- 1 ruut ruut  1393 Jun  1 10:41 types.hpp
-rw-r--r-- 1 ruut ruut   514 Jun  1 10:41 version.hpp
-rw-r--r-- 1 ruut ruut  1742 Jun  1 10:41 weak_ref.hpp
-rw-r--r-- 1 ruut ruut  3639 Jun  1 10:41 wrapper_base.hpp
-rw-r--r-- 1 ruut ruut  1572 Jun  1 10:41 yield_policy.hpp
</pre>
</details>

All submodules was initialized. if commented `#include "submodule_check.hpp"` in `src/Common/Config.hpp` then code will compile successful. Maybe need to rewrite the condition for determining the presence of submodules?

uname -a:
```
Linux arch-linux 5.12.7-arch1-1 #1 SMP PREEMPT Wed, 26 May 2021 22:03:57 +0000 x86_64 GNU/Linux
```

**Comment by Xottab-DUTY** [comment]
The problem is that CxImage cannot find the path to luabind

**Comment by ChugunovRoman** [comment]
> The problem is that CxImage cannot find the path to luabind

Is it depend of any environment variable or other environment settings?

**Comment by ChugunovRoman** [comment]
This error also appeared in CI, then it is not depend of environment, I think
Very strange

**Comment by ChugunovRoman** [comment]
I replaced path to luabind from `luabind/luabind.hpp` to `luabind/luabind/luabind.hpp` and now got successful build.

![screenshot_2021-06-01T12:56:41](https://user-images.githubusercontent.com/20404541/120305627-a8c35f00-c2d9-11eb-8289-505188cc7663.jpg)

![screenshot_2021-06-01T12:56:56](https://user-images.githubusercontent.com/20404541/120305638-ad881300-c2d9-11eb-8a5a-265d8a8264bd.jpg)
