### ISSUE TITLE
xrRender_GL.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by RichardTry** [OpenXRay/xray-16#816]
1.
```
$ ls
cximage.a      libmimalloc.so      libxrMiscMath.a    mimalloc-test-stress  xrAICore.so  xrCore.so    xrGameSpy.so  xrLuajit.so     xrPhysics.so       xrSound.so
libGameSpy.a   libmimalloc.so.1.6  libxrQSlim.a       OPCODE.so             xrAPI.so     xrEngine.so  xrLCUtil.so   xrNetServer.so  xrRender_GL.so     xrUICore.so
libmimalloc.a  libODE.so           mimalloc-test-api  xr_3da                xrCDB.so     xrGame.so    xrLuabind.so  xrParticles.so  xrScriptEngine.so
```
2.
```
$ LD_LIBRARY_PATH=. ./xr_3da 
```
3.
```
! Failed loading xrRender_GL.so: xrRender_GL.so: cannot open shared object file: No such file or directory
```

**Comment by Xottab-DUTY** [comment]
Can you share the full log or look at the text above the `! Failed loading xrRender_GL.so.. ` by yourself?
Probably, some required dependency like FreeImage is missing or installed version is incompatible with the version that xrRender_GL needs. (this frequently happens especially with FreeImage)

**Comment by RichardTry** [comment]
libfreeimage3 и libfreeimageplus3 установлены, никаких других ошибок до этой нету.

**Comment by vitaly-gaiduk** [comment]
@RichardTry set LD_LIBRARY_PATH variable with absolute path to libs not relative please. For example:
`$ export LD_LIBRARY_PATH=/home/retr0/git/xray-16/bin/x64/Release`
And run:
`$ ./xr_3da`

To save current value in LD_LIBRARY_PATH use:
`$ export LD_LIBRARY_PATH=/home/retr0/git/xray-16/bin/x64/Release:$LD_LIBRARY_PATH`

**Comment by Xottab-DUTY** [comment]
Does engine work well with the latest commits?
