### ISSUE TITLE
Invalid memory order after MSCV building

### ISSUE THREAD

**Issue by vitaly-gaiduk** [OpenXRay/xray-16#820]
I built all project with Debug configuration using 'How to...' manual and required VS items (CRT, SDK etc.). But when I launch engine with CoP or CS (Steam version) it is displayed debug assertion:
![assertion](https://user-images.githubusercontent.com/43039361/121028227-50480200-c7b0-11eb-8b55-316ea404e184.png)

Are there any subtleties with building or what have I missed?

OS: Windows 10 21H1 19043.985
MSVC: Microsoft Visual Studio Community 2019 ver. 16.10.0

P.S. There is no any usable info in log but I've attached it.
[openxray_vitaly.log](https://github.com/OpenXRay/xray-16/files/6609542/openxray_vitaly.log)

**Comment by Xottab-DUTY** [comment]
Don't use Debug. It is not designed for playing or debugging gameplay... Only hard debugging the memory, etc.

**Comment by Xottab-DUTY** [comment]
Also, you have built the outdated version, this exact error was already fixed.

**Comment by vitaly-gaiduk** [comment]
Yep, updated branch and built Mixed config - it works! Close issue.
