### ISSUE TITLE
Constant crashing after reaching the half of Limanks level.

### ISSUE THREAD

**Issue by DarkJoney** [OpenXRay/xray-16#828]
**Describe the bug**
The game simply starts to crash with the black screen in 1-5 mins or immediately. The repeatable crashing starts after we help the group of clear sky to fight for the house, a moment before the bus surrounded with space anomaly at Limansk. Before this moment the game worked perfectly. 

The console says this:
! [LUA][ERROR]  ERROR: Invalid AI map at kamp point [lim_smart_terrain_9_kamp_1]
stack traceback:
	...es\s.t.a.l.k.e.r. Чистое Небо\gamedata\scripts\_g.script:974: in function 'abort'
	...t.a.l.k.e.r. Чистое Небо\gamedata\scripts\xr_kamp.script:309: in function 'getDestVertex'
	...t.a.l.k.e.r. Чистое Небо\gamedata\scripts\xr_kamp.script:58: in function <...t.a.l.k.e.r. Чистое Небо\gamedata\scripts\xr_kamp.script:54>
 
FATAL ERROR
 
[error] Expression    : 0
[error] Function      : ErrorLog
[error] File          : C:\projects\xray-16\src\xrScriptEngine\ScriptEngineScript.cpp
[error] Line          : 40
[error] Description   : ERROR: Invalid AI map at kamp point [lim_smart_terrain_9_kamp_1]

**To Reproduce**
Reach the point of the level described before. 

**Expected behavior**

I expected that I would be able to completely pass Clear Sky with the current build of openXray. I am not able to pass Limansk level since the game crashes each few mins or after the save loading at the explained point of the level. The crash appears absolutely randomly, but for now, I can't stay at the level for longer than 2-5 mins. 

**Screenshots**

**BugTrap error report**
Please, add a crashreport if you have it. It should be located in `_appdata_/reports` folder
[OpenXRay_error_report_210621-231657.zip](https://github.com/OpenXRay/xray-16/files/6689305/OpenXRay_error_report_210621-231657.zip)
[OpenXRay_error_report_210621-231645.zip](https://github.com/OpenXRay/xray-16/files/6689308/OpenXRay_error_report_210621-231645.zip)
[OpenXRay_error_report_210621-231422.zip](https://github.com/OpenXRay/xray-16/files/6689309/OpenXRay_error_report_210621-231422.zip)
[OpenXRay_error_report_210617-145211.zip](https://github.com/OpenXRay/xray-16/files/6689312/OpenXRay_error_report_210617-145211.zip)
[OpenXRay_error_report_210616-221438.zip](https://github.com/OpenXRay/xray-16/files/6689319/OpenXRay_error_report_210616-221438.zip)

**Desktop (please complete the following information):**
 - OS: Window 10 20H2
 - OpenXRay build version December 2020 Preview Install and Play
 - i7 5820K
 - RTX 2080 (466.27)

**Additional context**
I have tried to run it with R4, original DX10 renderers, static one, but nothing helps.
The compartibility with Win 7 also does nothing.

This is very pity, because in the general it runs very well and I expected 0 crashes before reaching of this point of the game.

**Comment by Xottab-DUTY** [comment]
Unfortunately, this is the number one serious bug that we didn't figure out how to fix yet.
This crash with "Invalid AI map at kamp point" can appear even on swamps in the beginning of the game and it can be avoided by avoiding the place where this crash happens...

But since Limansk is a corridor location and it is impossible to avoid that house, the only thing can help is to load the game saves before reaching that house (I'd recommend to load a save before even entering Limansk) and hope that stalkers will refuse to go to that invalid kamp. (kamp is just incorrect spelling of camp)

**Comment by makpif** [comment]
Тоже встретил этот баг. Также иногда вылет происходит не в доме, а уже после телепортов. Причем если сохранится между домом и вылетом, а потом загрузить сейв будет 1-2 fps. Ждал долго, лагать не перестало

OS: Linux

**Comment by BielBdeLuna** [comment]
how can I help solve this? playing along gdb maybe and returning the stack would help you?
what places in swamp have this problem? as far as I know, this is error is not activated by the player but by another unit in the faction war isn't it?

**Comment by DarkJoney** [comment]
mate, I don't remember exactly. I should give it a second try since it is labeled as closed, am sitting at home anyway now.

**Comment by BielBdeLuna** [comment]
are my assumptions right thou?
- is this related to the faction wars units movement?

**Comment by Xottab-DUTY** [comment]
> it is labeled as closed

It is not closed. I've only closed the duplicate issue, but not this issue.
The crash is still here.

> how can I help solve this?

Gimme few minutes...

**Comment by Xottab-DUTY** [comment]
Unpack this into the game folder:
[gamedata.zip](https://github.com/OpenXRay/xray-16/files/8336983/gamedata.zip)

There's just one script with the workaround borrowed from https://github.com/OpenXRay/xray-16/issues/936#issuecomment-1024869735

**Comment by Xottab-DUTY** [comment]
> are my assumptions right thou?
> 
> * is this related to the faction wars units movement?

No, it's related to the generic camp logic, which `xr_kamp.script` is for. NPC is trying to sit near the campfire and cannot find a point where he could sit.

The original script works fine with the original Clear Sky's X-Ray 1.5 engine, but mainline OpenXRay is an Call of Pripyat engine (based on X-Ray 1.6) and, probably, something was changed under the hood... I didn't find the root of the problem yet :(

**Comment by Xottab-DUTY** [comment]
We have figured that this bug happens due to different luabind behaviour.
We need to research further in the luabind.

**Comment by Xottab-DUTY** [comment]
This may be also helpful
https://github.com/OpenXRay/xray-16/blob/dev/src/xrGame/ai/monsters/basemonster/base_monster.cpp#L467
> // sometimes accessible(object->Position())) returns true
    // but accessible(ai_location().level_vertex_id()) crashes
    // because level_vertex_id is not valid, so this code syncs vertex_id with position
```cpp
bool CBaseMonster::useful(const CItemManager* manager, const CGameObject* object) const
{
    const Fvector& object_pos = object->Position();
    if (!movement().restrictions().accessible(object_pos))
    {
        return false;
    }

    // Lain: added (temp?) guard due to bug http://tiger/bugz/view.php?id=15983
    // sometimes accessible(object->Position())) returns true
    // but accessible(ai_location().level_vertex_id()) crashes
    // because level_vertex_id is not valid, so this code syncs vertex_id with position
    if (!ai().level_graph().valid_vertex_id(object->ai_location().level_vertex_id()))
    {
        u32 vertex_id = ai().level_graph().vertex_id(object_pos);
        if (!ai().level_graph().valid_vertex_id(vertex_id))
        {
            return false;
        }
        object->ai_location().level_vertex(vertex_id);
    }

    if (!movement().restrictions().accessible(object->ai_location().level_vertex_id()))
    {
        return false;
    }

    const CEntityAlive* pCorpse = smart_cast<const CEntityAlive*>(object);
    if (!pCorpse)
    {
        return false;
    }

    if (!pCorpse->g_Alive())
    {
        return true;
    }

    return false;
}
```

**Comment by Decane** [comment]
I suggest giving the xr_kamp destination vertex assignment logic in https://github.com/Decane/SRP/commit/1377f511110c7dbe86ddc6631a19d8f01ba67a22 a try. The vanilla logic is buggy; it tries to assign NPCs to the nearest accessible vertex to `level.vertex_position(4294967296)` if the preferred campfire position is inaccessible. This doesn't cause a crash in vanilla X-Ray v1.5, but it does cause [strange NPC behavior](https://www.reddit.com/r/stalker/comments/11p5xch/weird_clear_sky_members_cssrp/).

BTW, I'm guessing `level.vertex_id(position)` in X-Ray v1.6 returns 429496729**5** for an inaccessible position, whereas X-Ray v1.5 returns 429496729**6** (which is why there is no crash with v1.5). To use the SRP logic with OpenXRay, 429496729**5** may therefore need to be substituted for 429496729**6**.

**Comment by Xottab-DUTY** [comment]
Interesting detail:
https://cs.stalker-game.com/en/?page=patches&item=1

Look at the changelog of the official patch 1.5.05:
> fixed crash (ERROR: Invalid AI map at kamp point [mar_smart_terrain_6_8_kamp_1](_g.script:973: bad argument 2 to 'format' (string expected, got nil)))

This is the smart terrain from #977.

Just as memo, the problematic kamps are:
mar_smart_terrain_6_8_kamp_1
lim_smart_terrain_9_kamp_1

**Comment by Xottab-DUTY** [comment]
> BTW, I'm guessing level.vertex_id(position) in X-Ray v1.6 returns 4294967295 for an inaccessible position, whereas X-Ray v1.5 returns 4294967296 (which is why there is no crash with v1.5).

Much thanks, @Decane! Finally the bug is fixed!

> To use the SRP logic with OpenXRay, 4294967295 may therefore need to be substituted for 4294967296.

~~It it possible to add `openxray.ltx` file to the SRP distribution with the settings that define 4294967295/4294967296 behaviour? :)~~
Oh, it's actually not needed, but it's still can be beneficial to configure other OpenXRay behaviours specifically for SRP :)

**Comment by zanghuashenwu** [comment]
stalker-anomaly Fix limansk crash feasibility?

**Comment by Xottab-DUTY** [comment]
> BTW, I'm guessing level.vertex_id(position) in X-Ray v1.6 returns 429496729**5** for an inaccessible position, whereas X-Ray v1.5 returns 429496729**6** (which is why there is no crash with v1.5). To use the SRP logic with OpenXRay, 429496729**5** may therefore need to be substituted for 429496729**6**.

It's interesting that originally compiled 1.6.02 and 1.5.10 return 429496729**6**, whereas https://github.com/OpenXRay/xray-15 compiled with VS 2015 returns 429496729**5** despite having fully original luabind and LuaJIT.
A compiler bug? A compiler preference/setting? Or some unnoticed code quirk?

This makes it problematic to be fully compatible both with vanilla and mods that utilize modern Visual Studio, LuaJIT 2.0, updated luabind.

**Comment by redpython** [comment]
> > BTW, I'm guessing level.vertex_id(position) in X-Ray v1.6 returns 429496729**5** for an inaccessible position, whereas X-Ray v1.5 returns 429496729**6** (which is why there is no crash with v1.5). To use the SRP logic with OpenXRay, 429496729**5** may therefore need to be substituted for 429496729**6**.
> 
> It's interesting that originally compiled 1.6.02 and 1.5.10 return 429496729**6**, whereas https://github.com/OpenXRay/xray-15 compiled with VS 2015 returns 429496729**5** despite having fully original luabind and LuaJIT. A compiler bug? A compiler preference/setting? Or some unnoticed code quirk?
> 
> This makes it problematic to be fully compatible both with vanilla and mods that utilize modern Visual Studio, LuaJIT 2.0, updated luabind.

Знаешь, в xr_surge_hide.script есть проверки и на то, и на другое значение. Видимо, скриптеры пыс уже сталкивались с таким поведением, а значит, можно предположить, что с большей вероятностью это зависит от настроек проекта в студии.
