### ISSUE TITLE
Extremely High chance of saves being corrupted or bugged in Call of Pripyat

### ISSUE THREAD

**Issue by l0oo0p** [OpenXRay/xray-16#840]
**Describe the bug**
Game = Stalker  Call of Pripyat

Extremely High chance of saves getting corrupted[ctd on load] or bugged[no mission ever updates or completes making the game unplayable also no rewards + all stats are reset like stashes found and for some reason the artifact hunter achievement is unlocked]

this literally makes saving the game feel like russian roulette lol, because everytime i save the game i have no idea if its corrupted/bugged or not, so i have to make a save file extremely often so to not lose progress and even then sometimes 5-6 saves back to back are just bugged

at first i thought it was because of me saving in places where a lot of npcs were but the saves get bugged/corrupted in wilderness too with no one around

this happens with all types of saves [autosaves/quicksaves/normal saves]
i have disabled autosaves and do not use quicksaves anymore only normal saves
a save is more likely to get bugged than get corrupted also

Loading a corrupted save leads to CTD where as

A bugged save loads fine but no mission objective will ever update or complete and not give any reward either + an achievement is also unlocked called artifact hunter all other stats go to 0 except artifacts found which is set to 20
Also loading a bugged save sometimes not all but sometimes will have graphical glitches too like super bright lighting or water being just super bright light or maybe its missing textures( sorry im not able to explain it properly)

i dont know if this will help but ive attached a crash report that happened when trying to load multiple bugged saves
[example: load a bugged save then load another bugged save and this crash happens]
https://github.com/OpenXRay/xray-16/files/6765952/OpenXRay_error_report_210706-000030.zip

i have also attached my save normal working save file and a bugged save file
https://github.com/OpenXRay/xray-16/files/6765967/SAVES.zip

the game is the steam version
All Game visual settings are set to max using DX11
no mods are installed

My Specs:
i7 8700
Nvidia GTX 1060 6gb
16gb ddr4 ram
playing on a SATA hard disk drive
Windows 10 64bit

I grabbed the latest openxray from AppVeyor, this is the version im using
OpenXRay.Master Gold 64-bit [e1f5104] [22-06-2021] 
[version/build "1020" this number was on AppVeyor i dunno if its version or build number]

hopefully there is some fix or workaround for this, because im loving the game but this save corrupted/bug is killing me
thank you for reading hope this info helps

**Comment by Xottab-DUTY** [comment]
This is known issue that appeared after LuaJIT update.

Please, don't use any nightly builds until this issue is fixed.
For now, the most stable version is December 2020 Preview.

**Comment by l0oo0p** [comment]
the December 2020 Preview build is working perfectly, the save issue is completely gone
thank you so much
