### ISSUE TITLE
Gamebreaking Bugged Cutscene in Yanov Causes Major NPCS to become Non-Interactable [Call of Pripyat]

### ISSUE THREAD

**Issue by l0oo0p** [OpenXRay/xray-16#841]
**Describe the bug**
 Game = Stalker Call of Pripyat

When first going from Skadovsk to Yanov with pilot, the cutscene bugs out and the player character is just standing there unable to move with no dialogue from the npcs (pilot and nitro), the player character is able to move after the cutscene ends but Pilot and Nitro cannot be interacted with anymore breaking the game, because now the player is unable to go back to other levels and progress in anyway because of being unable to interact with Pilot.

im using the x64 December 2020 Preview version of OpenXray

**Things i've tried: [none of them worked]**
Loading save game from behind multiple times
saving game after cutscene and loading again
trying x86 version of openxray [December 2020 Preview]
lowering all graphics to minimum
limiting framerate to 60
using save game with vanilla version causes ctd

the game is the steam version
no mods are installed

**To Reproduce**
1. Talk to Pilot in Skadovsk and ask him to take the player to Yanov
2. Once at Yanov the bugged Cutscene plays, with no dialogue, after a while the cutscene ends
3. After The Cutscene, the major characters[pilot + nitro] cannot be interracted with

i've attached a save file just before speaking with pilot to take player to Yanov
https://github.com/OpenXRay/xray-16/files/6770543/Saves.zip

My Specs:
i7 8700
Nvidia GTX 1060 6gb
16gb ddr4 ram
playing on a SATA hard disk drive
Windows 10 64bit

thank you for reading and please help with this issue

**Comment by Xottab-DUTY** [comment]
This bug happens even after new game start or you have used these saves from nightly builds?

Saves from nightly builds should be considered as broken and should not be used, unfortunately. :(

**Comment by l0oo0p** [comment]
> 
> 
> This bug happens even after new game start or you have used these saves from nightly builds?
> 
> Saves from nightly builds should be considered as broken and should not be used, unfortunately. :(

ah damn, yeah i used the saves from the nightly build :( 
is there no way to somehow bypass this?
welp i guess i'll have to start a new game hopefully it doesnt happen again [i will update this if the bug happens on a new game too]
thanks for replying.

**Edit: Just Tried to play the cutscene in a new game and it works completely fine**

**Comment by Xottab-DUTY** [comment]
> is there no way to somehow bypass this?

Most probably, no :(
