### ISSUE TITLE
Add HBAO+

### ISSUE THREAD

**Issue by ghost** [OpenXRay/xray-16#85]
I successfully added HBAO+ to DX11. If there's interest in it I can add it to the code this repo uses (I'm using a VS2013 version still as I'm interested in the ai_cleanup branch and that branch isn't ready yet).

I need to tweak it's appearance still and also make it so the different AO quality settings affect what it looks like.

Note that this effect requires a 3rd party DLL from Nvidia: this is not based in shaders.

**Comment by CrossVR** [comment]
We're trying to make a cross-platform port, I don't think adding more proprietary, closed-source DLLs is a good idea. Isn't there a HBAO+ shader we could implement instead?

**Comment by ghost** [comment]
Nvidia has never released an HBAO+ shader. That's the point: it's private, which is why it uses the external DLL. Just thought I'd offer, if you're not interested then whatever.

**Comment by CrossVR** [comment]
It looks like a proprietary implementation of the draw calls used for HDAO, the only difference is that it is more efficient and thus can use more occlusion samples. More information here: http://www.geforce.com/hardware/technology/hbao-plus/technology

Seems like something that could be re-implemented with open-source code, but without a white paper it would be difficult.

**Comment by ghost** [comment]
Fuck it. I'll keep it to myself. I don't know why I offer to help sometimes.

**Comment by CrossVR** [comment]
@Swartz27 Don't take it so personally, I'm just providing some feedback here. I'm not directing to you specifically to re-implement it. I'm just providing some more information for anyone willing to work on it.

Also, I'm not the only person on this project, my opinion is not final. Things like this are always open for discussion.

**Comment by ghost** [comment]
@Armada651 : I'm sorry about that. I've been a bit of an angry douche lately. I shouldn't have taken it personally and I shouldn't have blown my top like that. Plus you're right: if we want Open Xray to be compatible with a wide variety of systems we can do without it, especially since it's only for people with Nvidia cards.

I'll keep it to myself for now or perhaps release it and some other graphical effects I've worked on on a separate fork that people can grab themselves.

Sorry for being a dick to you,  it was uncalled for.

**Comment by Xottab-DUTY** [comment]
I think we can add HBAO+ with saving compatibility with a wide variety of systems :) Just make HBAO+ work on supported systems and make not working on not supported systems.

P.S. Please tell me if i done some mistakes in sentences. My English is not excellent.

**Comment by ghost** [comment]
Your English is quite good actually :)
And yes, that's a good idea. Not everyone will agree, but it never has to become part of this main branch.
In terms of HBAO+ I'm going to add it to my branch in the coming days. I have some other Nvidia effects too such as TXAA and Bokeh DOF (both for DX11) so assuming I get those working I can upload those too.

I'd do stuff for AMD users but since I don't have an AMD card it's not a priority for me.
