### ISSUE TITLE
-nointro switch disrupts Clear Sky start

### ISSUE THREAD

**Issue by donizettilorenzo** [OpenXRay/xray-16#866]
If you use the classic -nointro Clear Sky skips not only the intro video but the first game sequence too (Lebedev-Beanpolev dialogue, Scar's waking up).
Please fix (if possible)!

**Comment by Xottab-DUTY** [comment]
What's your OpenXRay version?

**Comment by donizettilorenzo** [comment]
https://ci.appveyor.com/project/OpenXRay/xray-16/build/job/yhfvkpte00gwj2a3

**Comment by Xottab-DUTY** [comment]
I remember I fixed that few months ago, so it should be there... Will need to recheck, then.
