### ISSUE TITLE
Crash after saving the game / Ошибка при сохранении игры

### ISSUE THREAD

**Issue by LostGhost1** [OpenXRay/xray-16#880]
English version:

Game crashes each time it is saved, automatically or manually. However, the resulting save files are saved and are valid, they load correctly, nonetheless, the game crashes after being saved.

Русская версия:

Игра выдает ошибку и зависает при каждом сохранении, автоматическом или ручном, при этом файлы сохранения рабочие, загружаются корректно

Platform: Arch Linux, recently updated
Engine compiled with system-provided allocator
Stalker, Call of Pripyat

Log attached
[stalker_log.txt](https://github.com/OpenXRay/xray-16/files/7058144/stalker_log.txt)

**Comment by Xottab-DUTY** [comment]
Судя по логу, перед самым вылетом была проблема с памятью.
Мы не так давно починили проблемы с аллокаторами, так что, баг вполне мог быть уже исправлен, поэтому и ещё потому что баг достаточно старый – закрываю.
