### ISSUE TITLE
Взаимодействие просветленного прицела и ПНВ

### ISSUE THREAD

**Issue by johndoe71rus** [OpenXRay/xray-16#881]
При использовании ночью ПНВ и просветленного прицела, в прицел ничего не видно.

**To Reproduce**
1. иметь на костюме ПНВ
2. иметь на оружии просветленный прицел
3. выйти в ночь и включить ПНВ.
4. Посмотреть на окрестности через бинокль, просветленный прицел, обычный прицел.

**Screenshots**
бинокль:
![image](https://user-images.githubusercontent.com/2989212/131255501-f9ae94d7-18c0-4e75-9096-dce96d9dca3c.png)

просветленный прицел:
![image](https://user-images.githubusercontent.com/2989212/131255508-bc38f691-a3e9-46c4-8866-c3955fcbeea1.png)

**Desktop (please complete the following information):**
 - все версии Windows/Linux
 - OpenXRay Rx64 build 8226, Aug 15 2021
Custom build from commit[1827610414fb30bfeba052ef9b77f0b53085e7e6] branch[dev]
Вероятно проблема еще с ванили.

**Comment by Xottab-DUTY** [comment]
Looks like intended vanilla behaviour. Not trivial to fix without breaking compatibility with vanilla...

**Comment by johndoe71rus** [comment]
а вот простой прицел и включенный ПНВ на шлеме 
![ss_johndoe_05-03-22_17-09-25_(zaton)](https://user-images.githubusercontent.com/7861172/166479521-0a6f1077-448c-485a-a73e-23c55310ebdb.jpg)
Если отталкиваться от предположения что ПНВ и прицел имеют разные фильтры, то в простом прицеле тоже должно быть ничего не видно.

**Comment by johndoe71rus** [comment]
![ss_johndoe_05-03-22_17-09-16_(zaton)](https://user-images.githubusercontent.com/7861172/166479716-f878524d-3b98-4faf-a960-a47f29db6368.jpg)
без ПНВ
