### ISSUE TITLE
Deboostify luabind

### ISSUE THREAD

**Issue by nitrocaster** [OpenXRay/xray-16#95]
See [OpenXRay/luabind-deboostified](https://github.com/OpenXRay/luabind-deboostified) and [decimad/luabind-deboostified](https://github.com/decimad/luabind-deboostified).

**Comment by alexgdi** [comment]
А почему решили эне заменять ее не готовой скомпиленной либой и не добавить ее в xraylibs?

**Comment by nitrocaster** [comment]
@alexgdi https://github.com/OpenXRay/luabind/blob/deboostify/README.md

**Comment by alexgdi** [comment]
@nitrocaster А, это luabind, а что насчет luajit? Я посмотрел проджект вроде бы там ничего нет.

**Comment by nitrocaster** [comment]
@alexgdi в чем проблема с LuaJIT? В `ai_cleanup` используется полностью оригинальный LuaJIT 2.0.4 с модифицированными скриптами сборки. В солюшене его нет, собирать нужно один раз, запустив скрипт вручную.

**Comment by nitrocaster** [comment]
Quick tests demonstrated that deboostified luabind gets compiled 6 times faster. There's a chance we could speed up xrGame compilation this way.

**Comment by alexgdi** [comment]
@nitrocaster, Я просто задумался, почему бы не поставлять его уже скомпиленным вместе с другими XRAY_LIBS.

**Comment by galek** [comment]
Есть и более быстрые байндинг-либы, но мы с товарищем их не используем(т.к они не проверены временем)

Вот он писал бенчмарк
https://github.com/bagobor/cpp2lua-buindings-battle

**Comment by nitrocaster** [comment]
Это, конечно, интересно, но есть ли какие-то результаты профайлинга, 
показывающие серьезное влияение оверхеда luabind на общую 
производительность?
На всякий случай, еще раз уточню, что главная цель этой "дебустификации" - ускорение компиляции.

On 11/30/2015 1:15 AM, Nick Galko wrote:

> Есть и более быстрые байндинг-либы, но мы с товарищем их не
> используем(т.к они не проверены временем)
> 
> Вот он писал бенчмарк
> https://github.com/bagobor/cpp2lua-buindings-battle
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/OpenXRay/xray-16/issues/95#issuecomment-160475902.

## 

Best regards, Pavel Kovalenko.

**Comment by galek** [comment]
В репозитории есть результаты бенчмарков(выполнения), развертывания темплейтов нету.

**Comment by nitrocaster** [comment]
Да, я смотрел. Реальные сценарии использования сильно отличаются от этих 
тестов, и делать какие-либо выводы из показанных результатов, на мой 
взгляд, преждевременно.

On 11/30/2015 2:01 AM, Nick Galko wrote:

> В репозитории есть результаты бенчмарков
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/OpenXRay/xray-16/issues/95#issuecomment-160479600.

## 

Best regards, Pavel Kovalenko.

**Comment by Kaffeine** [comment]
Было бы здорово, если бы изменения (исправления, дополнения) вошли в официальный релиз. Использование системных библиотек всегда предпочтительнее, чем "привязанных" к программе.
Жаль только, что это не всегда возможно. Например, с ODE мы явно застрянем надолго.

**Comment by nitrocaster** [comment]
Судя по рассылке и оригинальному репозиторию, официальных релизов не 
предвидится.

On 11/30/2015 8:44 AM, Alexandr Akulich wrote:

> Было бы здорово, если бы изменения (исправления, дополнения) вошли в
> официальный релиз. Использование системных библиотек всегда
> предпочтительнее, чем "привязанных" к программе.
> Жаль только, что это не всегда возможно. Например, с ODE мы явно
> застрянем надолго.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/OpenXRay/xray-16/issues/95#issuecomment-160523317.

## 

Best regards, Pavel Kovalenko.

**Comment by nitrocaster** [comment]
Now we use [luabind-deboostified fork](https://github.com/decimad/luabind-deboostified) with required modifications: [OpenXRay/luabind-deboostified](https://github.com/OpenXRay/luabind-deboostified). The library itself compiles ~6 times faster than 'canonical' luabind, xrGame compiles ~2 times faster.
