### ISSUE TITLE
Port from VS to CMake

### ISSUE THREAD

**Issue by tpimh** [OpenXRay/xray-16#98]
This will help to create Linux and OS X port. CMake can also be used with Visual Studio or other IDEs.

**Comment by Xottab-DUTY** [comment]
There is almost the same issue - #21

**Comment by tpimh** [comment]
Oh, didn't notice it. I think that CMake would be a good choice for such project.

**Comment by Xottab-DUTY** [comment]
Kaffeine already working around CMake. You can help him - https://github.com/Kaffeine/xray-16
